import * as T from './vendor/three.module.js';
import {plantPines} from './nature-render.mjs';
export function createForest(renderer,parent,library,forest){
 const targets=[],oldTarget=renderer.getRenderTarget(),oldColor=renderer.getClearColor(new T.Color),oldAlpha=renderer.getClearAlpha(),oldTone=renderer.toneMapping,oldShadows=renderer.shadowMap.enabled;
 const atlasScene=new T.Scene,camera=new T.OrthographicCamera(-2.3,2.3,3.5,-3.5,.1,30);camera.position.set(6,3.35,10);camera.lookAt(0,3.35,0);renderer.shadowMap.enabled=false;renderer.toneMapping=T.NoToneMapping;renderer.setClearColor(0,0);
 // The atlas stores albedo only; current scene lighting supplies its shading.
 const bark=new T.MeshBasicMaterial({map:library.bark.map}),leaf=new T.MeshBasicMaterial({map:library.leaf.map,alphaMap:library.leaf.alphaMap,alphaTest:.45,side:T.DoubleSide});
 try{for(const variant of library.variants){atlasScene.clear();atlasScene.add(new T.Mesh(variant.wood,bark),new T.Mesh(variant.needles,leaf));const target=new T.WebGLRenderTarget(512,512,{samples:4});target.texture.colorSpace=T.LinearSRGBColorSpace;target.texture.generateMipmaps=true;target.texture.minFilter=T.LinearMipmapLinearFilter;renderer.setRenderTarget(target);renderer.clear();renderer.render(atlasScene,camera);targets.push(target);}}finally{renderer.setRenderTarget(oldTarget);renderer.setClearColor(oldColor,oldAlpha);renderer.toneMapping=oldTone;renderer.shadowMap.enabled=oldShadows;bark.dispose();leaf.dispose();}
 const card=new T.PlaneGeometry(4.6,7);card.translate(0,3.35,0);const materials=targets.map(target=>{const m=new T.MeshStandardMaterial({map:target.texture,alphaTest:.3,side:T.DoubleSide,roughness:1,color:'#ffffff'});m.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <project_vertex>',`vec4 center=modelMatrix*instanceMatrix*vec4(0.0,0.0,0.0,1.0);
 float treeWidth=length(instanceMatrix[0].xyz);float treeHeight=length(instanceMatrix[1].xyz);
 vec3 direction=normalize(vec3(cameraPosition.x-center.x,0.0,cameraPosition.z-center.z)+vec3(.00001,0.0,0.0));
 vec3 right=vec3(direction.z,0.0,-direction.x);
 vec4 forestWorld=vec4(center.xyz+right*position.x*treeWidth+vec3(0.0,position.y*treeHeight,0.0),1.0);
 vec4 mvPosition=viewMatrix*forestWorld;
 gl_Position=projectionMatrix*mvPosition;`);s.vertexShader=s.vertexShader.replace('#include <worldpos_vertex>','vec4 worldPosition=forestWorld;');s.vertexShader=s.vertexShader.replace('#include <defaultnormal_vertex>','vec3 treeFacing=normalize(cameraPosition-(modelMatrix*instanceMatrix*vec4(0.0,0.0,0.0,1.0)).xyz);vec3 transformedNormal=normalMatrix*normalize(vec3(treeFacing.x*.25,.9,treeFacing.z*.25));');s.fragmentShader=s.fragmentShader.replace('#include <normal_fragment_begin>', '#include <normal_fragment_begin>\nnormal=normalize(vNormal);');};m.customProgramCacheKey=()=> 'forest-card-v2';return m;});
 // Fixed crossed silhouettes cast distant shadows independently of the viewing camera.
 const shadowCard=new T.BufferGeometry,positions=[],uvs=[],indices=[];
 for(let side=0;side<2;side++){const g=card.clone();g.rotateY(side*Math.PI/2);positions.push(...g.attributes.position.array);uvs.push(...g.attributes.uv.array);indices.push(...Array.from(g.index.array,n=>n+side*4));g.dispose();}
 shadowCard.setAttribute('position',new T.Float32BufferAttribute(positions,3));shadowCard.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));shadowCard.setIndex(indices);shadowCard.computeVertexNormals();
 const invisible=targets.map(t=>new T.MeshBasicMaterial({map:t.texture,alphaTest:.3,side:T.DoubleSide,colorWrite:false,depthWrite:false}));
 const depths=targets.map(t=>new T.MeshDepthMaterial({depthPacking:T.RGBADepthPacking,map:t.texture,alphaTest:.3,side:T.DoubleSide}));
 const dummy=new T.Object3D,chunks=forest.chunks.map(chunk=>{const root=new T.Group,low=new T.Group;root.add(low);parent.add(root);for(let v=0;v<3;v++){const ps=chunk.trees.filter((p,i)=>(p.variant??i%3)===v);if(!ps.length)continue;const mesh=new T.InstancedMesh(card,materials[v],ps.length),caster=new T.InstancedMesh(shadowCard,invisible[v],ps.length);caster.castShadow=true;caster.customDepthMaterial=depths[v];mesh.receiveShadow=true;ps.forEach((p,i)=>{dummy.position.set(p.x,p.y-.035,p.z);dummy.scale.set(p.scale*(p.width??1),p.scale*(p.height??1),p.scale*(p.width??1));dummy.rotation.set(0,0,0);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,new T.Color(p.tint??'#ffffff'));dummy.rotation.y=(p.x*17+p.z*29)%6.28;dummy.updateMatrix();caster.setMatrixAt(i,dummy.matrix);});mesh.computeBoundingSphere();mesh.boundingSphere.radius+=3;caster.computeBoundingSphere();low.add(mesh,caster);}return{...chunk,root,low,high:null,detail:false};});
 let lastX=Infinity,lastZ=Infinity,lastY=Infinity,stats={detailed:0,distant:forest.trees.length,chunks:chunks.length};
 function update(view,force=false){if(!force&&Math.hypot(view.position.x-lastX,view.position.z-lastZ,view.position.y-lastY)<2)return;lastX=view.position.x;lastZ=view.position.z;lastY=view.position.y;stats={detailed:0,distant:0,chunks:chunks.length};for(const c of chunks){const y=c.trees.reduce((sum,p)=>sum+p.y,0)/c.trees.length,d=Math.hypot(c.x-lastX,c.z-lastZ,(y+3-lastY)*.85),detail=d<(c.detail?44:38);if(detail&&!c.high){c.high=new T.Group;plantPines({world:c.high},library,c.trees);c.root.add(c.high);}c.detail=detail;c.low.visible=!detail;if(c.high)c.high.visible=detail;stats[detail?'detailed':'distant']+=c.trees.length;}}
 return{update,stats:()=>({...stats,total:forest.trees.length,atlasCount:targets.length,shadowTrees:forest.trees.length}),dispose(){for(const t of targets)t.dispose();card.dispose();shadowCard.dispose();[...materials,...invisible,...depths].forEach(m=>m.dispose());}};
}
