import test from 'node:test';import assert from 'node:assert/strict';
import {generateRoute,reuseDefaults,serializeReuse,restoreReuse,validateReuse} from './reuse-core.mjs';
import {generateTerrain,scatterTrees,pineDimensions} from './reuse-core.mjs';
import {makePineGeometry} from './nature-render.mjs';

test('rendered pine geometry fits the metre-scale clearance envelope',()=>{for(const seed of [51,157,391]){const tree=makePineGeometry(seed);for(const g of Object.values(tree)){const pos=g.attributes.position;for(let i=0;i<pos.count;i++){assert.ok(Math.hypot(pos.getX(i),pos.getZ(i))<=pineDimensions.radius);assert.ok(pos.getY(i)>=-.001&&pos.getY(i)<=pineDimensions.height+.001);}g.dispose();}}});
test('natural forest avoids overlapping trunk clusters and keeps full canopy away from the road',()=>{for(const scene of ['lake','mountain'])for(const treeScale of [.5,2]){const road=generateRoute({scene,width:4}),trees=scatterTrees(road,{treeDensity:600,treeScale});for(let i=0;i<trees.length;i++){const p=trees[i];assert.ok(road.nearest(p.x,p.z).distance>=road.width/2+pineDimensions.radius*p.scale+.3);for(let j=0;j<i;j++)assert.ok(Math.hypot(p.x-trees[j].x,p.z-trees[j].z)>=(p.scale+trees[j].scale)*1.5);}}});
test('terrain parameters change road elevations and tree roots together',()=>{for(const scene of ['lake','mountain']){const a=generateRoute({scene,width:2.4,hillHeight:0}),b=generateRoute({scene,width:2.4,hillHeight:2.8,hillX:-5});const pa=scatterTrees(a),pb=scatterTrees(b);assert.equal(pa.length,pb.length);assert.ok(pa.some((p,i)=>Math.abs(p.y-pb[i].y)>.1));for(let i=0;i<pb.length;i++){assert.equal(pb[i].x,pa[i].x);assert.equal(pb[i].z,pa[i].z);assert.equal(pb[i].y,b.terrain(pb[i].x,pb[i].z));}assert.ok(Math.max(...a.points.map((p,i)=>Math.abs(p.y-b.points[i].y)))>.1);for(let u=0;u<1;u+=.02){const q=b.sample(b.length*u);assert.ok(Math.abs(b.terrain(q.x,q.z)+.04-q.y)<.03);}}});
test('tree scatter is deterministic, empty at zero density, and respects canopy clearance',()=>{const road=generateRoute({scene:'mountain',width:4,hillHeight:3});for(const treePattern of ['uniform','clustered'])for(const treeScale of [.5,2]){const c={treeScale,treeDensity:600,treePattern},a=scatterTrees(road,c);assert.deepEqual(a,scatterTrees(road,c));assert.ok(a.every(p=>road.nearest(p.x,p.z).distance-road.width/2-.58*p.scale>=.25-1e-7));}assert.equal(scatterTrees(road,{treeDensity:0}).length,0);assert.notDeepEqual(scatterTrees(road,{treePattern:'uniform'}),scatterTrees(road,{treePattern:'clustered'}));});
test('moving the primary hill moves its high region; invalid nature parameters fail',()=>{const a=generateTerrain({scene:'mountain',hillHeight:3,hillX:-8}),b=generateTerrain({scene:'mountain',hillHeight:3,hillX:8});assert.ok(a(-8,-2)>b(-8,-2));assert.ok(b(8,-2)>a(8,-2));for(const p of [{hillHeight:-1},{hillX:9},{treeScale:0},{treeDensity:601},{treeDensity:2.5},{treePattern:'random-unknown'}])assert.throws(()=>validateReuse(p));});
test('old five-field saves migrate to nature defaults while v2 saves retain nature settings',()=>{const legacy={width:4,recipe:'wet',rightRoute:'direct',wire:false,paused:true};assert.deepEqual(restoreReuse(JSON.stringify({version:1,settings:legacy})),{...reuseDefaults(),...legacy});const c={...reuseDefaults(),treeScale:2,treeDensity:600,treePattern:'clustered',hillHeight:3,hillX:-8};assert.deepEqual(restoreReuse(serializeReuse(c)),c);assert.throws(()=>restoreReuse(JSON.stringify({version:2,settings:legacy})));});
test('same generator handles closed lake and both open mountain routes',()=>{for(const scene of ['lake','mountain'])for(const route of ['winding','direct'])for(const width of [1.2,4]){const t=generateRoute({scene,route,width});assert.equal(t.positions.length,482*3);for(let s=0;s<t.length;s+=.7){const a=t.sample(s,-width/2),b=t.sample(s,width/2),c=t.sample(s);assert.ok(Math.abs(Math.hypot(a.x-b.x,a.z-b.z)-width)<1e-6);assert.ok(Math.abs(t.terrain(c.x,c.z)+.04-c.y)<.03);}assert.ok(t.positions.every(Number.isFinite));}});
test('route change regenerates geometry, width changes do not stretch lengthwise UV scale',()=>{const a=generateRoute({scene:'mountain',route:'winding',width:2}),b=generateRoute({scene:'mountain',route:'direct',width:2}),c=generateRoute({scene:'mountain',route:'winding',width:4});assert.ok(a.length>b.length);assert.equal(a.uvs[240],c.uvs[240]);assert.notDeepEqual(a.positions,c.positions);});
test('saved configuration restores and rejects invalid inputs',()=>{const c={...reuseDefaults(),width:4,recipe:'wet'};assert.deepEqual(restoreReuse(serializeReuse(c)),c);for(const p of [{width:0},{width:NaN},{recipe:'__proto__'},{rightRoute:'bad'},{unknown:1}])assert.throws(()=>validateReuse(p));assert.throws(()=>restoreReuse('{"version":1,"settings":{}}'));});
