import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {stages,flagsFor,initialSurface,configureSurface,surfaceHeight,surfaceStats} from './surface-model.mjs';
const $=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
let cfg=initialSurface(),frozen=null,renderer,camera,controls,ready=false,disposed=false,time=0,last=0,renderError=null;
const sides=[],textures={},abort=new AbortController();
const assetIds={mud:'brown_mud_dry',grass:'aerial_grass_rock'};
const flagLabels={color:'颜色图',light:'光照',normal:'法线图',rough:'粗糙度图',grass:'真实草叶'};
const ranges=[['repeat','纹理重复',.5,5,.25,'次','次数越大，同一图案铺得越密。'],['normalStrength','法线强度',0,3,.1,'','只在光照与法线都开启时生效。'],['roughness','粗糙度系数',.08,1,.02,'','有粗糙度图时，与图中的数值相乘。'],['sun','太阳方向',0,360,5,'°','照明方向改变，不改变输入图片。'],['relief','真实几何起伏',0,1,.05,'','公式直接改变顶点；未使用位移贴图。'],['density','草叶数量',0,1600,50,'株','每株包含两个三角形；仅在草叶开启时显示。']];
function renderControls(){
 $('surface-steps').innerHTML=stages.map((s,i)=>`<button data-step="${i}" aria-pressed="${cfg.step===i}"><small>STEP 0${i+1}</small>${s.title}</button>`).join('');
 $('surface-flags').innerHTML=Object.entries(flagLabels).map(([key,label])=>`<label><input type="checkbox" data-flag="${key}" ${cfg[key]?'checked':''}>${label}</label>`).join('');
 $('surface-ranges').innerHTML=ranges.map(([key,label,min,max,step,unit,hint])=>`<div class="control"><label for="surface-${key}">${label}<output id="out-${key}">${cfg[key]}${unit}</output></label><input id="surface-${key}" data-range="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${cfg[key]}"><small>${hint}</small></div>`).join('');
 for(const key of ['material','wire','shadows','wind']){const el=$('surface-'+key);if(el.type==='checkbox')el.checked=cfg[key];else el.value=cfg[key];}
 updateCopy();
}
function updateCopy(){const s=stages[cfg.step];$('surface-step-number').textContent=`构建步骤 0${cfg.step+1} / 06`;$('surface-title').textContent=s.title;$('surface-explanation').textContent=s.detail;$('surface-action').textContent=s.action;$('surface-prev').disabled=cfg.step===0;$('surface-next').disabled=cfg.step===5;$('current-name').textContent=s.title+' · 可独立调节';$('reference-name').textContent=frozen?'已锁定的配置':cfg.step===0?'相同白模起点':stages[cfg.step-1].title;
 $('reference-status').textContent=frozen?'左侧已锁定：更换右侧地表、参数或步骤不会改变左侧。镜头继续同步。':'左侧为前一步，使用相同材质、光源与参数；右侧为当前配置。';
 const stat=surfaceStats(cfg);$('surface-metrics').innerHTML=`<div><span>底板顶点 · 法线不会增加</span><strong>${stat.vertices.toLocaleString()}</strong></div><div><span>草叶额外三角形</span><strong>${stat.grassTriangles.toLocaleString()}</strong></div><div><span>参与计算的贴图</span><strong>${stat.activeMaps.length} / 3</strong></div>`;
 const id=assetIds[cfg.material];$('surface-maps').innerHTML=[['diff','颜色',cfg.color],['nor_gl','法线',cfg.light&&cfg.normal],['rough','粗糙度',cfg.light&&cfg.rough]].map(([channel,label,active])=>`<figure data-active="${active}"><img src="../assets/textures/${id}_${channel}_1k.jpg" alt="${cfg.material==='mud'?'泥土':'草岩'}${label}原始贴图"><figcaption><strong>${label}</strong>${active?'正在参与计算':'当前未参与'}</figcaption></figure>`).join('');
 $('surface-map-status').textContent=`当前：${stat.activeMaps.join(' + ')||'未使用表面贴图'}。${!cfg.light&&(cfg.normal||cfg.rough)?'光照已关闭，法线与粗糙度不会产生受光效果。':''}${cfg.relief>0?'几何起伏已开启，轮廓变化来自顶点位置。':'底板保持平面，法线不会改变外轮廓。'}`;
}
function currentReference(){return frozen?{...frozen}:{...cfg,...flagsFor(Math.max(0,cfg.step-1)),step:Math.max(0,cfg.step-1)};}
function setSurface(patch,{refresh=true}={}){cfg=configureSurface(cfg,patch);if(ready){applySide(sides[0],currentReference());applySide(sides[1],cfg);}if(refresh)renderControls();else updateCopy();return state();}
function rng(){let n=17;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
function createSide(){const scene=new T.Scene;scene.background=new T.Color('#b7c4c8');const sun=new T.DirectionalLight('#fff0d6',3.4);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:1,far:30});sun.shadow.normalBias=.025;sun.shadow.bias=-.0002;scene.add(sun,new T.HemisphereLight('#d8ebed','#7c7566',1.7));
 const geo=new T.PlaneGeometry(6,6,64,64);geo.rotateX(-Math.PI/2);const ground=new T.Mesh(geo,new T.MeshStandardMaterial({color:'#ddddcf'}));ground.receiveShadow=true;scene.add(ground);
 const base=new T.Mesh(new T.BoxGeometry(6.08,.18,6.08),new T.MeshStandardMaterial({color:'#495953',roughness:.85}));base.position.y=-.12;scene.add(base);
 const bladeGeo=new T.BufferGeometry;bladeGeo.setAttribute('position',new T.Float32BufferAttribute([-.035,0,0,.035,0,0,.012,.19,.035,.035,0,0,.042,.36,.08,.012,.19,.035],3));bladeGeo.computeVertexNormals();
 const grassMat=new T.MeshStandardMaterial({color:'#708d38',roughness:.95,side:T.DoubleSide});const wind={value:0};grassMat.onBeforeCompile=shader=>{shader.uniforms.surfaceWind=wind;shader.vertexShader='uniform float surfaceWind;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.x += sin(surfaceWind + instanceMatrix[3].x * 2.1 + instanceMatrix[3].z) * transformed.y * transformed.y * 0.7;');};
 const grass=new T.InstancedMesh(bladeGeo,grassMat,1600);grass.castShadow=true;grass.receiveShadow=true;scene.add(grass);const random=rng(),placements=Array.from({length:1600},()=>({x:(random()-.5)*5.7,z:(random()-.5)*5.7,angle:random()*Math.PI*2,scale:.5+random()*1.2,color:new T.Color().setHSL(.19+random()*.06,.38,.25+random()*.15)}));
 const localTextures={};for(const [id,maps] of Object.entries(textures)){localTextures[id]={};for(const [channel,texture] of Object.entries(maps)){const t=texture.clone();t.needsUpdate=true;localTextures[id][channel]=t;}}
 return{scene,sun,ground,base,grass,grassMat,wind,placements,textures:localTextures,lastRelief:NaN,config:null};
}
function applySide(side,c){const maps=side.textures[c.material];for(const tex of Object.values(maps))tex.repeat.setScalar(c.repeat);
 const old=side.ground.material;side.ground.material=c.light?new T.MeshStandardMaterial({color:c.color?'#ffffff':'#d9dccc',map:c.color?maps.diff:null,normalMap:c.normal?maps.nor_gl:null,normalScale:new T.Vector2(c.normalStrength,c.normalStrength),roughnessMap:c.rough?maps.rough:null,roughness:c.roughness,metalness:0,side:T.DoubleSide,wireframe:c.wire}):new T.MeshBasicMaterial({color:c.color?'#ffffff':'#d9dccc',map:c.color?maps.diff:null,side:T.DoubleSide,wireframe:c.wire});old.dispose();
 if(side.lastRelief!==c.relief){const a=side.ground.geometry.attributes.position;for(let i=0;i<a.count;i++)a.setY(i,surfaceHeight(a.getX(i),a.getZ(i),c.relief));a.needsUpdate=true;side.ground.geometry.computeVertexNormals();side.ground.geometry.computeBoundingSphere();side.base.position.y=-.12-.36*c.relief;const dummy=new T.Object3D;side.placements.forEach((p,i)=>{dummy.position.set(p.x,surfaceHeight(p.x,p.z,c.relief),p.z);dummy.rotation.set(0,p.angle,0);dummy.scale.setScalar(p.scale);dummy.updateMatrix();side.grass.setMatrixAt(i,dummy.matrix);side.grass.setColorAt(i,p.color);});side.grass.instanceMatrix.needsUpdate=true;side.grass.instanceColor.needsUpdate=true;side.grass.computeBoundingSphere();side.lastRelief=c.relief;}
 side.grass.visible=c.grass;side.grass.count=c.density;side.grass.material=c.light?side.grassMat:(side.unlitGrass??=new T.MeshBasicMaterial({color:'#708d38',side:T.DoubleSide}));if(side.unlitGrass)side.unlitGrass.onBeforeCompile=side.grassMat.onBeforeCompile;side.sun.castShadow=c.shadows;side.grass.castShadow=c.shadows;const angle=c.sun*Math.PI/180;side.sun.position.set(Math.cos(angle)*6,3.5,Math.sin(angle)*6);side.config={...c};side.wind.value=c.wind?time:0;
}
function state(){return{ready:ready&&!renderError,renderError,config:{...cfg},reference:currentReference(),locked:!!frozen,stats:surfaceStats(cfg),loadedTextures:Object.keys(textures).reduce((n,k)=>n+Object.keys(textures[k]).length,0),rendered:sides.map(s=>({colorMap:!!s.ground.material.map,normalMap:!!s.ground.material.normalMap,roughnessMap:!!s.ground.material.roughnessMap,lit:!!s.ground.material.isMeshStandardMaterial,vertices:s.ground.geometry.attributes.position.count,grass:s.grass.visible?s.grass.count:0,relief:s.lastRelief,drawnTriangles:s.drawnTriangles||0}))};}
function resize(){const el=$('surface-view'),w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/2/h;camera.zoom=Math.min(1,camera.aspect/.85);camera.updateProjectionMatrix();}
function frame(now){if(disposed)return;const dt=Math.min((now-last)/1000||0,.05);last=now;if(!document.hidden){time+=dt;controls.update();renderer.setScissorTest(false);renderer.clear();renderer.setScissorTest(true);const width=$('surface-view').clientWidth,height=$('surface-view').clientHeight,half=Math.floor(width/2);for(let i=0;i<2;i++){sides[i].wind.value=sides[i].config.wind?time:0;renderer.setViewport(i*half,0,i?width-half:half,height);renderer.setScissor(i*half,0,i?width-half:half,height);renderer.render(sides[i].scene,camera);sides[i].drawnTriangles=renderer.info.render.triangles;}}requestAnimationFrame(frame);}
function view(kind){if(kind==='low')camera.position.set(7,1.2,8);else camera.position.set(4,10,5);controls.target.set(0,.1,0);controls.update();}
function action(name){if(name==='lock'){frozen={...cfg};setSurface({});}else if(name==='unlock'){frozen=null;setSurface({});}else if(name==='low'||name==='top')view(name);else if(name==='reset'){cfg=initialSurface();frozen=null;setSurface({});camera.position.set(7,6,9);controls.target.set(0,.1,0);controls.update();}else if(name==='pbr'){frozen=null;setSurface({...initialSurface(),step:4,roughness:.35,material:'mud'});$('surface-view').scrollIntoView({block:'start'});}else if(name==='geometry'){frozen={...initialSurface(),...flagsFor(4),step:4,material:'grass',relief:0};setSurface({step:5,material:'grass',relief:.8,density:1000});view('low');$('surface-view').scrollIntoView({block:'start'});}else throw Error('未知操作');return state();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!ready)return;if(b.dataset.step!==undefined)return setSurface({step:Number(b.dataset.step)});if(b.dataset.surfacePreset)return action(b.dataset.surfacePreset);const names={'surface-low':'low','surface-top':'top','surface-lock':'lock','surface-unlock':'unlock','surface-reset':'reset'};if(names[b.id])return action(names[b.id]);if(b.id==='surface-prev')setSurface({step:Math.max(0,cfg.step-1)});if(b.id==='surface-next')setSurface({step:Math.min(5,cfg.step+1)});});
document.addEventListener('change',e=>{if(!ready)return;if(e.target.dataset.flag)return setSurface({[e.target.dataset.flag]:e.target.checked});if(e.target.id==='surface-material')return setSurface({material:e.target.value});for(const key of ['wire','shadows','wind'])if(e.target.id==='surface-'+key)return setSurface({[key]:e.target.checked});});
document.addEventListener('input',e=>{const key=e.target.dataset.range;if(!key||!ready)return;setSurface({[key]:Number(e.target.value)},{refresh:false});$('out-'+key).textContent=cfg[key]+ranges.find(r=>r[0]===key)[5];});
async function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const content=()=>({content:[{type:'text',text:JSON.stringify(state())}]});const properties={step:{type:'integer',minimum:0,maximum:5},material:{type:'string',enum:['mud','grass']}};for(const [k,,min,max] of ranges)properties[k]={type:k==='density'?'integer':'number',minimum:min,maximum:max};for(const k of [...Object.keys(flagLabels),'wire','shadows','wind'])properties[k]={type:'boolean'};
 const tools=[{name:'read_surface_lab',description:'Read the visible surface comparison, input textures, actual material slots and geometry counts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:content},{name:'configure_surface_lab',description:'Adjust the visible surface experiment using its steps, switches and sliders. This changes only this local experiment.',inputSchema:{type:'object',properties,additionalProperties:false},annotations:{readOnlyHint:false},execute:patch=>{setSurface(patch);return content();}},{name:'surface_lab_action',description:'Use the visible reference lock, camera view, reset, or implemented alternative demonstrations.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['lock','unlock','low','top','reset','pbr','geometry']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({action:name})=>{action(name);return content();}}];for(const tool of tools)await context.registerTool(tool,{signal:abort.signal});}
renderControls();
try{renderer=new T.WebGLRenderer({canvas:$('surface-canvas'),antialias:true});renderer.debug.onShaderError=()=>{renderError='材质着色器未成功编译';};renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.autoClear=false;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;camera=new T.PerspectiveCamera(42,1,.05,100);camera.position.set(7,6,9);controls=new OrbitControls(camera,$('surface-canvas'));controls.target.set(0,.1,0);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=24;controls.maxPolarAngle=Math.PI*.485;controls.enablePan=false;
 const loader=new T.TextureLoader;await Promise.all(Object.entries(assetIds).flatMap(([key,id])=>['diff','nor_gl','rough'].map(async channel=>{const texture=await loader.loadAsync(`../assets/textures/${id}_${channel}_1k.jpg`);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(channel==='diff')texture.colorSpace=T.SRGBColorSpace;(textures[key]??={})[channel]=texture;})));
 sides.push(createSide(),createSide());ready=true;setSurface({});resize();const observer=new ResizeObserver(resize);observer.observe($('surface-view'));$('surface-loading').hidden=true;requestAnimationFrame(frame);try{await registerTools();}catch(e){console.warn('Optional page tools unavailable',e);}window.addEventListener('pagehide',()=>{disposed=true;abort.abort();observer.disconnect();controls.dispose();renderer.dispose();},{once:true});
}catch(error){$('surface-loading').innerHTML='<strong>材质实验暂时无法启动</strong><p>请确认浏览器支持 WebGL，且本地素材文件完整。</p><button onclick="location.reload()">重新加载</button>';console.error(error);}
