import {outdoorPresets} from './outdoor-recipe.mjs';
import {addEnvironmentCover} from './environment-render.mjs';
import {environments} from './environment-core.mjs';
import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {loadPines,blendGround,backdrop} from './nature-render.mjs';
import {expandForest,outerHeight,forestHeight} from './forest-core.mjs';
import {createForest} from './forest-render.mjs';
import {makeCanopySampler,enrichGroundGeometry,enrichGroundMaterial} from './landscape-surface.mjs';
import {recipes} from './reuse-core.mjs';
import {addVehicleRig,createWalker} from './outdoor-actors.mjs';
import {roundedBox,tentFabric,addCampDetails,addRouteDetails} from './outdoor-details.mjs';
import {makeOutdoor,journeyAt,chapters,lightAt,clamp,smooth,actorAt,solarDirection,shadowAt,inspectOutdoorLayout} from './outdoor-core.mjs';
import {mountOutdoorEditor} from './outdoor-editor.mjs';
const $=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);const entryParams=new URLSearchParams(location.search),entryLayout=Object.hasOwn(outdoorPresets,entryParams.get('layout'))?outdoorPresets[entryParams.get('layout')]:{};let land=makeOutdoor(entryLayout),pineLibrary,editor;
let groundCover,valleyForest,forestRenderer,performanceSample={frames:0,elapsed:0,fps:0},ready=false,renderer,camera,controls,progress=entryParams.get('view')==='sunrise'?.97:0,playing=false,cameraMode='follow',lightMode='auto',last=0,disposed=false,renderError=null,previousChapter='',frameCount=0,frameDt=1/60;
const scene=new T.Scene(),world=new T.Group(),vegetation=new T.Group(),abort=new AbortController(),maps={};scene.add(world,vegetation);
const sun=new T.DirectionalLight('#ffddae',3),ambient=new T.HemisphereLight('#b8d3e2','#70604d',1.5);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-175,right:175,top:175,bottom:-175,near:1,far:680});sun.shadow.normalBias=.025;sun.shadow.bias=-.000025;scene.add(sun,sun.target,ambient);scene.fog=new T.Fog('#aebfbc',70,220);
const skyMaterial=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color('#779cac')},horizon:{value:new T.Color('#efc68d')},low:{value:new T.Color('#91988d')},sunDirection:{value:V(.41,.05,-.91)},dawn:{value:0}},vertexShader:'varying vec3 vDirection;void main(){vDirection=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:`varying vec3 vDirection;uniform vec3 top;uniform vec3 horizon;uniform vec3 low;uniform vec3 sunDirection;uniform float dawn;
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
 float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}
 void main(){vec3 direction=normalize(vDirection);float y=direction.y;float facing=pow(max(0.0,dot(normalize(direction.xz),normalize(sunDirection.xz))),7.0);vec3 c=mix(horizon,top,smoothstep(.01,.42,y));c=mix(c,low,1.0-smoothstep(-.18,0.0,y));
 float band=exp(-pow((y-.035)/.13,2.0))*facing*dawn;c=mix(c,vec3(.95,.24,.075),band*.50);
 float halo=pow(max(0.0,dot(direction,sunDirection)),90.0)*dawn;c+=vec3(.85,.33,.09)*halo*.55;
 vec2 cloudUv=vec2(atan(direction.x,-direction.z)*18.0,y*90.0);float clouds=noise(cloudUv)*.65+noise(cloudUv*2.7)*.35;float veil=smoothstep(.51,.78,clouds)*smoothstep(.015,.07,y)*(1.0-smoothstep(.16,.3,y))*facing*dawn*.32;c=mix(c,vec3(.94,.55,.32),veil);
 gl_FragColor=vec4(c,1.0);
 #include <tonemapping_fragment>
 #include <colorspace_fragment>
 }`});
const sky=new T.Mesh(new T.SphereGeometry(280,32,16),skyMaterial);sky.renderOrder=-100;scene.add(sky);
const sunDisc=new T.Mesh(new T.SphereGeometry(3.8,32,20),new T.MeshBasicMaterial({color:'#ffe3a6',fog:false,toneMapped:false}));scene.add(sunDisc);const glow=new T.Mesh(new T.PlaneGeometry(26,26),new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec2 vUv;void main(){float a=pow(max(0.0,1.0-length(vUv-.5)*2.0),3.0)*.48;gl_FragColor=vec4(1.0,.38,.10,a);}'}));scene.add(glow);
function material(color,roughness=.9){return new T.MeshStandardMaterial({color,roughness});}
function mesh(g,m,parent=world){const o=new T.Mesh(g,m);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
function box(w,h,d,color,parent=world){return mesh(new T.BoxGeometry(w,h,d),material(color),parent);}
function groundMaterial(asset='aerial_grass_rock',tint='#d2cbb0',tile=2.2){const channels={};for(const c of ['diff','nor_gl','rough']){const t=maps[asset][c].clone();t.repeat.setScalar(1/tile);t.needsUpdate=true;channels[c]=t;}return new T.MeshStandardMaterial({map:channels.diff,normalMap:channels.nor_gl,roughnessMap:channels.rough,normalScale:new T.Vector2(.8,.8),color:tint,roughness:.95,side:T.DoubleSide});}
function terrain(){const shade=makeCanopySampler(valleyForest.trees);const g=new T.PlaneGeometry(64,64,180,180),distances=[];g.rotateX(-Math.PI/2);const p=g.attributes.position,uv=g.attributes.uv;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,land.terrain(x,z));uv.setXY(i,x,z);distances.push(land.nearest(x,z).distance);}g.setAttribute('roadDistance',new T.Float32BufferAttribute(distances,1));g.computeVertexNormals();const mat=groundMaterial();blendGround(mat,maps.brown_mud_dry.diff,maps.brown_mud_dry.nor_gl,3.2,recipes.dry);enrichGroundGeometry(g,shade);enrichGroundMaterial(mat,maps.rock_2,land.recipe.environment,true);mesh(g,mat).castShadow=false;
 const side={world,name:'mountain',road:{terrain:land.terrain,nearest:land.nearest,width:3.2}};groundCover=addEnvironmentCover(world,land,(x,z)=>forestHeight(land,x,z),maps.rock_2);const far=backdrop(side,groundMaterial('aerial_grass_rock','#d2cbb0',2.2),(x,z)=>outerHeight(land,x,z));enrichGroundGeometry(far.geometry,shade);enrichGroundMaterial(far.material,maps.rock_2,land.recipe.environment,false);
}
const lamps=[],lampMaterials=[];
function lantern(x,y,z,parent=world){const group=new T.Group;parent.add(group);group.position.set(x,y,z);const cage=box(.17,.28,.17,'#303630',group);cage.position.y=.14;const glow=new T.MeshStandardMaterial({color:'#ffe1a2',emissive:'#ffb650',emissiveIntensity:2,roughness:.5});const bulb=mesh(new T.CylinderGeometry(.065,.065,.19,10),glow,group);bulb.position.y=.17;lampMaterials.push(glow);const light=new T.PointLight('#ffc276',3,8,2);light.position.y=.3;group.add(light);light.castShadow=y>.7;light.shadow.mapSize.set(512,512);light.shadow.bias=-.001;lamps.push(light);return group;}
function tent(x,z,angle,color){const group=new T.Group;group.position.set(x,land.terrain(x,z)+.04,z);group.rotation.y=angle;world.add(group);const vertices=[-1.3,0,-1.5,1.3,0,-1.5,0,1.65,-1.5,-1.3,0,1.5,1.3,0,1.5,0,1.65,1.5],g=new T.BufferGeometry;g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setIndex([0,2,5,0,5,3,2,1,4,2,4,5,0,1,2,3,5,4]);g.computeVertexNormals();const fabric=material(color);fabric.side=T.DoubleSide;const end=new T.BufferGeometry;end.setAttribute('position',new T.Float32BufferAttribute([-1.3,0,-1.5,1.3,0,-1.5,0,1.65,-1.5],3));end.computeVertexNormals();mesh(end,fabric,group);g.dispose();tentFabric(group,color);const door=new T.BufferGeometry;door.setAttribute('position',new T.Float32BufferAttribute([-.87,.03,1.51,.87,.03,1.51,0,1.38,1.51],3));door.computeVertexNormals();mesh(door,new T.MeshStandardMaterial({color:'#222e2b',side:T.DoubleSide}),group);box(2.7,.045,3.15,'#514e36',group).position.y=.015;for(const sign of [-1,1]){const pole=mesh(new T.CylinderGeometry(.023,.023,2.12,6),material('#c8c9b8'),group);pole.position.set(sign*.65,.82,1.53);pole.rotation.z=sign*.67;}lantern(1.55,.02,1.4,group);}
function camp(){tent(land.camp.x-1.3,land.camp.z+.8,.2,'#c07c40');tent(land.camp.x+2.3,land.camp.z+1.5,-.3,'#9f9d6c');const table=new T.Group;table.position.set(land.camp.x+.3,land.camp.y,land.camp.z-2.3);world.add(table);box(1.6,.09,.8,'#a18b62',table).position.y=.75;for(const x of [-.62,.62])for(const z of [-.25,.25])box(.065,.73,.065,'#424d43',table).position.set(x,.365,z);for(const x of [-1.2,1.2]){box(.55,.06,.6,'#746748',table).position.set(x,.4,0);box(.55,.6,.06,'#746748',table).position.set(x,.67,-.25);for(const z of [-.22,.22])box(.06,.4,.06,'#424d43',table).position.set(x,.2,z);}lantern(.1,.79,.08,table);box(.5,.38,.38,'#bbc4b8',table).position.set(1,.19,1.1);
 // An entrance sign and parking bay are outside the tents and the driving corridor.
 const sign=new T.Group;sign.position.set(land.camp.x-4,land.terrain(land.camp.x-4,land.camp.z),land.camp.z);world.add(sign);box(.1,1.5,.1,'#625c46',sign).position.y=.75;box(.95,.35,.09,'#d6c8a2',sign).position.set(.35,1.35,0);
 const deck=box(3.3,.14,2.8,'#95866a');deck.position.set(land.summit.x,land.summit.y+.09,land.summit.z);for(let i=-6;i<=6;i++){const seam=box(.018,.012,2.8,'#6e6754');seam.position.set(land.summit.x+i*.24,land.summit.y+.165,land.summit.z);}for(const x of [land.summit.x-1.5,land.summit.x+1.5]){box(.1,1,.1,'#686b57').position.set(x,land.summit.y+.65,land.summit.z-1.3);}box(3.1,.09,.09,'#7b7c63').position.set(land.summit.x,land.summit.y+1.15,land.summit.z-1.3);
}
const car=new T.Group(),carDoor=new T.Group();let vehicleRig,walker;const routeGuides=new T.Group;car.add(carDoor);car.rotation.order='YXZ';world.add(car);
function vehicle(){carDoor.position.set(.87,.77,.64);mesh(roundedBox(.06,.43,.85,.02),material('#a6b29e',.46),carDoor).position.set(0,.01,-.42);box(.035,.38,.83,'#344b50',carDoor).position.set(0,.47,-.42);box(.05,.035,.16,'#34443a',carDoor).position.set(.04,.14,-.65);mesh(roundedBox(1.65,.5,3.25,.09),material('#a6b29e',.46),car).position.y=.72;mesh(roundedBox(1.45,.65,1.8,.11),material('#b7c1ac',.45),car).position.set(0,1.28,-.27);box(1.33,.42,.035,'#344b50',car).position.set(0,1.35,.65);box(1.33,.4,.035,'#344b50',car).position.set(0,1.35,-1.19);for(const sign of [-1,1]){box(.035,.4,1.55,'#344b50',car).position.set(sign*.735,1.35,-.27);box(.065,.065,2.1,'#3a443d',car).position.set(sign*.57,1.68,-.24);box(.34,.16,.04,'#fff2c6',car).position.set(sign*.52,.8,1.65);box(.24,.13,.04,'#ad5945',car).position.set(sign*.57,.84,-1.65);}box(1.6,.16,.14,'#414a40',car).position.set(0,.53,1.7);box(1.65,.13,.18,'#414a40',car).position.set(0,.53,-1.7);mesh(roundedBox(.72,.25,1.3,.07),material('#776a4b'),car).position.set(0,1.83,-.25);}
const look=new T.Vector3(),desired=new T.Vector3();
function placeActors(j){const motion=actorAt(land,j,lightAt(j,lightMode)),d=vehicleRig.update(motion,lightAt(j,lightMode));carDoor.rotation.y=j.chapter.id==='camp'?-1.05*smooth(j.local/.035)*(1-smooth((j.local-.09)/.06)):0;walker.update(motion,lightAt(j,lightMode));return{d,p:motion.p,f:V(Math.sin(d.heading),0,Math.cos(d.heading)),motion};}
function setCamera(j,a,snap=false){if(cameraMode==='free')return;const targetFov=54;if(Math.abs(camera.fov-targetFov)>.01){camera.fov=snap?targetFov:camera.fov+(targetFov-camera.fov)*Math.min(1,frameDt*4);camera.updateProjectionMatrix();}const blend=snap?1:1-Math.exp(-frameDt*3.8);if(cameraMode==='overview'){desired.set(70,65,85);look.set(0,5,0);}else if(cameraMode==='layout'){desired.set(34,53,58);look.set(-2,3,0);}else if(j.chapter.id==='drive'){desired.set(a.d.x-a.f.x*6.8+.7,a.d.y+3.6,a.d.z-a.f.z*6.8);look.set(a.d.x+a.f.x*2,a.d.y+1,a.d.z+a.f.z*2);}else if(j.chapter.id==='camp'){const opening=1-smooth(j.local/.28);desired.set(land.camp.x+4.2-opening*9.8,land.camp.y+4.5+opening,land.camp.z+4.7-opening*1.7);look.set((land.camp.x+.5)*(1-opening)+a.p.x*opening,land.camp.y+.9,(land.camp.z-.7)*(1-opening)+a.p.z*opening);}else if(j.chapter.id==='hike'){const f=V(Math.sin(a.p.heading),0,Math.cos(a.p.heading));desired.set(a.p.x-f.x*3.9+.7,a.p.y+2.6,a.p.z-f.z*3.9);look.set(a.p.x+f.x*1.5,a.p.y+1.1,a.p.z+f.z*1.5);}else{const dir=solarDirection(lightAt(j,lightMode)),forward=V(dir.x,0,dir.z).normalize(),right=V(forward.z,0,-forward.x),eye=V(a.p.x,a.p.y+1.78,a.p.z);if(cameraMode==='eyes'){const elevation=Math.atan(lightAt(j,lightMode).elevation)*a.motion.viewTurn,gaze=V(Math.sin(a.p.heading)*Math.cos(elevation),Math.sin(elevation),Math.cos(a.p.heading)*Math.cos(elevation));desired.copy(eye).addScaledVector(gaze,.28);look.copy(eye).addScaledVector(gaze,80);}else{desired.copy(eye).addScaledVector(forward,-4.7).addScaledVector(right,1.3);desired.y+=.77;look.copy(eye).addScaledVector(forward,22);look.y+=2.0;}}desired.y=Math.max(desired.y,forestHeight(land,desired.x,desired.z)+1);camera.position.lerp(desired,blend);camera.position.y=Math.max(camera.position.y,forestHeight(land,camera.position.x,camera.position.z)+.85);controls.target.lerp(look,blend);}
function lighting(j){const l=lightAt(j,lightMode),b=l.brightness,dir=solarDirection(l),warm=1-smooth((l.elevation-.10)/.35);skyMaterial.uniforms.top.value.set('#25364b').lerp(new T.Color('#83a9bc'),b);skyMaterial.uniforms.horizon.value.set('#343f52').lerp(new T.Color(warm>.5?'#eecb9b':'#c6d8e0'),smooth(b*1.8));const dawnStrength=l.dawnMix;skyMaterial.uniforms.dawn.value=dawnStrength;skyMaterial.uniforms.sunDirection.value.set(dir.x,dir.y,dir.z);if(dawnStrength>0){const rise=l.dawnPhase;skyMaterial.uniforms.top.value.set('#243652').lerp(new T.Color('#6b98b5'),rise);skyMaterial.uniforms.horizon.value.set('#a84e3b').lerp(new T.Color('#ffca88'),rise);}skyMaterial.uniforms.low.value.set('#8c998f');scene.fog.color.copy(skyMaterial.uniforms.horizon.value).lerp(new T.Color('#a0b8bb'),.3);
 const focus=V(0,8,0),direction=V(dir.x,dir.y,dir.z);sun.target.position.copy(focus);sun.position.copy(focus).addScaledVector(direction,320);sun.color.set('#fff3dd').lerp(new T.Color('#ffbf82'),warm);sun.intensity=(.6+b*2.5)*smooth(l.elevation/.055);sun.castShadow=l.elevation>0;ambient.intensity=.55+b*1.35;ambient.color.set('#7184a0').lerp(new T.Color('#c1d9e5'),smooth(b));ambient.groundColor.set('#424a48').lerp(new T.Color('#96957d'),b);scene.fog.near=55+b*25;scene.fog.far=180+b*55;scene.fog.color.multiplyScalar(.40+b*.60);
 sunDisc.position.copy(camera.position).addScaledVector(direction,220);sunDisc.visible=glow.visible=l.elevation>0;sunDisc.material.color.set('#fff7c4').lerp(new T.Color('#ffb44c'),warm*.5).multiplyScalar(2.2);glow.position.copy(sunDisc.position);glow.quaternion.copy(camera.quaternion);
 for(const lamp of lamps)lamp.intensity=Math.max(0,(.7-b)/.7)*7;for(const m of lampMaterials)m.emissiveIntensity=.1+(1-b)*2.5;
}
function mapRoute(j){const ctx=$('route-map').getContext('2d'),to=p=>[10+(p.x+29)*2.15,8+(p.z+24)*1.65];ctx.clearRect(0,0,140,100);for(const [route,color] of [[land.drive,'#e5b26e'],[land.arrival,'#bec9ad'],[land.departure,'#bec9ad'],[land.trail,'#8ed5ce']]){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<=80;i++){const [x,y]=to(route.sample(i/80));i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}const a=actorAt(land,j,lightAt(j,lightMode)),p=j.chapter.id==='drive'?land.drive.sample(a.driveProgress):a.p,[x,y]=to(p);ctx.fillStyle='#fff7c9';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();ctx.font='9px sans-serif';ctx.fillStyle='#edf0db';for(const [label,point] of [['P',land.drive.sample(1)],['营地',land.camp],['山顶',land.summit]]){const [x,z]=to(point);ctx.fillText(label,x+3,z-4);}ctx.fillStyle='#e5b26e';ctx.fillText('车道',10,95);ctx.fillStyle='#8ed5ce';ctx.fillText('步道 ↑'+land.recipe.ascent+'m',60,95);}
function layoutGuides(){for(const [route,color] of [[land.drive,'#ffbd61'],[land.trail,'#72ddd5']]){const points=[];for(let i=0;i<=300;i++){const p=route.sample(i/300);points.push(V(p.x,p.y+.09,p.z));}routeGuides.add(new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color,depthTest:false,toneMapped:false})));}for(const [text,point] of [['山脚停车',land.drive.sample(1)],['林间营地',land.camp],['日出山脊 · +'+land.recipe.ascent+'m',land.summit]]){const canvas=document.createElement('canvas');canvas.width=384;canvas.height=80;const ctx=canvas.getContext('2d');ctx.fillStyle='#233c32e8';ctx.fillRect(0,0,384,80);ctx.font='bold '+(text.length>6?40:60)+'px Microsoft YaHei';ctx.textAlign='center';ctx.fillStyle='#fff1ce';ctx.fillText(text,192,53);const label=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(canvas),depthTest:false,toneMapped:false,sizeAttenuation:false}));label.scale.set(.21,.044,1);label.position.set(point.x+(text==='山脚停车'?-6:text==='林间营地'?6:0),point.y+3,point.z);label.renderOrder=20;routeGuides.add(label);}world.add(routeGuides);}
function ui(j){routeGuides.visible=cameraMode==='layout';$('route-map').style.visibility=cameraMode==='layout'||j.chapter.id==='sunrise'?'hidden':'visible';$('sunrise-controls').hidden=j.chapter.id!=='sunrise';const motion=actorAt(land,j,lightAt(j,lightMode));$('action-label').textContent=lightMode==='auto'?motion.action:({day:'正午光照 · 观察短树影',dusk:'傍晚光照 · 观察长树影',dawn:'清晨光照 · 观察长树影'}[lightMode]);$('night-transition').style.opacity=motion.nightFade;$('night-transition').setAttribute('aria-hidden',String(motion.nightFade<.5));mapRoute(j);for(const b of document.querySelectorAll('[data-chapter]'))b.setAttribute('aria-pressed',String(b.dataset.chapter===j.chapter.id));const clockLight=lightAt(j,lightMode);$('stage-tag').textContent='演示时间 · 第'+clockLight.day+'天 '+clockLight.clock;$('shadow-note').textContent=clockLight.elevation>0?'树影背向太阳；太阳越低，影子越长。':'太阳尚在地平线下；当前没有太阳树影。';$('stage-title').textContent=$('chapter-title').textContent=j.chapter.title;$('chapter-description').textContent=j.chapter.description;$('reuse-explanation').textContent=j.chapter.reuse;$('stage-weather').textContent=j.chapter.id==='drive'?'林间车道 · 3.2 m':j.chapter.id==='camp'?'营地空地 · 车行分离':j.chapter.id==='hike'?'登山步道 · 0.95 m':'山脊观景点 · 晨光';$('stage-play').textContent=playing?'Ⅱ 暂停':j.chapter.id==='sunrise'?(progress>=1?'↻ 重看日出':'▶ 播放日出'):'▶ 播放行程';for(const b of document.querySelectorAll('[data-sunphase]'))b.setAttribute('aria-pressed',String(Math.abs(progress-Number(b.dataset.sunphase))<.009));$('progress').value=$('stage-progress').value=progress*100;$('progress-out').textContent=Math.round(progress*100)+'%';$('play').textContent=playing?'Ⅱ 暂停行程':progress>=1?'↻ 再播放一遍':progress>0?'▶ 继续行程':'▶ 播放完整行程';$('camera-caption').textContent={follow:j.chapter.id==='sunrise'?'人物后侧 · 人物与日出同框':'跟随行程 · 可切换自由观察',eyes:'人物视角 · 面向当前太阳方向',free:'自由观察 · 拖动旋转，滚轮缩放',overview:'山谷全景 · 连续松林覆盖周围山坡',layout:'动线总览 · 金色车道，青色登山步道'}[cameraMode];for(const b of document.querySelectorAll('[data-camera]'))b.setAttribute('aria-pressed',String(b.dataset.camera===cameraMode));$('light').value=lightMode;if(j.chapter.id!==previousChapter){$('status').textContent=j.chapter.id==='drive'?'车辆沿指定土路行驶，到营地入口后停止。':j.chapter.id==='camp'?'已到营地：车辆停在入口，营位独立放置；下一段行程跳到第二天清晨。':j.chapter.id==='hike'?'第二天清晨：步行上山，车辆保持停放；这是压缩的路线演示。':'已到观景点：日出约 24 秒，可暂停或按三个阶段对比。';previousChapter=j.chapter.id;}}
function renderState(snap=false){const j=journeyAt(progress),a=placeActors(j);setCamera(j,a,snap);lighting(j);ui(j);return j;}
function state(){return{groundCover,layout:editor?.state(),recipe:land.recipe,geometryMemory:renderer?.info.memory,ready:ready&&!renderError,renderError,progress,playing,camera:cameraMode,light:lightMode,chapter:journeyAt(progress).chapter.id,action:actorAt(land,journeyAt(progress)).action,nightFade:actorAt(land,journeyAt(progress)).nightFade,trees:valleyForest?.trees.length??land.trees.length,forest:forestRenderer?.stats(),forestExtent:224,measuredFps:performanceSample.fps,driveLength:land.drive.length,trailLength:land.trail.length,car:{x:car.position.x,y:car.position.y,z:car.position.z},summit:land.summit,camp:land.camp,ascent:land.summit.y-land.camp.y,solarDirection:solarDirection(lightAt(journeyAt(progress),lightMode)),time:lightAt(journeyAt(progress),lightMode),shadow:shadowAt(lightAt(journeyAt(progress),lightMode)),sunShadowMapSize:sun.shadow.mapSize.x,sunShadowActive:sun.castShadow,hiker:{heading:walker.root.rotation.y,forward:{x:Math.sin(walker.root.rotation.y),z:Math.cos(walker.root.rotation.y)},visible:walker.root.visible,x:walker.root.position.x,y:walker.root.position.y,z:walker.root.position.z},sunVisible:sunDisc.visible,sunScreen:sunDisc.position.clone().project(camera).toArray(),viewPosition:camera.position.toArray(),viewTarget:controls.target.toArray(),triangles:renderer?.info.render.triangles};}
function configure(p){if(!ready)throw Error('场景正在更新，请稍候');if(p.chapter!==undefined){const c=chapters.find(c=>c.id===p.chapter);if(!c)throw Error('未知章节');progress=c.focus;playing=false;if(p.light===undefined)lightMode='auto';}if(p.progress!==undefined){if(!Number.isFinite(p.progress)||p.progress<0||p.progress>1)throw Error('进度需在 0～1');progress=p.progress;playing=false;}if(p.camera!==undefined){if(!['follow','free','overview','layout','eyes'].includes(p.camera))throw Error('未知视角');cameraMode=p.camera;}if(p.light!==undefined){lightAt(journeyAt(progress),p.light);lightMode=p.light;}if(p.playing!==undefined){if(typeof p.playing!=='boolean')throw Error('播放开关无效');if(p.playing&&progress>=1)progress=journeyAt(progress).chapter.id==='sunrise'?.88:0;playing=p.playing;}if(cameraMode==='eyes'&&journeyAt(progress).chapter.id!=='sunrise')cameraMode='follow';renderState(p.progress!==undefined||p.chapter!==undefined||p.camera!==undefined);forestRenderer?.update(camera,true);return state();}
document.addEventListener('click',e=>{if(!ready)return;const b=e.target.closest('button');if(!b)return;if(b.dataset.inspect){const scenes={path:{progress:.735,camera:'follow',light:'day',playing:false},steps:{progress:.65,camera:'follow',light:'day',playing:true},light:{progress:.97,camera:'follow',light:'auto',playing:false}};configure(scenes[b.dataset.inspect]);$('stage').scrollIntoView({behavior:'smooth',block:'center'});}if(b.dataset.chapter)configure({chapter:b.dataset.chapter,camera:'follow',playing:b.dataset.chapter==='sunrise'});if(b.dataset.sunphase)configure({chapter:'sunrise',camera:'follow',progress:Number(b.dataset.sunphase),light:'auto',playing:false});if(b.dataset.camera)configure({camera:b.dataset.camera});if(b.id==='play'||b.id==='stage-play')configure({playing:!playing});if(b.id==='restart')configure({progress:0,camera:'follow',light:'auto'});});for(const id of ['progress','stage-progress'])$(id).addEventListener('input',e=>{if(ready)configure({progress:Number(e.target.value)/100});});$('light').addEventListener('change',e=>{if(ready)configure({light:e.target.value});});
async function register(){const c=document.modelContext;if(!c?.registerTool)return;const result=()=>({content:[{type:'text',text:JSON.stringify(state())}]});await c.registerTool({name:'read_outdoor_demo',description:'Read the outdoor journey stage, playback, camera, route lengths and actor positions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:result},{signal:abort.signal});await c.registerTool({name:'configure_outdoor_demo',description:'Operate the visible camping journey controls: select chapter, seek progress, play or pause, change camera or lighting.',inputSchema:{type:'object',properties:{chapter:{type:'string',enum:chapters.map(c=>c.id)},progress:{type:'number',minimum:0,maximum:1},playing:{type:'boolean'},camera:{type:'string',enum:['follow','free','overview','layout','eyes']},light:{type:'string',enum:['auto','day','dusk','dawn']}},additionalProperties:false},execute:p=>{configure(p);return result();}},{signal:abort.signal});await c.registerTool({name:'configure_outdoor_layout',description:'Use the visible layout workbench: preview or apply bounded campsite, summit, ascent and road settings; select a template, save the current scene locally, restore its local save or reset the original layout.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['preview','apply','preset','save','restore','reset']},preset:{type:'string',enum:['original','ridge','valley']},recipe:{type:'object',properties:{campX:{type:'number',minimum:4,maximum:10},campZ:{type:'number',minimum:8,maximum:12},summitX:{type:'number',minimum:12,maximum:20},summitZ:{type:'number',minimum:-22,maximum:-16},ascent:{type:'number',minimum:8,maximum:14},roadBend:{type:'number',minimum:-3,maximum:3},environment:{type:'string',enum:Object.keys(environments)}},additionalProperties:false}},required:['action'],additionalProperties:false},execute:async p=>{await editor.operate(p);return result();}},{signal:abort.signal});}
function releaseOutdoor(){
 // Shared source assets survive regeneration; generated geometry, maps and lamp shadows do not.
 const protectedGeometry=new Set(pineLibrary.variants.flatMap(v=>[v.wood,v.needles])),protectedMaterials=new Set([pineLibrary.bark,pineLibrary.leaf,pineLibrary.depth]);
 const protectedTextures=new Set(Object.values(maps).flatMap(v=>Object.values(v)));for(const m of protectedMaterials)for(const value of Object.values(m))if(value?.isTexture)protectedTextures.add(value);
 const geometries=new Set,materials=new Set,textures=new Set;
 for(const root of [world,vegetation])root.traverse(o=>{if(o.isInstancedMesh)o.dispose();o.shadow?.map?.dispose();if(o.geometry&&!protectedGeometry.has(o.geometry))geometries.add(o.geometry);for(const m of [o.material,o.customDepthMaterial].flat().filter(Boolean))if(!protectedMaterials.has(m)){materials.add(m);for(const value of Object.values(m))if(value?.isTexture&&!protectedTextures.has(value))textures.add(value);}});
 geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());forestRenderer?.dispose();forestRenderer=null;
 world.clear();vegetation.clear();car.clear();carDoor.clear();routeGuides.clear();car.add(carDoor);world.add(car);lamps.length=lampMaterials.length=0;
}
function buildOutdoor(){
 valleyForest=expandForest(land);terrain();$('environment-current').textContent=environments[land.recipe.environment].name+' · 草丛 '+groundCover.grassClumps.toLocaleString()+' / 灌木 '+groundCover.shrubs+' / 岩石 '+groundCover.rocks;forestRenderer=createForest(renderer,vegetation,pineLibrary,valleyForest);camp();addCampDetails(world,land);addRouteDetails(world,land);vehicle();vehicleRig=addVehicleRig(car,land);walker=createWalker(world,land);layoutGuides();
 $('road-length').textContent=land.drive.length.toFixed(0)+' m';$('trail-length').textContent=land.trail.length.toFixed(0)+' m';$('tree-count').textContent=valleyForest.trees.length.toLocaleString()+' 棵';$('forest-count').textContent=valleyForest.trees.length.toLocaleString();$('layout-summary').textContent='车道止于营地入口；独立步道爬升 '+land.recipe.ascent+' m 到日出山脊。';
}
async function applyOutdoor(recipe){
 if(!ready)throw Error('场景正在更新，请稍候');const next=makeOutdoor(recipe),report=inspectOutdoorLayout(next);if(!report.valid)throw Error(report.errors.join('；'));
 const old=land;ready=false;playing=false;$('loading').hidden=false;$('loading').textContent='正在更新山坡、路线、营位和树林…';
 await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
 try{releaseOutdoor();land=next;buildOutdoor();}catch(error){releaseOutdoor();land=old;buildOutdoor();throw error;}finally{ready=true;$('loading').hidden=true;progress=.47;cameraMode='layout';lightMode='day';previousChapter='';renderState(true);controls.update();forestRenderer.update(camera,true);}
 return{...report,trees:valleyForest.trees.length};
}
function frame(now){if(disposed)return;const dt=Math.min((now-last)/1000||0,.05);last=now;frameDt=dt||1/60;if(ready&&!document.hidden){if(playing){progress=clamp(progress+dt/(progress>=.88?200:90));if(progress>=1)playing=false;}const j=journeyAt(progress),a=placeActors(j);setCamera(j,a);lighting(j);if(frameCount++%6===0)ui(j);controls.update();if(Math.max(Math.abs(camera.position.x),Math.abs(camera.position.z))<119)camera.position.y=Math.max(camera.position.y,forestHeight(land,camera.position.x,camera.position.z)+.85);sky.position.copy(camera.position);forestRenderer.update(camera);renderer.render(scene,camera);performanceSample.frames++;performanceSample.elapsed+=Math.max((now-performanceSample.lastTime)/1000||dt,.001);performanceSample.lastTime=now;if(performanceSample.elapsed>=2){performanceSample.fps=Math.round(performanceSample.frames/performanceSample.elapsed);performanceSample.frames=0;performanceSample.elapsed=0;}}requestAnimationFrame(frame);}
try{renderer=new T.WebGLRenderer({canvas:$('outdoor-canvas'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));sun.shadow.mapSize.setScalar(Math.min(4096,renderer.capabilities.maxTextureSize));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.debug.onShaderError=(gl,program,vertex,fragment)=>{console.error('Outdoor shader',gl.getShaderInfoLog(vertex),gl.getShaderInfoLog(fragment));renderError='着色器编译失败';$('status').textContent='画面未能正常渲染，请刷新重试。';};camera=new T.PerspectiveCamera(54,1,.08,650);controls=new OrbitControls(camera,$('outdoor-canvas'));controls.enableDamping=true;controls.minDistance=1;controls.maxDistance=190;controls.maxPolarAngle=Math.PI*.92;controls.addEventListener('start',()=>{cameraMode='free';ui(journeyAt(progress));});const loader=new T.TextureLoader;await Promise.all(['brown_mud_dry','aerial_grass_rock','rock_2'].flatMap(id=>['diff','nor_gl','rough'].map(async c=>{const t=await loader.loadAsync(`../assets/textures/${id}_${c}_1k.jpg`);t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(c==='diff')t.colorSpace=T.SRGBColorSpace;(maps[id]??={})[c]=t;})));pineLibrary=await loadPines(loader);buildOutdoor();editor=mountOutdoorEditor({getLand:()=>land,getTrees:()=>valleyForest.trees.length,apply:applyOutdoor});function resize(){const el=$('stage');renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe($('stage'));resize();ready=true;renderState(true);controls.update();$('loading').hidden=true;requestAnimationFrame(frame);try{await register();}catch(e){console.warn('Optional page controls unavailable',e);}window.addEventListener('pagehide',()=>{disposed=true;abort.abort();observer.disconnect();controls.dispose();forestRenderer?.dispose();renderer.dispose();},{once:true});}catch(e){$('loading').textContent='场景加载失败，请确认本地素材完整并刷新。';console.error(e);}
