import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {loadPines,blendGround} from './nature-render.mjs';
import {createForest} from './forest-render.mjs';
import {tentFabric,roundedBox} from './outdoor-details.mjs';
import {createWalker,addVehicleRig} from './outdoor-actors.mjs';
import {site,plans,measure,decision,requirements,record,restoreRecord,routeTo,lengthOf,pointOnRoute,terrainHeight,fixedTrees} from './camp-plan-core.mjs';
const $=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),key='songlan-camp-review-v1';
let planId='B',brief={groups:4,gap:4},pitchId='west-back',hour=15,view='overview',walking=false,progress=0,ready=false,error=null,renderer,camera,controls,forest,walker,routeLine,last=0,stopped=false;
const scene=new T.Scene,world=new T.Group,proposal=new T.Group,labels=new T.Group,trees=fixedTrees(),maps={},abort=new AbortController;scene.add(world,proposal,labels);scene.background=new T.Color('#b9c7c2');scene.fog=new T.Fog('#b9c7c2',70,155);
const sun=new T.DirectionalLight('#ffe0b3',3),ambient=new T.HemisphereLight('#c2dbe6','#78694e',1.8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:160});sun.shadow.normalBias=.025;sun.shadow.bias=-.00008;scene.add(sun,sun.target,ambient);
function mesh(parent,g,color){const m=new T.Mesh(g,new T.MeshStandardMaterial({color,roughness:.9}));m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
function box(parent,w,h,d,color,x,y,z){const m=mesh(parent,roundedBox(w,h,d,Math.min(.04,h/4)),color);m.position.set(x,y,z);return m;}
function label(parent,text,x,y,z,color='#2c4737',width=3.5){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const c=canvas.getContext('2d');c.fillStyle=color;c.beginPath();c.roundRect(4,4,504,88,14);c.fill();c.font='500 32px "Microsoft YaHei", sans-serif';c.fillStyle='#fff5df';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,48);const map=new T.CanvasTexture(canvas);map.colorSpace=T.SRGBColorSpace;const s=new T.Sprite(new T.SpriteMaterial({map,depthTest:true,transparent:true}));s.position.set(x,y,z);s.scale.set(width,width*96/512,1);parent.add(s);return s;}
function disposeGroup(group){const gs=new Set,ms=new Set,ts=new Set;group.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of [o.material].flat().filter(Boolean)){ms.add(m);if(m.map&&!Object.values(maps).flatMap(Object.values).includes(m.map))ts.add(m.map);}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());group.clear();}
function line(parent,points,color='#d8b55b',dashed=false){const geometry=new T.BufferGeometry().setFromPoints(points.map(p=>V(p[0],p[1],p[2]))),m=dashed?new T.LineDashedMaterial({color,dashSize:.24,gapSize:.15}):new T.LineBasicMaterial({color});const o=new T.Line(geometry,m);if(dashed)o.computeLineDistances();parent.add(o);return o;}
function strip(parent,a,b,width=.95){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);const g=new T.PlaneGeometry(width,len);g.rotateX(-Math.PI/2);const material=new T.MeshStandardMaterial({map:maps.brown_mud_dry.diff,color:'#b4a080',roughness:1,polygonOffset:true,polygonOffsetFactor:-1});const m=new T.Mesh(g,material);m.position.set((a[0]+b[0])/2,.026,(a[1]+b[1])/2);m.rotation.y=Math.atan2(dx,dz);m.receiveShadow=true;parent.add(m);}
function createGround(){const g=new T.PlaneGeometry(160,160,160,160);g.rotateX(-Math.PI/2);const p=g.attributes.position,uv=g.attributes.uv,dist=[];for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,terrainHeight(x,z));uv.setXY(i,x,z);dist.push(Math.min(Math.hypot(x+24,Math.max(0,11-z)),Math.hypot(Math.max(-24-x,x+16,0),z-16)));}g.setAttribute('roadDistance',new T.Float32BufferAttribute(dist,1));g.computeVertexNormals();const mat=new T.MeshStandardMaterial({map:maps.aerial_grass_rock.diff,normalMap:maps.aerial_grass_rock.nor_gl,roughnessMap:maps.aerial_grass_rock.rough,color:'#c8c6a6',roughness:1,normalScale:new T.Vector2(.7,.7)});blendGround(mat,maps.brown_mud_dry.diff,maps.brown_mud_dry.nor_gl,3.8,{tint:'#b7a086',roughness:1});const ground=new T.Mesh(g,mat);ground.receiveShadow=true;world.add(ground);
 // Low grass outside the reserved clearing; seed and positions never depend on proposal.
 const blades=[],normals=[];let seed=13;const r=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);for(let i=0;i<15000;i++){const x=(r()-.5)*105,z=(r()-.5)*105;if(Math.abs(x)<16&&z>-14&&z<22||Math.abs(x+24)<2.7&&z>10)continue;const y=terrainHeight(x,z),h=.10+r()*.26,w=.018;blades.push(x-w,y,z,x+w,y,z,x+.04,y+h,z+.01);normals.push(0,1,0,0,1,0,0,1,0);}const grass=new T.BufferGeometry;grass.setAttribute('position',new T.Float32BufferAttribute(blades,3));grass.setAttribute('normal',new T.Float32BufferAttribute(normals,3));const tufts=new T.Mesh(grass,new T.MeshStandardMaterial({color:'#7e8656',roughness:1,side:T.DoubleSide}));tufts.receiveShadow=true;world.add(tufts);
}
function fixedFacilities(){const pad=new T.PlaneGeometry(8,12,8,12);pad.rotateX(-Math.PI/2);const pos=pad.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i)-20,z=pos.getZ(i)+16;pos.setXYZ(i,x,terrainHeight(x,z)+.035,z);}pad.computeVertexNormals();const parking=new T.Mesh(pad,new T.MeshStandardMaterial({map:maps.brown_mud_dry.diff,color:'#a7987d',roughness:1}));parking.receiveShadow=true;world.add(parking);strip(world,site.parking,site.hub,1.3);const publicGroup=new T.Group;publicGroup.position.set(6,0,16);world.add(publicGroup);box(publicGroup,3.4,.10,2.3,'#95856a',0,.08,0);box(publicGroup,2,.12,1,'#a19476',0,.8,0);for(const x of [-.75,.75])for(const z of [-.35,.35])box(publicGroup,.09,.76,.09,'#625f4e',x,.4,z);for(const z of [-.9,.9]){box(publicGroup,2.1,.1,.38,'#8d856a',0,.46,z);for(const x of [-.8,.8])box(publicGroup,.08,.43,.09,'#625f4e',x,.23,z);}label(labels,'固定 · 共享公区',6,2.1,16);
 for(const z of [13,19]){const car=new T.Group;car.position.set(-19,terrainHeight(-19,z),z);world.add(car);box(car,1.65,.5,3.35,'#738078',0,.65,0);box(car,1.45,.67,1.8,'#566b60',0,1.16,-.15);box(car,1.29,.43,1.82,'#a0bbc0',0,1.17,-.14);box(car,1.50,.10,1.96,'#738078',0,1.53,-.15);const route={length:0,sample:()=>({x:-19,z,heading:0})},rig=addVehicleRig(car,{drive:route,terrain:terrainHeight});rig.update({driveProgress:1},{brightness:1});}
 label(labels,'固定 · 停车区',-19,3.1,19,undefined,4.4);label(labels,'车辆止步 · 由此步行',-12,.9,16,undefined,4.4);for(const z of [14.7,17.3])box(world,.12,.75,.12,'#8f8064',-14,.375,z);
 const boundary=[[-15,.04,21],[15,.04,21],[15,.04,-13],[-15,.04,-13],[-15,.04,21]];line(world,boundary,'#b9b793',true);
}
function selectedPitch(){return plans[planId].pitches.find(p=>p.id===pitchId)??plans[planId].pitches.at(-1);}
function pitchName(p){return(p.x<0?'西':'东')+(p.z===6?'前':p.z===-1?'中':'后')+'营位';}
function makeProposal(){disposeGroup(proposal);const ps=plans[planId].pitches,levels=[...new Set(ps.map(p=>p.z+2.4))];strip(proposal,site.hub,[0,Math.min(...levels)],1.1);for(const z of levels)strip(proposal,[-9,z],[9,z]);for(const p of ps){const g=new T.Group;g.position.set(p.x,0,p.z);proposal.add(g);const footprint=new T.Mesh(new T.PlaneGeometry(5.8,5.8),new T.MeshStandardMaterial({map:maps.brown_mud_dry.diff,color:'#afa78c',transparent:true,opacity:.42,depthWrite:false,roughness:1}));footprint.rotation.x=-Math.PI/2;footprint.position.y=.012;footprint.receiveShadow=true;g.add(footprint);tentFabric(g,p.existing?'#bb9468':'#677e58');line(g,[[-3,.045,-3],[3,.045,-3],[3,.045,3],[-3,.045,3],[-3,.045,-3]],p.existing?'#d1c5a4':'#9eb886',true);label(g,(p.existing?'既有 · ':'新增 · ')+pitchName(p),0,2.3,0,p.existing?'#80674d':'#3f6244',4.0);}
 const neighbor=planId==='A'?-1:-8,start=neighbor+2.2,end=6-2.2,gap=measure(plans[planId],brief).gap;line(proposal,[[-12.7,.13,start],[-12.7,.13,end]],'#f2d688',true);for(const z of [start,end])line(proposal,[[-13.1,.13,z],[-12.3,.13,z]],'#f2d688');label(proposal,`最近边界 ${gap.toFixed(1)} m`,-12.7,1.2,(start+end)/2,'#8a693f',4.1);
 $('pitch-select').replaceChildren(...ps.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=pitchName(p)+(p.existing?' · 既有':' · 新增');return o;}));pitchId=selectedPitch().id;$('pitch-select').value=pitchId;resetWalk();
}
function resetWalk(){walking=false;progress=0;$('walk-play').textContent='播放搬运行李路线';if(routeLine){world.remove(routeLine);routeLine.geometry.dispose();routeLine.material.dispose();}const points=routeTo(selectedPitch());routeLine=line(world,points.map(p=>[p[0],.09,p[1]]));updateWalker();$('walk-status').textContent=`停车区 → 公区入口 → ${pitchName(selectedPitch())}：${lengthOf(points).toFixed(1)} m。黄色线为实际播放路径。`;}
function updateWalker(){if(!walker)return;const points=routeTo(selectedPitch()),length=lengthOf(points),p=pointOnRoute(points,progress);if(progress>=1)p.heading=Math.PI;walker.update({p,visible:true,walking,poles:false,watching:progress>=1,routeDistance:progress*length,route:{length,sample:t=>pointOnRoute(points,t)}});}
function setView(next){view=next;const p=selectedPitch();const views={overview:[[30,32,37],[-3,0,4]],top:[[0, 60,3],[0,0,2.9]],arrival:[[-29,9,29],[-7,1,12]],pitch:[[p.x+2.7,1.7,p.z+2.8],[p.x,1.3,p.z-9]]};const [eye,target]=views[next];camera.position.set(...eye);controls.target.set(...target);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));}
function lighting(){const az=(hour-12)*.18,elevation=Math.max(.16,1.20-Math.abs(hour-12)*.18),d=V(Math.sin(az)*Math.cos(elevation),Math.sin(elevation),-Math.cos(az)*Math.cos(elevation));sun.position.copy(d.multiplyScalar(80));sun.color.set(hour>=16?'#ffd2a0':'#ffe3bb');sun.intensity=hour>=16?2.5:3;ambient.intensity=hour>=16?1.5:1.8;$('sun-label').textContent=`${hour}:00 · 示意日照`;$('hour-output').textContent=`${hour}:00`;}
function sync(){const a=measure(plans.A,brief),b=measure(plans.B,brief),m=planId==='A'?a:b,d=decision(brief);$('groups-output').textContent=brief.groups+' 组';$('gap-output').textContent=brief.gap+' m';$('groups').value=brief.groups;$('gap').value=brief.gap;document.querySelectorAll('[data-plan]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.plan===planId)));$('scene-name').textContent=planId+' · '+plans[planId].name;
 $('requirements-result').innerHTML=`<div class="requirement" data-pass="${m.capacityPass}"><span>当前 ${m.capacity} 营位 / 需要 ${brief.groups}</span><strong>${m.capacityPass?'数量满足':'数量不足'}</strong></div><div class="requirement" data-pass="${m.gapPass}"><span>最近 ${m.gap.toFixed(1)} m / 目标 ${brief.gap} m</span><strong>${m.gapPass?'间距满足':'间距不足'}</strong></div>`;
 $('decision').dataset.pass=String(d.plan!==null);$('decision').replaceChildren();const strong=document.createElement('strong');strong.textContent=d.plan?'本次优先讨论方案 '+d.plan:'两案均需调整';$('decision').append(strong,document.createTextNode(d.text));
 const rows=[['同时接待上限',`${a.capacity} 组`,`${b.capacity} 组`,'每组占一个营位'],['新增营位',`${a.added} 个`,`${b.added} 个`,'在固定的 2 个既有营位上扩建'],['最近帐篷边界间距',`${a.gap.toFixed(1)} m`,`${b.gap.toFixed(1)} m`,'含拉绳；只衡量空间分隔'],['新增营位预留面积',`${a.newPitchArea} m²`,`${b.newPitchArea} m²`,'预留土地的多少，未推算成本'],['步道中心线总长',`${a.pathLength.toFixed(1)} m`,`${b.pathLength.toFixed(1)} m`,'去重计量；包括既有入口通道'],['停车到营位 · 平均',`${a.walkMean.toFixed(1)} m`,`${b.walkMean.toFixed(1)} m`,'此布局两案均值相同，不夸大收益'],['停车到营位 · 最远',`${a.walkMax.toFixed(1)} m`,`${b.walkMax.toFixed(1)} m`,'体验西后 / 东后营位核对']];$('comparison-body').innerHTML=rows.map(r=>`<tr><th scope="row">${r[0]}</th><td class="${planId==='A'?'active':''}">${r[1]}</td><td class="${planId==='B'?'active':''}">${r[2]}</td><td>${r[3]}</td></tr>`).join('');
}
function choose(id){if(!Object.hasOwn(plans,id))throw Error('未知方案');planId=id;makeProposal();sync();if(view==='pitch')setView(view);}
function capture(){return{...record(planId,brief,$('review-note').value),savedAt:new Date().toISOString(),observation:{hour,view,pitchId},source:'camp-planner-v1'};}
function save(){try{localStorage.setItem(key,JSON.stringify(capture()));$('save-status').textContent=`已保存方案 ${planId}、需求和备注。${measure(plans[planId],brief).pass?'':'当前方案未满足全部需求，记录中已保留这一结果。'}`;}catch{$('save-status').textContent='本机保存失败，请导出评审单留档。';}}
function restore(){try{const raw=localStorage.getItem(key);if(!raw)throw Error('本机还没有评审记录');const r=restoreRecord(raw);brief=r.brief;$('review-note').value=r.note;choose(r.planId);$('save-status').textContent='已恢复方案、需求与备注；计算结果已按当前模型重新核对。';}catch(e){$('save-status').textContent=e.message;}}
function download(){const r=capture(),a=measure(plans.A,brief),b=measure(plans.B,brief),d=decision(brief);const text=`# 松岚营地扩建评审\n\n时间：${r.savedAt}\n场地：${site.id} / 版本 ${site.version}（示例，非测绘）\n选择：${planId} · ${plans[planId].name}\n需求：${brief.groups} 组；帐篷边界间距至少 ${brief.gap} m\n当前方案满足全部需求：${r.metrics.pass?'是':'否'}\n\n| 比较项 | A | B |\n|---|---|---|\n| 营位 | ${a.capacity} | ${b.capacity} |\n| 最近间距 / m | ${a.gap.toFixed(1)} | ${b.gap.toFixed(1)} |\n| 新增预留面积 / m² | ${a.newPitchArea} | ${b.newPitchArea} |\n| 步道总长 / m | ${a.pathLength.toFixed(1)} | ${b.pathLength.toFixed(1)} |\n| 最远搬运 / m | ${a.walkMax.toFixed(1)} | ${b.walkMax.toFixed(1)} |\n\n规则建议：${d.text}\n\n## 选择理由与待确认问题\n${r.note||'尚未填写'}\n\n## 假设和边界\n${r.assumptions.map(s=>'- '+s).join('\n')}\n- 日照为时段示意，未输入地点和日期。\n\n## 结构化记录\n\x60\x60\x60json\n${JSON.stringify(r,null,2)}\n\x60\x60\x60\n`;const link=$('review-download');if(link.href.startsWith('blob:'))URL.revokeObjectURL(link.href);link.href=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));link.download=`songlan-review-${planId}.md`;$('review-document').value=text;$('review-output').hidden=false;$('review-output').scrollIntoView({behavior:'smooth',block:'start'});$('save-status').textContent='评审单已生成，见下方预览；可下载或选中文字复制。';}
function state(){return{ready,error,siteId:site.id,planId,brief,pitchId,hour,view,walking,progress,trees:trees.length,metrics:measure(plans[planId],brief),recommendation:decision(brief),route:routeTo(selectedPitch()),walker:pointOnRoute(routeTo(selectedPitch()),progress),geometry:renderer?.info.memory.geometries};}
async function register(){const c=document.modelContext;if(!c?.registerTool)return;const result=()=>({content:[{type:'text',text:JSON.stringify(state())}]});await c.registerTool({name:'read_camp_review',description:'Read the visible campsite proposal, requirements, measurements, route playback and loading status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:result},{signal:abort.signal});await c.registerTool({name:'configure_camp_review',description:'Operate the visible campsite review: switch proposal, set capacity and spacing requirements, inspect a viewpoint or tent, change illustrative hour, play the luggage route. Saving is separate.',inputSchema:{type:'object',properties:{plan:{type:'string',enum:['A','B']},groups:{type:'integer',minimum:2,maximum:6},gap:{type:'integer',minimum:2,maximum:8},view:{type:'string',enum:['overview','top','arrival','pitch']},pitch:{type:'string',enum:['west-front','east-front','west-middle','east-middle','west-back','east-back']},hour:{type:'integer',minimum:9,maximum:17},playing:{type:'boolean'}},additionalProperties:false},execute:p=>{if(p.groups!==undefined||p.gap!==undefined)brief=requirements({groups:p.groups??brief.groups,gap:p.gap??brief.gap});if(p.plan)choose(p.plan);if(p.pitch){if(!plans[planId].pitches.some(t=>t.id===p.pitch))throw Error('该方案不存在此营位');pitchId=p.pitch;$('pitch-select').value=pitchId;resetWalk();}if(p.hour!==undefined){hour=p.hour;$('hour').value=hour;lighting();}if(p.view)setView(p.view);if(p.playing!==undefined){walking=p.playing;if(walking&&progress>=1)progress=0;$('walk-play').textContent=walking?'暂停行走':'继续 / 重播路线';}sync();return result();}},{signal:abort.signal});}
document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>ready&&choose(b.dataset.plan));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>ready&&setView(b.dataset.view));for(const id of ['groups','gap'])$(id).oninput=()=>{brief=requirements({groups:Number($('groups').value),gap:Number($('gap').value)});sync();};$('hour').oninput=()=>{hour=Number($('hour').value);lighting();};$('pitch-select').onchange=()=>{pitchId=$('pitch-select').value;resetWalk();if(view==='pitch')setView(view);};$('walk-play').onclick=()=>{if(!ready)return;if(progress>=1)progress=0;walking=!walking;$('walk-play').textContent=walking?'暂停行走':'继续 / 重播路线';};$('save-review').onclick=save;$('restore-review').onclick=()=>ready&&restore();$('export-review').onclick=download;$('close-review').onclick=()=>{$('review-output').hidden=true;};sync();
function frame(now){if(stopped)return;const dt=Math.min(.05,(now-last)/1000||0);last=now;if(ready&&!document.hidden){if(walking){progress=Math.min(1,progress+dt*1.5/lengthOf(routeTo(selectedPitch())));if(progress>=1){walking=false;$('walk-play').textContent='重新播放路线';}$('walk-status').textContent=`${progress>=1?'已到达':'正在前往'}${pitchName(selectedPitch())} · ${Math.round(progress*100)}% · ${lengthOf(routeTo(selectedPitch())).toFixed(1)} m（以 1.5 m/s 示意播放）`;}updateWalker();controls.update();camera.position.y=Math.max(camera.position.y,terrainHeight(camera.position.x,camera.position.z)+.6);forest.update(camera);for(const group of [labels,proposal])group.traverse(o=>{if(o.isSprite)o.visible=o.getWorldPosition(new T.Vector3).distanceTo(camera.position)>=8;});renderer.render(scene,camera);}requestAnimationFrame(frame);}
try{renderer=new T.WebGLRenderer({canvas:$('planner-canvas'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.debug.onShaderError=()=>{error='着色器编译失败';ready=false;$('planner-loading').hidden=false;$('planner-loading').textContent='画面渲染失败，请刷新重试。';};camera=new T.PerspectiveCamera(48,1,.08,260);controls=new OrbitControls(camera,$('planner-canvas'));controls.enableDamping=true;controls.minDistance=1.1;controls.maxDistance=105;controls.maxPolarAngle=Math.PI/2-.02;controls.addEventListener('start',()=>{view='free';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed','false'));});const loader=new T.TextureLoader;await Promise.all(['aerial_grass_rock','brown_mud_dry'].flatMap(id=>['diff','nor_gl','rough'].map(async c=>{const t=await loader.loadAsync(`../assets/textures/${id}_${c}_1k.jpg`);t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());if(c==='diff')t.colorSpace=T.SRGBColorSpace;t.repeat.setScalar(c==='diff'&&id==='brown_mud_dry'?1:1/2.2);(maps[id]??={})[c]=t;})));createGround();fixedFacilities();const library=await loadPines(loader),chunks=new Map;for(const p of trees){const cx=Math.floor(p.x/16),cz=Math.floor(p.z/16),id=cx+':'+cz;if(!chunks.has(id))chunks.set(id,{x:cx*16+8,z:cz*16+8,trees:[]});chunks.get(id).trees.push(p);}forest=createForest(renderer,world,library,{trees,chunks:[...chunks.values()]});walker=createWalker(world,{terrain:terrainHeight,summit:{x:999,z:999}});makeProposal();lighting();setView('overview');const resize=()=>{const el=$('planner-stage');renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe($('planner-stage'));resize();forest.update(camera,true);renderer.render(scene,camera);if(!error){ready=true;$('planner-loading').hidden=true;}requestAnimationFrame(frame);await register();window.addEventListener('pagehide',()=>{stopped=true;abort.abort();observer.disconnect();controls.dispose();forest.dispose();renderer.dispose();},{once:true});}catch(e){error=e.message;$('planner-loading').hidden=false;$('planner-loading').textContent='场景加载失败：'+e.message;console.error(e);}
