import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {clamp,mix,smooth,createTrack,grip,landmarks,footprintDistance,routeClearances,vehicleRadius} from './model.mjs';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}}
function mesh(geo,mat,parent,pos=[0,0,0]){const m=new T.Mesh(geo,mat);m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(parent,mat,size,pos){return mesh(new T.BoxGeometry(...size),mat,parent,pos)}
function beam(parent,mat,a,b,r=.06){const A=V(...a),B=V(...b);const m=mesh(new T.CylinderGeometry(r,r,A.distanceTo(B),7),mat,parent);m.position.copy(A).add(B).multiplyScalar(.5);m.quaternion.setFromUnitVectors(V(0,1,0),B.sub(A).normalize());return m}
function combine(gs){const pos=[],norm=[],color=[];for(const g0 of gs){const g=g0.index?g0.toNonIndexed():g0;pos.push(...g.attributes.position.array);norm.push(...g.attributes.normal.array);if(g.attributes.color)color.push(...g.attributes.color.array);if(g!==g0)g.dispose()}const out=new T.BufferGeometry;out.setAttribute('position',new T.Float32BufferAttribute(pos,3));out.setAttribute('normal',new T.Float32BufferAttribute(norm,3));if(color.length===pos.length)out.setAttribute('color',new T.Float32BufferAttribute(color,3));return out}
function pineGeometry(){const gs=[],random=rng(93);for(let k=0;k<7;k++){const r=1.8*(1-k/8),h=1.5;const g=new T.ConeGeometry(r,h,12,2).toNonIndexed();const p=g.attributes.position;const colors=[];for(let i=0;i<p.count;i++){let x=p.getX(i),y=p.getY(i),z=p.getZ(i);const q=.82+random()*.35;x*=q;z*=q;p.setXYZ(i,x,y+k*.65+1.6,z);const c=new T.Color().setHSL(.255+random()*.035,.24+random()*.18,.17+random()*.15);colors.push(c.r,c.g,c.b)}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();gs.push(g)}return combine(gs)}
function makeVehicle(parent,palette='#dc9147'){
 const g=new T.Group;parent.add(g);const body=new T.Group;g.add(body);
 const mats={paint:new T.MeshStandardMaterial({color:palette,roughness:.31,metalness:.35}),dark:new T.MeshStandardMaterial({color:'#263631',roughness:.7}),rubber:new T.MeshStandardMaterial({color:'#202322',roughness:.94}),metal:new T.MeshStandardMaterial({color:'#8c9791',metalness:.82,roughness:.33}),cream:new T.MeshStandardMaterial({color:'#e4d9bd',roughness:.85}),glass:new T.MeshPhysicalMaterial({color:'#a4c9cc',transparent:true,opacity:.25,roughness:.1,metalness:.2,side:T.DoubleSide}),skin:new T.MeshStandardMaterial({color:'#c59169',roughness:.95}),shirt:new T.MeshStandardMaterial({color:'#466b64',roughness:.95})};
 box(body,mats.dark,[1.8,.18,3.05],[0,.77,0]);box(body,mats.paint,[1.85,.38,1],[0,.98,1.05]);box(body,mats.paint,[1.84,.4,.52],[0,.94,-1.35]);box(body,mats.dark,[1.7,.2,.18],[0,.71,1.58]);
 for(const x of [-.85,.85]){box(body,mats.paint,[.13,.32,1.9],[x,.91,-.25]);beam(body,mats.dark,[x,1.07,.62],[x,2.13,.52]);beam(body,mats.dark,[x,1.04,-1.18],[x,2.13,-1.13]);beam(body,mats.dark,[x,2.13,.52],[x,2.13,-1.13]);box(body,mats.cream,[.12,.35,.26],[x*.77,1.04,1.565]);}
 const roof=box(body,mats.cream,[2,.13,2.15],[0,2.19,-.32]);box(body,mats.glass,[1.58,.8,.035],[0,1.67,.55]);for(const z of [-.64,.03]){box(body,mats.dark,[1.4,.16,.4],[0,1.06,z]);box(body,mats.dark,[1.4,.45,.12],[0,1.28,z-.21]);}
 const wheels=[];for(const z of [-1.06,1.02])for(const x of [-1,1]){const hub=new T.Group;hub.position.set(x,.48,z);g.add(hub);const tire=mesh(new T.TorusGeometry(.37,.14,10,24),mats.rubber,hub);tire.rotation.y=Math.PI/2;const wheel=mesh(new T.CylinderGeometry(.26,.26,.23,12),mats.metal,hub);wheel.rotation.z=Math.PI/2;const cap=mesh(new T.CylinderGeometry(.09,.09,.25,10),mats.dark,hub);cap.rotation.z=Math.PI/2;wheels.push(hub);}
 for(const x of [-.37,.38]){const torso=mesh(new T.CapsuleGeometry(.14,.27,4,8),x<0?mats.shirt:mats.cream,body,[x,1.48,-.43]);const head=mesh(new T.SphereGeometry(.14,12,10),mats.skin,body,[x,1.86,-.43]);mesh(new T.SphereGeometry(.15,12,8,0,Math.PI*2,0,Math.PI/2),mats.cream,body,[x,1.91,-.43]);beam(body,mats.shirt,[x,1.5,-.32],[x,1.32,.13],.055);}
 const steering=mesh(new T.TorusGeometry(.19,.025,5,14),mats.dark,body,[-.37,1.33,.2]);steering.rotation.x=.8;
 for(let k=0;k<5;k++)box(body,mats.dark,[.16,.08,.035],[(k-2)*.24,1.02,1.568]);
 const originals=[];body.traverse(o=>{if(o.isMesh)originals.push({o,p:o.position.clone()})});return{g,body,wheels,roof,mats,originals};
}
export class ParkScene{
 constructor(canvas,cfg){this.cfg=cfg;this.track=createTrack(cfg.lift);this.canvas=canvas;this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;
 this.scene=new T.Scene;this.scene.background=new T.Color('#abc5cc');this.scene.fog=new T.FogExp2('#adc3c8',.006);
 this.camera=new T.PerspectiveCamera(43,1,.15,500);this.camera.position.set(77,66,86);this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(0,3,0);this.controls.enableDamping=true;this.controls.minDistance=8;this.controls.maxDistance=175;this.controls.maxPolarAngle=Math.PI*.475;this.controls.minPolarAngle=.12;
 this.sun=new T.DirectionalLight('#ffe3b0',3.2);this.sun.position.set(-40,65,35);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-70,right:70,top:60,bottom:-60,near:1,far:170});this.sun.shadow.bias=-.00035;this.sun.shadow.normalBias=.075;this.scene.add(this.sun);
 this.hemi=new T.HemisphereLight('#d4edf6','#787154',2);this.scene.add(this.hemi);this.world=new T.Group;this.scene.add(this.world);this.vehicles=[makeVehicle(this.scene),makeVehicle(this.scene,'#77978a')];this.staticMeshes=[];this.savedMaterials=new Map;this.loadingErrors=[];
 const loader=new T.TextureLoader;this.textures={};this.ready=Promise.all(['aerial_grass_rock','brown_mud_dry'].flatMap(id=>['diff','nor_gl','rough'].map(async channel=>{const url=`../assets/textures/${id}_${channel}_1k.jpg`;const texture=await loader.loadAsync(url);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());if(channel==='diff')texture.colorSpace=T.SRGBColorSpace;this.textures[`${id}_${channel}`]=texture}))).then(()=>{this.createMaterials();this.buildWorld();this.createWeather();this.resize();});this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.followTarget=V();this.lastCam='overview';this.time=0;
 }
 resize(){const {width,height}=this.canvas.parentElement.getBoundingClientRect();if(!width||!height)return;this.renderer.setSize(width,height,false);this.camera.aspect=width/height;this.camera.updateProjectionMatrix()}
 createMaterials(){const set=(id,extra={})=>new T.MeshStandardMaterial({map:this.textures[id+'_diff'],normalMap:this.textures[id+'_nor_gl'],roughnessMap:this.textures[id+'_rough'],roughness:.94,normalScale:new T.Vector2(.9,.9),...extra});this.materials={ground:set('aerial_grass_rock',{color:'#bdc1a3'}),road:set('brown_mud_dry',{color:'#c1ad8f',normalScale:new T.Vector2(.65,.65)}),stone:set('aerial_grass_rock',{color:'#93978d',normalScale:new T.Vector2(.4,.4)}),wood:new T.MeshStandardMaterial({color:'#776046',roughness:.94}),bark:new T.MeshStandardMaterial({color:'#746149',roughness:1}),leaf:new T.MeshStandardMaterial({vertexColors:true,roughness:.9}),grass:new T.MeshStandardMaterial({color:'#748249',roughness:1,side:T.DoubleSide}),ivory:new T.MeshStandardMaterial({color:'#e3deca',roughness:.8}),metal:new T.MeshStandardMaterial({color:'#384646',roughness:.55,metalness:.45})};this.materials.ground.map.repeat.set(1,1);}
 clearWorld(){this.world.traverse(o=>{if(o.isMesh)o.geometry.dispose()});this.world.clear();this.savedMaterials.clear()}
 buildWorld(){if(this.world.children.length)this.clearWorld();this.track=createTrack(this.cfg.lift);this.clearances=routeClearances(this.track);if(this.clearances.some(o=>o.margin<.3))throw Error('建筑侵入通行范围');const track=this.track,m=this.materials,random=rng(1234),terrain=new T.PlaneGeometry(132,104,160,126);terrain.rotateX(-Math.PI/2);const p=terrain.attributes.position,uv=terrain.attributes.uv;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,track.terrain(x,z));uv.setXY(i,x/12,z/12)}terrain.computeVertexNormals();this.ground=mesh(terrain,m.ground,this.world);this.ground.castShadow=false;this.ground.userData.category='terrain';
 // The road and vehicle both sample the same elevation function.
 const pos=[],uvs=[],indices=[],roadN=480;for(let i=0;i<=roadN;i++){const s=i/roadN*track.length;for(const lane of [-3.2,3.2]){const q=track.sample(s,lane);pos.push(q.x,q.y,q.z);uvs.push(s/4,lane/4)}}for(let i=0;i<roadN;i++){const a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3)}const roadGeo=new T.BufferGeometry;roadGeo.setAttribute('position',new T.Float32BufferAttribute(pos,3));roadGeo.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));roadGeo.setIndex(indices);roadGeo.computeVertexNormals();this.road=mesh(roadGeo,m.road,this.world);this.road.castShadow=false;this.road.userData.category='road';this.road.material.side=T.DoubleSide;
 // Irregular rocky lake shoreline with a lit water surface.
 const waterGeo=new T.CircleGeometry(1,100);waterGeo.rotateX(-Math.PI/2);const wp=waterGeo.attributes.position;for(let i=0;i<wp.count;i++){const x=wp.getX(i),z=wp.getZ(i),a=Math.atan2(z,x),r=1+.026*Math.sin(a*7)+.015*Math.cos(a*11);wp.setXYZ(i,-6+x*13*r,1.37,-1+z*10*r)}waterGeo.computeVertexNormals();this.waterMat=new T.MeshPhysicalMaterial({color:'#3d8889',roughness:.21,metalness:.38,transparent:true,opacity:.88,side:T.DoubleSide});this.water=mesh(waterGeo,this.waterMat,this.world);this.water.castShadow=false;this.water.userData.category='terrain';
 const rippleGeo=new T.BufferGeometry,arr=[];for(let k=0;k<28;k++){const a=random()*Math.PI*2,r=Math.sqrt(random());arr.push(-6+Math.cos(a)*r*12,1.405,-1+Math.sin(a)*r*9)}rippleGeo.setAttribute('position',new T.Float32BufferAttribute(arr,3));this.sparkles=new T.Points(rippleGeo,new T.PointsMaterial({color:'#dfefdf',size:.12,transparent:true,opacity:.6}));this.sparkles.userData.category='terrain';this.world.add(this.sparkles);
 const treePositions=[];for(let i=0;i<420;i++){const x=(random()-.5)*116,z=(random()-.5)*85;if(track.nearest(x,z).distance<6||track.lakeRadius(x,z)<1.45||landmarks.some(o=>footprintDistance(x,z,o)<3))continue;if(z>12&&random()<.72)continue;treePositions.push({x,z,y:track.terrain(x,z),scale:.65+random()*.75,angle:random()*6.28})}this.treePositions=treePositions;
 const pine=pineGeometry(),trunk=new T.CylinderGeometry(.12,.27,4.4,7);trunk.translate(0,2.2,0);const tops=new T.InstancedMesh(pine,m.leaf,treePositions.length),stems=new T.InstancedMesh(trunk,m.bark,treePositions.length),dummy=new T.Object3D;treePositions.forEach((t,i)=>{dummy.position.set(t.x,t.y,t.z);dummy.rotation.set(0,t.angle,0);dummy.scale.setScalar(t.scale);dummy.updateMatrix();tops.setMatrixAt(i,dummy.matrix);stems.setMatrixAt(i,dummy.matrix)});tops.castShadow=stems.castShadow=true;tops.receiveShadow=true;tops.userData.category=stems.userData.category='nature';this.world.add(tops,stems);this.trees=tops;
 const rg=new T.IcosahedronGeometry(1,1);const rp=rg.attributes.position;for(let i=0;i<rp.count;i++){const x=rp.getX(i),y=rp.getY(i),z=rp.getZ(i);const s=1+.18*Math.sin(x*13+y*9+z*7);rp.setXYZ(i,x*s,y*s*.73,z*s)}rg.computeVertexNormals();const stones=[];for(let i=0;i<160;i++){let x,z,sc;if(i<75){const a=i/75*Math.PI*2;x=-6+Math.cos(a)*(13.5+random()*1.4);z=-1+Math.sin(a)*(10.5+random()*1.2);sc=.3+random()*.75}else{x=(random()-.5)*115;z=(random()-.5)*90;sc=.55+random()*2}if(track.nearest(x,z).distance<5.1+sc*1.85||track.lakeRadius(x,z)<1||landmarks.some(o=>footprintDistance(x,z,o)<sc*1.85+1))continue;stones.push({x,z,sc})}const rocks=new T.InstancedMesh(rg,m.stone,stones.length);stones.forEach((r,i)=>{dummy.position.set(r.x,track.terrain(r.x,r.z)+.1,r.z);dummy.rotation.set(random()*.5,random()*6.28,random()*.3);dummy.scale.set(r.sc*1.5,r.sc,r.sc);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix)});rocks.castShadow=true;rocks.receiveShadow=true;rocks.userData.category='nature';this.world.add(rocks);
 // Roadside details reinforce scale and route readability.
 for(let s=0;s<track.length;s+=3.8){const q=track.sample(s,3.65);if(q.z<0||q.x>24){const g=track.terrain(q.x,q.z);beam(this.world,m.wood,[q.x,g,q.z],[q.x,g+1.25,q.z],.07);const next=track.sample(s+3.8,3.65);for(const h of [.55,1.05])beam(this.world,m.wood,[q.x,g+h,q.z],[next.x,track.terrain(next.x,next.z)+h,next.z],.045)}}
 for(let s=0;s<track.length;s+=1.6){const q=track.sample(s,-2.65);const stone=mesh(new T.BoxGeometry(.32,.12,.65),s%3.2<1.6?m.ivory:m.stone,this.world,[q.x,q.y+.06,q.z]);stone.rotation.y=Math.atan2(q.forward.x,q.forward.z);}
 for(const o of landmarks){if(o.id==='cabin')this.createCabin(o.x,o.z,o.angle);if(o.id==='lookout')this.createLookout(o.x,o.z);if(o.id==='windmill')this.createWindmill(o.x,o.z);}this.createBrakeBay();
 // Grass is actual instanced geometry, separate from grass in the ground texture.
 const gg=new T.BufferGeometry;gg.setAttribute('position',new T.Float32BufferAttribute([-.12,0,0,0,.58,.07,.08,0,0,0,0,-.15,.1,.4,0,0,0,.15],3));gg.computeVertexNormals();const gp=[];for(let i=0;i<3000;i++){const x=(random()-.5)*112,z=(random()-.5)*84;if(track.nearest(x,z).distance<3.5||track.lakeRadius(x,z)<1.15||landmarks.some(o=>footprintDistance(x,z,o)<.5))continue;gp.push([x,track.terrain(x,z),z])}const grass=new T.InstancedMesh(gg,m.grass,gp.length);gp.forEach((p,i)=>{dummy.position.set(...p);dummy.rotation.set(0,random()*6.28,0);dummy.scale.setScalar(.6+random()*.75);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix)});grass.userData.category='nature';this.world.add(grass);this.grass=grass;
 // Highlight the editable section without obscuring its ground texture.
 const markers=new T.Group;this.world.add(markers);for(const u of [.12,.22]){const s=u*track.length,q=track.sample(s);for(const lane of [-3.35,3.35]){const a=track.sample(s,lane);beam(markers,m.metal,[a.x,a.y,a.z],[a.x,a.y+2,a.z],.045);box(markers,new T.MeshStandardMaterial({color:'#d9a24b'}),[.13,.38,.48],[a.x,a.y+1.78,a.z])}}this.editMarkers=markers;
 for(const o of this.world.children)o.userData.category??='road';this.auditBuildingGeometry();this.createBounds();this.captureMaterials();this.applyMaterial();}
 createCabin(x,z,angle){const y=this.track.terrain(x,z),g=new T.Group;g.position.set(x,y,z);g.rotation.y=angle;g.userData.landmark='cabin';g.userData.category='buildings';this.world.add(g);const m=this.materials;box(g,m.stone,[8,.4,5.2],[0,0,0]);box(g,m.wood,[5.5,2.8,3.8],[0,1.55,0]);for(const sx of [-1,1]){const roof=box(g,m.metal,[3.8,.14,5],[sx*1.65,3.48,0]);roof.rotation.z=sx*.31;}for(const k of [-1.7,1.7]){box(g,m.ivory,[1.2,1.15,.08],[k,1.8,1.94]);box(g,new T.MeshStandardMaterial({color:'#467477',roughness:.2,metalness:.35}),[.96,.93,.09],[k,1.8,1.99])}box(g,m.metal,[.85,1.9,.08],[0,1.15,1.95]);for(let k=0;k<3;k++)box(g,m.stone,[2,.2,1.2],[0,-.25-k*.14,2.5+k*.4]);for(const sx of [-1,1]){beam(g,m.wood,[sx*3.5,0,2.2],[sx*3.5,2.8,2.2],.1)}
 const signCanvas=document.createElement('canvas');signCanvas.width=512;signCanvas.height=128;const ctx=signCanvas.getContext('2d');ctx.fillStyle='#163c39';ctx.fillRect(0,0,512,128);ctx.fillStyle='#f1e4c6';ctx.font='44px "Microsoft YaHei",sans-serif';ctx.textAlign='center';ctx.fillText('松岚湖 · 巡游站',256,79);const texture=new T.CanvasTexture(signCanvas);texture.colorSpace=T.SRGBColorSpace;mesh(new T.PlaneGeometry(3.5,.85),new T.MeshBasicMaterial({map:texture}),g,[0,2.8,2.04]);}
 createLookout(x,z){const y=this.track.terrain(x,z),g=new T.Group;g.position.set(x,y+.2,z);g.userData.landmark='lookout';g.userData.category='buildings';this.world.add(g);const m=this.materials;box(g,m.wood,[6,.2,4],[0,0,0]);for(const sx of [-1,1]){for(const sz of [-1,1])beam(g,m.wood,[sx*2.8,0,sz*1.8],[sx*2.8,1.15,sz*1.8],.065);beam(g,m.wood,[sx*2.8,1.15,-1.8],[sx*2.8,1.15,1.8],.04)}for(let i=0;i<3;i++)box(g,m.metal,[1.8,.4,.55],[i*1.8-1.8,.4,-.9]);}
 createWindmill(x,z){const y=this.track.terrain(x,z);const g=new T.Group;g.position.set(x,y,z);g.userData.landmark='windmill';g.userData.category='buildings';this.world.add(g);const m=this.materials;mesh(new T.CylinderGeometry(.18,.4,9,9),m.ivory,g,[0,4.5,0]);const blades=new T.Group;blades.position.set(0,9,.35);g.add(blades);mesh(new T.SphereGeometry(.32,10,8),m.ivory,blades);for(let k=0;k<3;k++){const arm=new T.Group;arm.rotation.z=k*2*Math.PI/3;blades.add(arm);const blade=box(arm,m.ivory,[.25,3.8,.1],[0,2,0]);blade.rotation.z=.12}this.windBlades=blades;}
 auditBuildingGeometry(){this.world.updateMatrixWorld(true);this.buildingGeometryAudit=[];for(const g of this.world.children.filter(o=>o.userData.landmark)){const spec=landmarks.find(o=>o.id===g.userData.landmark),inverse=g.matrixWorld.clone().invert();let overflow=0,vertices=0;g.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){const p=V().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).applyMatrix4(inverse);if(spec.id==='windmill'&&p.y>3)continue;vertices++;overflow=Math.max(overflow,Math.abs(p.x)-spec.halfX,spec.minZ-p.z,p.z-spec.maxZ);}});this.buildingGeometryAudit.push({id:spec.id,vertices,overflow:Number(overflow.toFixed(6))});if(overflow>.001)throw Error(spec.label+'几何超出占地约束');}}
 createBounds(){const g=new T.Group;g.userData.category='bounds';this.world.add(g);for(const o of landmarks){const outline=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(o.halfX*2,5,o.maxZ-o.minZ)),new T.LineBasicMaterial({color:'#ffc14d',depthTest:false,transparent:true,opacity:.85}));const wrapper=new T.Group;wrapper.position.set(o.x,this.track.terrain(o.x,o.z),o.z);wrapper.rotation.y=o.angle;outline.position.set(0,2.5,(o.minZ+o.maxZ)/2);outline.renderOrder=10;wrapper.add(outline);g.add(wrapper);}this.boundsGroup=g;
 for(const v of this.vehicles){if(v.boundRing)continue;const pts=Array.from({length:65},(_,i)=>V(Math.cos(i/64*Math.PI*2)*vehicleRadius,.2,Math.sin(i/64*Math.PI*2)*vehicleRadius));v.boundRing=new T.Line(new T.BufferGeometry().setFromPoints(pts),new T.LineBasicMaterial({color:'#57ffff',depthTest:false,transparent:true,opacity:.85}));v.boundRing.renderOrder=10;v.g.add(v.boundRing);}}
 applyVisibility(){const cfg=this.cfg,map={terrain:cfg.showTerrain,road:cfg.showRoad,buildings:cfg.showBuildings,nature:cfg.showNature,bounds:cfg.bounds};for(const o of this.world.children)o.visible=map[o.userData.category]??true;if(this.editMarkers)this.editMarkers.visible=cfg.showRoad&&cfg.layer===1;for(const v of this.vehicles){v.g.visible=cfg.showVehicles;if(v.boundRing)v.boundRing.visible=cfg.bounds;}if(this.brakeDemo)for(const v of this.brakeDemo.vehicles)v.g.visible=cfg.showVehicles;}
 compositionAudit(){const result={visibleMeshes:0,texturedMeshes:0,litMeshes:0,visibleVehicles:this.vehicles.filter(v=>v.g.visible).length};this.scene.traverseVisible(o=>{if(!o.isMesh)return;result.visibleMeshes++;const mats=Array.isArray(o.material)?o.material:[o.material];if(mats.some(m=>m.map))result.texturedMeshes++;if(mats.some(m=>m.isMeshStandardMaterial||m.isMeshPhysicalMaterial))result.litMeshes++;});return result;}
 focusCabin(){const o=landmarks[0],y=this.track.terrain(o.x,o.z);this.camera.position.set(o.x-15,y+15,o.z+22);this.controls.target.set(o.x+5,y+1,o.z-2);this.controls.update();}
 captureMaterials(){this.world.traverse(o=>{if(o.isMesh&&!this.savedMaterials.has(o))this.savedMaterials.set(o,o.material)});for(const v of this.vehicles)v.g.traverse(o=>{if(o.isMesh)this.savedMaterials.set(o,o.material)});}
 applyMaterial(){if(!this.materials)return;const cfg=this.cfg;this.clay??=new T.MeshStandardMaterial({color:'#d3d8d2',roughness:.85,side:T.DoubleSide});this.wire??=new T.MeshBasicMaterial({color:'#bedacc',wireframe:true});this.normalView??=new T.MeshNormalMaterial({side:T.DoubleSide});this.colorOnly??=new Map;for(const [o,mat] of this.savedMaterials){if(cfg.layer!==4||cfg.material==='full'){if(cfg.textures&&cfg.lighting)o.material=mat;else{this.assemblyMaterials??=new Map;const key=mat.uuid+'-'+cfg.textures+'-'+cfg.lighting;if(!this.assemblyMaterials.has(key)){const flat=cfg.lighting?mat.clone():new T.MeshBasicMaterial({color:mat.color||'#ffffff',vertexColors:mat.vertexColors||false,side:T.DoubleSide,map:cfg.textures?mat.map:null});if(!cfg.textures){flat.map=null;flat.normalMap=null;flat.roughnessMap=null;}this.assemblyMaterials.set(key,flat);}o.material=this.assemblyMaterials.get(key);}}else if(cfg.material==='clay')o.material=this.clay;else if(cfg.material==='wire')o.material=this.wire;else if(cfg.material==='normal')o.material=this.normalView;else{if(!this.colorOnly.has(mat))this.colorOnly.set(mat,new T.MeshBasicMaterial({map:mat.map||null,color:mat.color||'#a6bbae',vertexColors:mat.vertexColors||false,side:T.DoubleSide}));o.material=this.colorOnly.get(mat)}}const m=this.materials;for(const mat of [m.ground,m.road,m.stone]){mat.normalScale.setScalar(cfg.normal*(mat===m.road?.65:.9));mat.roughness=cfg.roughness*(1-.7*cfg.wet);for(const key of ['map','normalMap','roughnessMap'])if(mat[key])mat[key].repeat.setScalar(cfg.repeat)}m.road.color.set('#c1ad8f').lerp(new T.Color('#595649'),cfg.wet*.68);m.ground.color.set('#bdc1a3').lerp(new T.Color('#687366'),cfg.wet*.3);this.renderer.shadowMap.enabled=cfg.shadows;this.sun.castShadow=cfg.shadows;this.sun.intensity=mix(3.2,1.2,cfg.wet);this.hemi.intensity=mix(2,1.5,cfg.wet);this.scene.background.set('#abc5cc').lerp(new T.Color('#70838d'),cfg.wet);this.scene.fog.color.copy(this.scene.background);this.scene.fog.density=mix(.006,.009,cfg.wet);this.applyVisibility();}
 setConfig(cfg){const rebuild=cfg.lift!==this.cfg.lift;const modeChanged=cfg.camera!==this.cfg.camera;const leaveBrake=cfg.layer!==2||modeChanged;this.cfg={...cfg};if(leaveBrake&&this.brakeDemo)this.brakeDemo.active=false;if(rebuild)this.buildWorld();this.applyMaterial();if(modeChanged){if(cfg.camera==='overview'){this.camera.position.set(77,66,86);this.controls.target.set(0,3,0)}else if(cfg.camera==='detail'){const q=this.track.sample(this.track.length*.17);this.camera.position.set(q.x+12,q.y+7,q.z+12);this.controls.target.set(q.x,q.y+.6,q.z)}}this.controls.enabled=cfg.camera==='overview'||cfg.camera==='detail';}
 createBrakeBay(){const g=new T.Group;g.position.set(-16,3.8,39);g.rotation.y=Math.PI/2;this.world.add(g);const road=new T.MeshStandardMaterial({color:'#656965',roughness:.87});box(g,road,[8,.35,21],[0,-.17,5.5]);for(const x of [-3.8,0,3.8])box(g,this.materials.ivory,[.08,.02,20],[x,.02,5.5]);for(let z=0;z<=12;z+=2)for(const x of [-3.4,3.4])box(g,this.materials.ivory,[.7,.02,.065],[x,.03,z]);box(g,this.materials.ivory,[7.8,.02,.13],[0,.04,0]);const vehicles=[makeVehicle(g,'#d39a52'),makeVehicle(g,'#739ba0')];vehicles[0].g.position.set(-1.9,.02,-2);vehicles[1].g.position.set(1.9,.02,-2);this.brakeDemo={active:false,running:false,time:0,velocities:[0,0],distances:[0,0],vehicles};this.brakeBay=g;}
 startBraking(){this.brakeDemo.active=true;this.brakeDemo.running=true;this.brakeDemo.time=0;this.brakeDemo.velocities=[24/3.6,24/3.6];this.brakeDemo.distances=[0,0];this.camera.position.set(3,17,60);this.controls.target.set(-10,4.5,39);this.controls.update();}
 updateBraking(dt){const b=this.brakeDemo;if(!b)return;if(b.running){b.time+=dt;for(let i=0;i<2;i++){const a=grip(i)*9.81,h=Math.min(dt,b.velocities[i]/a);b.distances[i]+=b.velocities[i]*h-.5*a*h*h;b.velocities[i]=Math.max(0,b.velocities[i]-a*h);b.vehicles[i].g.position.set(i?1.9:-1.9,.02,b.distances[i]);b.vehicles[i].body.rotation.x=b.velocities[i]>.02?.04:0;b.vehicles[i].wheels.forEach(w=>w.rotation.x+=b.velocities[i]*h/.48)}b.running=b.velocities.some(v=>v>.001)};}
 createWeather(){const random=rng(82),a=new Float32Array(1300*6);for(let i=0;i<1300;i++){const x=(random()-.5)*115,y=random()*48,z=(random()-.5)*92;a.set([x,y,z,x-.2,y+1.4,z+.05],i*6)}const g=new T.BufferGeometry;g.setAttribute('position',new T.BufferAttribute(a,3));this.rain=new T.LineSegments(g,new T.LineBasicMaterial({color:'#ccdde3',transparent:true,opacity:.32,depthWrite:false}));this.rain.frustumCulled=false;this.scene.add(this.rain);
 const dustGeo=new T.BufferGeometry;dustGeo.setAttribute('position',new T.BufferAttribute(new Float32Array(120*3),3));const dustCanvas=document.createElement('canvas');dustCanvas.width=dustCanvas.height=32;const c=dustCanvas.getContext('2d'),gradient=c.createRadialGradient(16,16,0,16,16,16);gradient.addColorStop(0,'rgba(255,255,255,.8)');gradient.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=gradient;c.fillRect(0,0,32,32);this.dust=new T.Points(dustGeo,new T.PointsMaterial({color:'#cfb797',size:.65,map:new T.CanvasTexture(dustCanvas),transparent:true,opacity:.35,depthWrite:false}));this.dust.frustumCulled=false;this.scene.add(this.dust);this.particles=Array.from({length:120},()=>({x:0,y:-100,z:0,life:0}));this.particleIndex=0;
 }
 update(dt,states){if(!this.materials)return;const cfg=this.cfg,motionDt=cfg.paused?0:dt;this.time+=motionDt;for(let i=0;i<2;i++){const state=states[i],v=this.vehicles[i],p=this.track.sample(state.s,state.lane);v.g.position.set(p.x,p.y+.04,p.z);v.g.rotation.set(0,Math.atan2(p.forward.x,p.forward.z),0);v.body.rotation.x=-state.bodyPitch;v.body.rotation.z=state.bodyRoll;v.body.position.y=cfg.motion?Math.sin(this.time*15)*.016*state.v:0;v.wheels.forEach((wheel,j)=>{if(cfg.motion)wheel.rotation.x+=state.v*motionDt/.48;const along=j<2?-1.06:1.02,side=j%2?-1:1;const q=this.track.sample(state.s+along,state.lane+side);wheel.position.y=.48+q.y-p.y;});const explode=cfg.layer===4?cfg.explode:0;for(const {o,p}of v.originals){o.position.copy(p);if(explode){o.position.y+=p.y*explode*1.4;o.position.x+=p.x*explode*.9}}}
 const a=states[0],q=this.track.sample(a.s,a.lane);if(cfg.camera==='follow'||cfg.camera==='driver'){const distance=cfg.camera==='driver'?-.15:-9,up=cfg.camera==='driver'?2.15:5;const pos=V(q.x+q.forward.x*distance,q.y+up,q.z+q.forward.z*distance);const target=this.track.sample(a.s+(cfg.camera==='driver'?12:5),a.lane);this.camera.position.lerp(pos,1-Math.exp(-dt*4));this.followTarget.lerp(V(target.x,target.y+1.2,target.z),1-Math.exp(-dt*5));this.camera.lookAt(this.followTarget);}else this.controls.update();
 if(this.windBlades&&cfg.motion)this.windBlades.rotation.z+=motionDt*(.5+cfg.wet);if(this.sparkles)this.sparkles.material.opacity=.35+Math.sin(this.time*1.2)*.15;
 this.rain.visible=cfg.wet>.08&&cfg.motion&&cfg.showTerrain;if(this.rain.visible){this.rain.geometry.setDrawRange(0,Math.floor(1300*cfg.wet)*2);const a=this.rain.geometry.attributes.position.array;for(let i=0;i<a.length;i+=6){a[i+1]-=motionDt*22;a[i+4]-=motionDt*22;if(a[i+1]<0){a[i+1]+=48;a[i+4]+=48}}this.rain.geometry.attributes.position.needsUpdate=true;}
 this.dust.visible=cfg.motion&&cfg.showVehicles&&a.v>1;const wet=cfg.wet;this.dust.material.color.set(wet>.4?'#c6d8d8':'#c9b294');this.dust.material.opacity=wet>.4?.34:.27;this.dust.material.size=wet>.4?.25:.7;
 if(this.dust.visible&&motionDt>0){for(let k=0;k<2;k++){const p=this.particles[this.particleIndex++%120];p.x=q.x-q.forward.x*1.4+q.forward.z*(k?1:-1)*.8;p.y=q.y+.3;p.z=q.z-q.forward.z*1.4-q.forward.x*(k?1:-1)*.8;p.life=wet>.4?.5:1.6;}}
 const arr=this.dust.geometry.attributes.position.array;this.particles.forEach((p,i)=>{p.life-=motionDt;if(p.life>0){p.y+=motionDt*.4;p.x+=motionDt*.22;arr.set([p.x,p.y,p.z],i*3)}else arr[i*3+1]=-100});this.dust.geometry.attributes.position.needsUpdate=true;
 for(const o of landmarks){if(footprintDistance(this.camera.position.x,this.camera.position.z,o)<1.2)this.camera.position.y=Math.max(this.camera.position.y,this.track.terrain(o.x,o.z)+6.5);}
 this.updateBraking(motionDt);this.renderer.render(this.scene,this.camera);
 }
 editLabel(){const p=this.track.sample(this.track.length*.17),v=V(p.x,p.y+2,p.z).project(this.camera);return{x:(v.x*.5+.5)*this.canvas.clientWidth,y:(-.5*v.y+.5)*this.canvas.clientHeight,visible:v.z<1&&Math.abs(v.x)<1&&Math.abs(v.y)<1}}
 dispose(){this.resizeObserver.disconnect();this.controls.dispose();this.renderer.dispose();}
}
