import {keepHabitatTree} from './environment-core.mjs';
// One height function for the outer landscape mesh and its vegetation.
export const forestBounds=Object.freeze({halfSize:112,landscapeHalfSize:120,cellSize:16});
export function outerHeight(land,x,z){const d=Math.max(Math.abs(x),Math.abs(z)),rise=Math.max(0,Math.min(1,(d-34)/22));return land.terrain(x,z)-.12+rise*(5+7*Math.sin(x*.049+Math.sin(z*.025))**2+6*Math.cos(z*.063+x*.018)**2);}
// Match the rendered landscape's two triangles per grid cell, not an unrelated formula.
export function meshHeight(height,x,z,size=240,segments=90){const step=size/segments,gx=Math.max(0,Math.min(segments-1e-8,(x+size/2)/step)),gz=Math.max(0,Math.min(segments-1e-8,(z+size/2)/step)),i=Math.floor(gx),j=Math.floor(gz),u=gx-i,v=gz-j,x0=-size/2+i*step,z0=-size/2+j*step,a=height(x0,z0),b=height(x0+step,z0),c=height(x0,z0+step),d=height(x0+step,z0+step);return u+v<=1?a+(b-a)*u+(c-a)*v:d+(c-d)*(1-u)+(b-d)*(1-v);}
const heightCaches=new WeakMap;
export function forestHeight(land,x,z){let cache=heightCaches.get(land);if(!cache){const memo=fn=>{const values=new Map;return(a,b)=>{const key=a+','+b;if(!values.has(key))values.set(key,fn(a,b));return values.get(key);};};cache={inner:memo(land.terrain),outer:memo((a,b)=>outerHeight(land,a,b))};heightCaches.set(land,cache);}return Math.max(Math.abs(x),Math.abs(z))<=32?meshHeight(cache.inner,x,z,64,180):meshHeight(cache.outer,x,z);}
export function expandForest(land){let seed=9417;const rand=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296),trees=land.trees.map(p=>({...p,y:forestHeight(land,p.x,p.z),zone:'camp'}));const grid=new Map,cell=3,key=(x,z)=>`${x},${z}`;function add(p){const k=key(Math.floor(p.x/cell),Math.floor(p.z/cell));if(!grid.has(k))grid.set(k,[]);grid.get(k).push(p);}trees.forEach(add);
 for(let z=-110;z<112;z+=3.7)for(let x=-110;x<112;x+=3.7){const px=x+(rand()-.5)*2.9,pz=z+(rand()-.5)*2.9;if(Math.max(Math.abs(px),Math.abs(pz))<22)continue;const forward=(px-land.summit.x)*.41-(pz-land.summit.z)*.91,across=Math.abs((px-land.summit.x)*.91+(pz-land.summit.z)*.41);if(forward>15&&forward<115&&across<1+forward*.035)continue;const scale=.72+rand()*.7,patch=.5+.23*Math.sin(px*.12+Math.sin(pz*.075))+.2*Math.cos(pz*.14-px*.04);if(rand()>patch+.23)continue;if(land.isPlantable&&!land.isPlantable(px,pz,scale*1.14))continue;const y=forestHeight(land,px,pz),dx=(forestHeight(land,px+.3,pz)-forestHeight(land,px-.3,pz))/.6,dz=(forestHeight(land,px,pz+.3)-forestHeight(land,px,pz-.3))/.6;if(Math.hypot(dx,dz)>1.1)continue;
 const gx=Math.floor(px/cell),gz=Math.floor(pz/cell);let overlap=false;for(let j=-2;j<=2&&!overlap;j++)for(let i=-2;i<=2&&!overlap;i++)for(const p of grid.get(key(gx+i,gz+j))||[])if(Math.hypot(px-p.x,pz-p.z)<(scale+p.scale)*1.3){overlap=true;break;}if(overlap)continue;const p={x:px,z:pz,y,scale,zone:'valley'};trees.push(p);add(p);}
 for(const p of trees){const h=Math.abs(Math.sin(p.x*12.9898+p.z*78.233)*43758.5453)%1;const k=Math.abs(Math.sin(p.x*39.31-p.z*11.17)*17431.3)%1;p.width=p.zone==='camp'?.84+h*.16:.76+h*.38;p.height=.86+k*.25;p.variant=Math.floor(h*3);p.tint=['#ced8b8','#b6caa8','#dfdfbe','#a9c1a5'][Math.floor(k*4)];}
 for(let i=trees.length-1;i>=0;i--)if(!keepHabitatTree(land,trees[i]))trees.splice(i,1);
 const chunks=new Map;for(const p of trees){const ix=Math.floor(p.x/16),iz=Math.floor(p.z/16),k=key(ix,iz);if(!chunks.has(k))chunks.set(k,{x:ix*16+8,z:iz*16+8,trees:[]});chunks.get(k).trees.push(p);}return{trees,chunks:[...chunks.values()],bounds:forestBounds};
}
