import {softenCrownNormals,shadeFoliage,padTwigColour} from './foliage-shading.mjs';
import * as T from './vendor/three.module.js';
import {pineDimensions} from './reuse-core.mjs';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const random=seed=>()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
function buffer(){return{p:[],n:[],uv:[]};}
function append(out,geometry,matrix){const g=geometry.index?geometry.toNonIndexed():geometry.clone();g.applyMatrix4(matrix);out.p.push(...g.attributes.position.array);out.n.push(...g.attributes.normal.array);out.uv.push(...g.attributes.uv.array);g.dispose();geometry.dispose();}
function finish(out){const g=new T.BufferGeometry;g.setAttribute('position',new T.Float32BufferAttribute(out.p,3));g.setAttribute('normal',new T.Float32BufferAttribute(out.n,3));g.setAttribute('uv',new T.Float32BufferAttribute(out.uv,2));g.computeBoundingSphere();return g;}
function branch(out,a,b,r1,r2){const d=b.clone().sub(a),q=new T.Quaternion().setFromUnitVectors(V(0,1,0),d.clone().normalize());append(out,new T.CylinderGeometry(r2,r1,d.length(),5),new T.Matrix4().compose(a.clone().add(b).multiplyScalar(.5),q,V(1,1,1)));}
function twig(out,base,dir,width,length,roll){const q=new T.Quaternion().setFromUnitVectors(V(0,1,0),dir.clone().normalize());q.multiply(new T.Quaternion().setFromAxisAngle(V(0,1,0),roll));const g=new T.PlaneGeometry(width,length);g.translate(0,length/2,0);const uv=g.attributes.uv;for(let i=0;i<uv.count;i++)uv.setXY(i,.006+uv.getX(i)*.201,.554+uv.getY(i)*.405);append(out,g,new T.Matrix4().compose(base,q,V(1,1,1)));}
export function makePineGeometry(seed){const rng=random(seed),wood=buffer(),needles=buffer();branch(wood,V(),V(.10,pineDimensions.height,0),.16,.012);
 for(let tier=0;tier<11;tier++){const y=1.65+tier*.405+(rng()-.5)*.20,radius=(1-tier/12)*1.42;for(let j=0;j<6;j++){if(rng()<.17)continue;const a=j/6*Math.PI*2+tier*2.39+rng()*.48,start=V(.015,y,0),end=V(Math.cos(a)*radius*(.6+rng()*.4),y+.08+rng()*.3,Math.sin(a)*radius*(.6+rng()*.4));branch(wood,start,end,.032*(1-tier/13),.003);
 for(let k=0;k<9;k++){const t=.18+k*.09,b=start.clone().lerp(end,t);for(const sign of [-1,1]){const angle=a+sign*(.55+rng()*.5),length=(.38+rng()*.2)*(1-tier*.025),dir=V(Math.cos(angle),.2+rng()*.5,Math.sin(angle));twig(needles,b,dir,length*.52,length,rng()*Math.PI);twig(needles,b,dir,length*.52,length,Math.PI/2+rng()*.3);}}}}
 const trunk=finish(wood),p=trunk.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,Math.max(0,Math.min(pineDimensions.height,p.getY(i))));const crown=finish(needles);softenCrownNormals(crown);return{wood:trunk,needles:crown};
}
export async function loadPines(loader){const result={};await Promise.all(['twig_diff','twig_alpha','bark_diff','bark_nor_gl'].map(async key=>{const t=await loader.loadAsync(`../assets/vegetation/pine_tree_01_${key}_1k.${key==='twig_alpha'?'png':'jpg'}`);if(key.endsWith('diff'))t.colorSpace=T.SRGBColorSpace;t.anisotropy=4;result[key]=t;}));result.bark_diff.wrapS=result.bark_diff.wrapT=result.bark_nor_gl.wrapS=result.bark_nor_gl.wrapT=T.RepeatWrapping;
 result.twig_diff=padTwigColour(result.twig_diff,result.twig_alpha);
 const bark=new T.MeshStandardMaterial({map:result.bark_diff,normalMap:result.bark_nor_gl,normalScale:new T.Vector2(.7,.7),roughness:.95});const leaf=new T.MeshStandardMaterial({map:result.twig_diff,alphaMap:result.twig_alpha,alphaTest:.35,alphaToCoverage:false,side:T.DoubleSide,color:'#ffffff',roughness:1});shadeFoliage(leaf);const depth=new T.MeshDepthMaterial({depthPacking:T.RGBADepthPacking,map:result.twig_diff,alphaMap:result.twig_alpha,alphaTest:.45,side:T.DoubleSide});return{variants:[makePineGeometry(51),makePineGeometry(157),makePineGeometry(391)],bark,leaf,depth};
}
export function plantPines(side,library,places){const dummy=new T.Object3D;for(let v=0;v<3;v++){const ps=places.filter((p,i)=>(p.variant??i%3)===v),tree=library.variants[v];for(const [geo,mat,isLeaf] of [[tree.wood,library.bark,false],[tree.needles,library.leaf,true]]){const mesh=new T.InstancedMesh(geo,mat,ps.length);mesh.userData.sharedResources=true;mesh.castShadow=true;mesh.receiveShadow=!isLeaf;if(isLeaf)mesh.customDepthMaterial=library.depth;ps.forEach((p,i)=>{dummy.position.set(p.x,p.y-.025,p.z);dummy.rotation.set(0,(p.x*17+p.z*29)%6.28,0);dummy.scale.set(p.scale*(p.width??1),p.scale*(p.height??1),p.scale*(p.width??1));dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);if(p.tint)mesh.setColorAt(i,new T.Color(p.tint));});side.world.add(mesh);}}}
// Blend by distance to the route in world metres; noise breaks up the shoulder.
export function blendGround(mat,mud,normal,width,recipe){mat.onBeforeCompile=s=>{s.uniforms.roadMap={value:mud};s.uniforms.roadNormal={value:normal};s.uniforms.roadHalf={value:width/2};s.uniforms.roadTint={value:new T.Color(recipe.tint)};s.uniforms.roadRoughness={value:recipe.roughness};s.vertexShader='attribute float roadDistance; varying float vRoadDistance; varying vec2 vGroundUv;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <uv_vertex>','#include <uv_vertex>\nvRoadDistance=roadDistance; vGroundUv=uv;');s.fragmentShader='uniform sampler2D roadMap; uniform sampler2D roadNormal; uniform float roadHalf; uniform vec3 roadTint; uniform float roadRoughness; varying float vRoadDistance; varying vec2 vGroundUv;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>',`#include <map_fragment>
 float edgeNoise=sin(vGroundUv.x*7.3+sin(vGroundUv.y*6.1))*.10+sin(vGroundUv.y*19.0+vGroundUv.x*13.1)*.035;
 float roadBlend=1.0-smoothstep(roadHalf-.28,roadHalf+.55+edgeNoise,vRoadDistance);
 vec3 dirt=texture2D(roadMap,vGroundUv/2.2).rgb;
 float track=1.0-.13*exp(-pow((vRoadDistance-roadHalf*.55)/.15,2.0));
 diffuseColor.rgb=mix(diffuseColor.rgb,dirt*track*roadTint,roadBlend);`);s.fragmentShader=s.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor=mix(roughnessFactor,roadRoughness,roadBlend);');s.fragmentShader=s.fragmentShader.replace('vec3 mapN = texture2D( normalMap, vNormalMapUv ).xyz * 2.0 - 1.0;','vec3 mapN = mix(texture2D(normalMap,vNormalMapUv).xyz,texture2D(roadNormal,vGroundUv/2.2).xyz,roadBlend)*2.0-1.0;');};mat.customProgramCacheKey=()=> 'natural-ground-v1';}
export function undergrowth(side){const rng=random(337),grass=buffer(),stones=[];for(let i=0;i<10000;i++){const x=(rng()-.5)*48,z=(rng()-.5)*48,d=side.road.nearest(x,z).distance;if(d<side.road.width/2+.2||side.name==='lake'&&Math.hypot(x/5.8,z/4.5)<1)continue;if(Math.sin(x*.7+Math.cos(z))<-.2&&rng()<.85)continue;const y=side.road.terrain(x,z),h=.05+rng()*.16;for(let j=0;j<3;j++){const a=rng()*6.28,w=.004+rng()*.009,dx=Math.cos(a)*w,dz=Math.sin(a)*w;grass.p.push(x-dx,y,z-dz,x+dx,y,z+dz,x+dx*3,y+h,z+dz*3);grass.n.push(0,1,0,0,1,0,0,1,0);grass.uv.push(0,0,1,0,.5,1);}if(i%17===0)stones.push({x,y,z,s:.06+rng()*.2});}
 const blades=new T.Mesh(finish(grass),new T.MeshStandardMaterial({color:'#727749',roughness:1,side:T.DoubleSide}));blades.receiveShadow=true;side.world.add(blades);const rock=new T.InstancedMesh(new T.DodecahedronGeometry(1,0),new T.MeshStandardMaterial({color:'#8d887b',roughness:.97}),stones.length),o=new T.Object3D;stones.forEach((p,i)=>{o.position.set(p.x,p.y,p.z);o.scale.set(p.s,p.s*.55,p.s*.8);o.rotation.set(p.x,0,p.z);o.updateMatrix();rock.setMatrixAt(i,o.matrix);});rock.castShadow=rock.receiveShadow=true;side.world.add(rock);
}

export function backdrop(side,mat,heightOverride){const g=new T.PlaneGeometry(240,240,90,90);g.rotateX(-Math.PI/2);const p=g.attributes.position,uv=g.attributes.uv;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),d=Math.max(Math.abs(x),Math.abs(z)),rise=Math.max(0,Math.min(1,(d-34)/22));p.setY(i,heightOverride?heightOverride(x,z):side.road.terrain(x,z)-.12+rise*(5+7*Math.sin(x*.049+Math.sin(z*.025))**2+6*Math.cos(z*.063+x*.018)**2));uv.setXY(i,x,z);}const indices=[];for(let i=0;i<g.index.count;i+=3){const a=g.index.getX(i),b=g.index.getX(i+1),c=g.index.getX(i+2);const x=(p.getX(a)+p.getX(b)+p.getX(c))/3,z=(p.getZ(a)+p.getZ(b)+p.getZ(c))/3;if(Math.abs(x)<30&&Math.abs(z)<30)continue;indices.push(a,b,c);}g.setIndex(indices);g.computeVertexNormals();const mesh=new T.Mesh(g,mat);mesh.receiveShadow=true;side.world.add(mesh);return mesh;}
