import {defaults,createTrack,makeRace,stepRace,standings,compareScenario,grip,riderInfo,validateConfig} from './model.mjs';
import {ParkScene} from './scene.mjs';
const $=id=>document.getElementById(id),clock=t=>{const minutes=Math.floor(t/60),sec=(t%60).toFixed(1).padStart(4,'0');return String(minutes).padStart(2,'0')+':'+sec};
let cfg=defaults(),track=createTrack(),race=makeRace(cfg),scene,paused=false,manual=false,pace=1,selected=0,last=0,accumulator=0,uiTimer=0,finishShown=false,audio=null,loaded=false;
const keys=new Set,pointers=new Map,input=()=>({throttle:keys.has('w')||keys.has('arrowup')||[...pointers.values()].includes('throttle')?1:0,brake:keys.has('s')||keys.has('arrowdown')||keys.has(' ')||[...pointers.values()].includes('brake')?1:0,steer:(keys.has('a')||keys.has('arrowleft')||[...pointers.values()].includes('left')?-1:0)+(keys.has('d')||keys.has('arrowright')||[...pointers.values()].includes('right')?1:0)});
function clearInput(){keys.clear();pointers.clear()}
function notice(text){$('notice').textContent=text}
function camera(mode){if(!loaded)return;scene.selected=selected;scene.setCamera(mode);const label={overview:'公园全景',follow:'跟随镜头',helmet:'骑手视角',test:'试验坡近看'}[mode];$('camera-label').textContent=label+(mode==='follow'||mode==='helmet'?' / '+riderInfo[selected].name:'');document.querySelectorAll('[data-camera]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.camera===mode)))}
function setManual(value){manual=value;clearInput();$('takeover').setAttribute('aria-pressed',String(value));$('takeover').textContent=value?'交回自动驾驶':'接管阿岚';$('drive-pad').hidden=!value;$('control-help').textContent=value?'W / ↑ 加速 · S / ↓ / 空格 制动；A D 路内转向，Esc 交回。':'自动巡游与比赛；手动驾驶仍保留道路辅助。';if(value){selected=0;pace=1;$('pace').value='1';camera('helmet');$('world').focus();notice('已接管黄色车手。按住 W 或油门加速；Esc 交回。')}else notice('已交回自动驾驶。')}
function resetRace(message='重新起跑，比赛成绩已清空。'){race=makeRace(cfg);track=createTrack(cfg.lift);accumulator=0;finishShown=false;paused=false;clearInput();$('finish').hidden=true;$('pause').textContent='暂停';$('pause').setAttribute('aria-pressed','false');notice(message);refresh()}
function syncControls(){for(const k of ['lift','wet','surface','skill'])$(k).value=String(cfg[k]);$('lift-value').textContent=(cfg.lift>=0?'+':'')+cfg.lift.toFixed(1)+' m';$('wet-value').textContent=Math.round(cfg.wet*100)+'%';$('skill-value').textContent=cfg.skill}
function configure(patch,preset='custom'){validateConfig(patch);cfg={...cfg,...patch};scene.setConfig(cfg);syncControls();if(manual)setManual(false);document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===preset)));$('comparison-result').hidden=true;resetRace('条件已改变，重新起跑。单圈对照需重新计算。')}
function preset(name){const presets={original:defaults(),hill:{...defaults(),lift:3},rain:{...defaults(),wet:.85,surface:'mud'}};configure(presets[name],name);if(name==='hill')camera('test');else if(name==='rain')camera('follow');else camera('overview')}
function map(){const c=$('minimap'),ctx=c.getContext('2d'),w=c.width,h=c.height,to=p=>({x:w/2+p.x*1.75,y:h/2+p.z*1.4});ctx.clearRect(0,0,w,h);ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();track.points.forEach((p,i)=>{const q=to(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.closePath();ctx.strokeStyle='#82918a';ctx.lineWidth=4;ctx.stroke();ctx.beginPath();for(let s=track.editS-24;s<=track.editS+24;s+=1){const q=to(track.sample(s));s===track.editS-24?ctx.moveTo(q.x,q.y):ctx.lineTo(q.x,q.y)}ctx.strokeStyle='#ffbb55';ctx.lineWidth=4;ctx.stroke();for(const r of race.riders){const q=to(track.sample(r.s));ctx.beginPath();ctx.arc(q.x,q.y,r.id===selected?5:3.4,0,Math.PI*2);ctx.fillStyle=riderInfo[r.id].color;ctx.fill();if(r.id===selected){ctx.strokeStyle='#fff';ctx.lineWidth=1.3;ctx.stroke()}}}
function refresh(){const r=race.riders[selected],p=track.sample(r.s),sorted=standings(race);$('race-time').textContent=clock(race.time);$('speed').textContent=Math.round(r.v*3.6);$('grip').textContent=grip(cfg,track,r.s).toFixed(2);$('grade').textContent=(p.grade*100).toFixed(1)+'%';$('lap-count').textContent=race.status==='finished'?'全部完赛':'第 '+Math.min(r.lap+1,cfg.laps)+' / '+cfg.laps+' 圈';$('race-status').textContent=paused?'已暂停':race.status==='countdown'?'准备起跑':race.status==='finished'?'比赛结束':manual?'阿岚 / 手动驾驶':'自动比赛';$('countdown').textContent=race.status==='countdown'?String(Math.ceil(race.countdown)):'';const reason=race.status==='countdown'?'等待起跑':r.finishTime!==null?'已完成比赛':paused?'已暂停':manual&&selected===0?'你正在驾驶':p.grade>.065?'上坡 · 动力与重力共同作用':r.brake>.12?'弯前减速 · 抓地限制速度':cfg.wet>.4?'湿滑路面 · 降低控弯速度':'沿赛道行驶';$('cause').textContent=riderInfo[selected].name+' / '+reason;$('ranking').innerHTML=sorted.map((v,i)=>'<li class="'+(v.id===selected?'selected':'')+'"><span>'+(i+1)+'</span><i class="rider-dot" style="background:'+riderInfo[v.id].color+'"></i><button data-rider="'+v.id+'" aria-label="观察'+riderInfo[v.id].name+'">'+riderInfo[v.id].name+'</button><span class="rank-value">'+(v.finishTime!==null?clock(v.finishTime):Math.round(v.v*3.6)+' km/h')+'</span></li>').join('');
 $('live-explanation').textContent=cfg.lift!==0?`试验坡${cfg.lift>0?'抬高':'下挖'} ${Math.abs(cfg.lift)} 米，道路与车辆同步采样新高度；坡度改变加速度，前方弯道仍限制目标速度。`:cfg.wet>.05?`湿润 ${Math.round(cfg.wet*100)}%，抓地降低；路面变暗、雨丝和粒子同步改变。点击单圈对照查看同一车手的差异。`:'前方弯道决定目标速度，车手会提前减速。道路、运动和画面读取同一份场景状态。';
 if(race.status==='finished'&&!finishShown){finishShown=true;$('finish').hidden=false;$('finish-results').innerHTML='<ol>'+sorted.map((v,i)=>'<li><b>'+(i+1)+'</b><span style="color:'+riderInfo[v.id].color+'">'+riderInfo[v.id].name+'</span><span>'+clock(v.finishTime)+'</span></li>').join('')+'</ol>';if(manual)setManual(false);notice('三圈比赛已结束，可以重新起跑或改变条件。')}map()}
class EngineAudio{
 constructor(){this.ctx=new AudioContext;this.master=this.ctx.createGain();this.master.gain.value=0;this.master.connect(this.ctx.destination);this.filter=this.ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=600;this.filter.connect(this.master);this.tone=this.ctx.createOscillator();this.tone.type='sawtooth';this.tone.frequency.value=40;this.tone.connect(this.filter);this.tone.start();this.bass=this.ctx.createOscillator();this.bass.type='triangle';this.bassGain=this.ctx.createGain();this.bassGain.gain.value=.35;this.bass.connect(this.bassGain);this.bassGain.connect(this.master);this.bass.start();this.on=false}
 async toggle(){await this.ctx.resume();this.on=!this.on;return this.on}
 update(r,silent){const now=this.ctx.currentTime,level=this.on&&!silent?.018+r.throttle*.013:0;this.master.gain.setTargetAtTime(level,now,.09);this.tone.frequency.setTargetAtTime(35+r.v*8+r.throttle*20,now,.09);this.bass.frequency.setTargetAtTime(24+r.v*3,now,.13);this.filter.frequency.setTargetAtTime(250+r.v*55+r.throttle*160,now,.1)}
}
function frame(t){const dt=Math.min((t-last)/1000||0,.05);last=t;if(loaded&&!document.hidden){const frozen=paused||race.status==='finished';if(!frozen){accumulator+=dt*pace;while(accumulator>=1/60){stepRace(race,1/60,track,cfg,manual?input():null);accumulator-=1/60}}scene.update(dt*pace,race,frozen);audio?.update(race.riders[selected],frozen||race.status==='countdown');uiTimer+=dt;if(uiTimer>.10){refresh();uiTimer=0}}requestAnimationFrame(frame)}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!loaded)return;if(b.dataset.camera)return camera(b.dataset.camera);if(b.dataset.rider){selected=Number(b.dataset.rider);scene.selected=selected;camera(scene.mode);return refresh()}if(b.dataset.preset)return preset(b.dataset.preset);if(b.dataset.demo){const action=b.dataset.demo;$('park').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});if(action==='hill')preset('hill');if(action==='rain')preset('rain');if(action==='race'){preset('original');pace=4;$('pace').value='4'}if(action==='structure'){scene.setView('clay');$('view-mode').value='clay';camera('overview')}return}if(['restart','again'].includes(b.id))return resetRace();if(b.id==='pause'){paused=!paused;clearInput();b.textContent=paused?'继续':'暂停';b.setAttribute('aria-pressed',String(paused));return refresh()}if(b.id==='takeover'){if(race.status==='finished')resetRace();paused=false;$('pause').textContent='暂停';$('pause').setAttribute('aria-pressed','false');return setManual(!manual)}if(b.id==='sound'){try{audio??=new EngineAudio;const on=await audio.toggle();b.textContent=on?'关闭声音':'开启声音';b.setAttribute('aria-pressed',String(on));notice(on?'已开启合成引擎声，随当前观察车手变化。':'声音已关闭。')}catch{notice('当前浏览器无法开启声音，其余操作可以继续。')}return}if(b.id==='compare'){b.disabled=true;b.textContent='正在计算单圈…';try{await new Promise(r=>requestAnimationFrame(r));const result=compareScenario(cfg),delta=result.current.lap-result.baseline.lap;const el=$('comparison-result');el.hidden=false;el.innerHTML='<p>默认干燥 / 原坡：'+result.baseline.lap.toFixed(2)+' 秒</p><p>当前条件：'+result.current.lap.toFixed(2)+' 秒</p><strong>'+(Math.abs(delta)<.005?'圈时相同':(delta>0?'慢 ':'快 ')+Math.abs(delta).toFixed(2)+' 秒')+'</strong><p>试验段抓地 '+result.baseline.testGrip.toFixed(2)+' → '+result.current.testGrip.toFixed(2)+'</p><small>同一黄色车手、相同起点，计算完整单圈；不含 3 秒倒计时。</small>'}catch{notice('单圈计算未完成，请重置参数后再试。')}finally{b.disabled=false;b.innerHTML='计算同车手单圈对照 <span>↗</span>'}}});
document.addEventListener('input',e=>{if(['lift','wet','skill'].includes(e.target.id)){$(e.target.id+'-value').textContent=e.target.id==='lift'?(+e.target.value>=0?'+':'')+(+e.target.value).toFixed(1)+' m':e.target.id==='wet'?Math.round(e.target.value*100)+'%':e.target.value}});
document.addEventListener('change',e=>{if(!loaded)return;if(['lift','wet','skill','surface'].includes(e.target.id))configure({[e.target.id]:e.target.id==='surface'?e.target.value:Number(e.target.value)});if(e.target.id==='pace'){pace=Number(e.target.value);if(manual&&pace!==1){setManual(false);notice('加速演示时已交回自动驾驶。')}}if(e.target.id==='view-mode')scene.setView(e.target.value)});
const drivingKeys=['w','s','a','d','arrowup','arrowdown','arrowleft','arrowright',' '];window.addEventListener('keydown',e=>{if(e.key==='Escape'&&manual){e.preventDefault();setManual(false);return}if(!manual||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;const key=e.key.toLowerCase();if(drivingKeys.includes(key)){e.preventDefault();keys.add(key)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();if(manual)setManual(false);audio?.update(race.riders[selected],true)});document.addEventListener('visibilitychange',()=>{clearInput();last=performance.now();accumulator=0;if(document.hidden){audio?.update(race.riders[selected],true);if(manual)setManual(false)}});
document.querySelectorAll('[data-drive]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(!manual)return;e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.drive)});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>pointers.delete(e.pointerId))});
const controls=[...document.querySelectorAll('.experiment button,.experiment input,.experiment select,.transport button,.transport select')];controls.forEach(o=>o.disabled=true);
try{scene=new ParkScene($('world'),cfg);await scene.ready;loaded=true;controls.forEach(o=>o.disabled=false);$('loading').hidden=true;syncControls();refresh();requestAnimationFrame(frame);$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();paused=true;notice('图形上下文暂时丢失，请刷新页面重新载入场景。');$('loading').hidden=false;$('loading').innerHTML='<strong>场景需要重新载入</strong><button onclick="location.reload()">刷新场景</button>'});window.addEventListener('pagehide',()=>{audio?.ctx.close();scene.dispose()},{once:true})}catch(error){$('loading').innerHTML='<strong>三维场景暂时无法启动</strong><span>需要支持 WebGL 的浏览器，并完整加载本地素材。</span><button onclick="location.reload()">重新加载</button>';$('loading').style.padding='25px';console.error(error);notice('下方原作对比与研究内容仍可阅读。')}
