export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const mix=(a,b,t)=>a+(b-a)*t;
export const wrap=(s,n)=>((s%n)+n)%n;
export const defaults=()=>({lift:0,wet:0,surface:'dirt',skill:70,laps:3});
export const controlPoints=[[-44,28],[-54,12],[-51,-12],[-37,-28],[-8,-30],[9,-22],[33,-29],[51,-17],[52,7],[41,20],[18,18],[10,5],[26,0],[30,-10],[15,-13],[-1,0],[-17,1],[-29,-10],[-37,-3],[-34,13],[-17,20],[1,30],[-18,34]];
function spline(a,b,c,d,t){return .5*((2*b)+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t)}
export function validateConfig(c){if(!c||typeof c!=='object')throw Error('参数格式错误');for(const [k,v]of Object.entries(c)){if(k==='surface'){if(!['dirt','mud','gravel'].includes(v))throw Error('路面无效')}else if(k==='lift'){if(!Number.isFinite(v)||v< -2||v>4)throw Error('抬坡超出范围')}else if(k==='wet'){if(!Number.isFinite(v)||v<0||v>1)throw Error('湿润超出范围')}else if(k==='skill'){if(!Number.isFinite(v)||v<40||v>95)throw Error('能力超出范围')}else if(k==='laps'){if(!Number.isInteger(v)||v<1||v>5)throw Error('圈数无效')}else throw Error('未知参数：'+k)}return c}
export function createTrack(lift=0){
 const points=[],lengths=[0],N=920;for(let i=0;i<=N;i++){const u=i/N*controlPoints.length,j=Math.floor(u)%controlPoints.length,t=u-Math.floor(u),p=[-1,0,1,2].map(k=>controlPoints[wrap(j+k,controlPoints.length)]);const x=spline(...p.map(q=>q[0]),t),z=spline(...p.map(q=>q[1]),t);points.push({x,z});if(i)lengths.push(lengths[i-1]+Math.hypot(x-points[i-1].x,z-points[i-1].z))}
 const length=lengths[N],editS=length*.235,halfWidth=2.7;
 function height(s){const u=wrap(s,length)/length,t=u*Math.PI*2,d=Math.min(Math.abs(u-.235),1-Math.abs(u-.235));return 2.2+.8*Math.sin(t*2-.2)+.55*Math.cos(t*3)+lift*Math.exp(-((d/.03)**2))}
 function point(s){s=wrap(s,length);let lo=0,hi=N;while(hi-lo>1){const mid=(lo+hi)>>1;if(lengths[mid]>s)hi=mid;else lo=mid}const t=(s-lengths[lo])/(lengths[hi]-lengths[lo]);return{x:mix(points[lo].x,points[hi].x,t),y:height(s),z:mix(points[lo].z,points[hi].z,t)}}
 function sample(s,lane=0){const p=point(s),a=point(s-.4),b=point(s+.4),dx=b.x-a.x,dz=b.z-a.z,n=Math.hypot(dx,dz),f={x:dx/n,z:dz/n},c=point(s-1.2),d=point(s+1.2),ax=p.x-c.x,az=p.z-c.z,bx=d.x-p.x,bz=d.z-p.z;const curvature=2*(ax*bz-az*bx)/Math.max(.0001,Math.hypot(ax,az)*Math.hypot(bx,bz)*Math.hypot(d.x-c.x,d.z-c.z));return{...p,x:p.x+f.z*lane,z:p.z-f.x*lane,forward:f,grade:(b.y-a.y)/n,curvature,s:wrap(s,length)}}
 function nearest(x,z){let best=Infinity,s=0;for(let i=0;i<N;i++){const a=points[i],b=points[i+1],dx=b.x-a.x,dz=b.z-a.z,t=clamp(((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz),0,1),dist=(x-a.x-t*dx)**2+(z-a.z-t*dz)**2;if(dist<best){best=dist;s=mix(lengths[i],lengths[i+1],t)}}return{distance:Math.sqrt(best),s,y:height(s)}}
 function terrain(x,z){const n=nearest(x,z),lake=Math.hypot((x+12)/10,(z+15)/7);let h=1.5+2.5*Math.exp(-((x-26)**2/190+(z+19)**2/110))+3*Math.exp(-((x+40)**2/150+(z+22)**2/95))+.32*Math.sin(x*.22)*Math.cos(z*.19);h=mix(.45,h,clamp((lake-.88)/.65,0,1));const t=clamp((n.distance-halfWidth-.05)/5,0,1);return mix(n.y-.08,h,t*t*(3-2*t))}
 function inTest(s){return Math.abs(wrap(s-editS+length/2,length)-length/2)<24}
 return{points,lengths,length,editS,halfWidth,lift,height,point,sample,nearest,terrain,inTest};
}
export function grip(cfg,track,s){return (track.inTest(s)?({dirt:.9,mud:.56,gravel:.7}[cfg.surface]):.9)*(1-cfg.wet*.52)}
export const riderInfo=[{name:'阿岚',color:'#ffbd3f',style:'均衡',pace:1},{name:'小野',color:'#f0654c',style:'进取',pace:1.04},{name:'青禾',color:'#48c5c1',style:'稳健',pace:.97},{name:'北川',color:'#a6adff',style:'流畅',pace:1.015}];
export function makeRace(cfg=defaults()){validateConfig(cfg);return{status:'countdown',countdown:3,time:0,riders:riderInfo.map((_,id)=>({id,distance:-id*3,s:-id*3,v:0,lane:(id-1.5),roll:0,pitch:0,lap:0,lapStart:null,bestLap:null,lastLap:null,finishTime:null,throttle:0,brake:0,target:0,mu:.9,grade:0})),events:[],laps:cfg.laps}}
export function targets(track,r,cfg){const skill=(r.id===0?cfg.skill:70)/100,mu=grip(cfg,track,r.s);let bend=0;for(let d=0;d<=16;d+=2)bend=Math.max(bend,Math.abs(track.sample(r.s+d).curvature));const corner=Math.sqrt(mu*9.81*(.54+skill*.35)/Math.max(.012,bend));const cruise=(10.5+skill*2.5)*riderInfo[r.id].pace;let uphill=0;for(let d=0;d<=10;d+=2)uphill=Math.max(uphill,track.sample(r.s+d).grade);const hill=cruise/(1+uphill*5);return{target:Math.min(cruise,corner,hill),mu,skill}}
export function stepRider(r,dt,track,cfg,manual=null){if(r.finishTime!==null)return;const p=track.sample(r.s),t=targets(track,r,cfg);r.target=t.target;r.mu=t.mu;r.grade=p.grade;const throttle=manual?clamp(manual.throttle||0,0,1):clamp((t.target-r.v)*1.2,0,1),brake=manual?clamp(manual.brake||0,0,1):clamp((r.v-t.target)*.7,0,1);const a=throttle*(3.8+t.skill*1.5)-brake*t.mu*9.81-.18-.011*r.v*r.v-9.81*Math.sin(Math.atan(p.grade));r.v=clamp(r.v+a*dt,0,15);r.distance+=r.v*dt;r.s=wrap(r.distance,track.length);r.throttle=throttle;r.brake=brake;const desired=manual?clamp(r.lane+(manual.steer||0)*r.v*.22*dt,-1.65,1.65):(r.id-1.5)+.08*Math.sin(r.s*.12+r.id);r.lane=manual?desired:mix(r.lane,desired,1-Math.exp(-dt*2));r.roll=mix(r.roll,clamp(-p.curvature*r.v*r.v*.034,-.52,.52),1-Math.exp(-dt*7));r.pitch=mix(r.pitch,Math.atan(p.grade)+a*.016,1-Math.exp(-dt*7))}
export function stepRace(race,dt,track,cfg,input=null){if(race.status==='finished')return;if(race.status==='countdown'){race.countdown=Math.max(0,race.countdown-dt);if(race.countdown===0)race.status='running';return}race.time+=dt;for(const r of race.riders){if(r.finishTime!==null)continue;const before=r.distance;stepRider(r,dt,track,cfg,r.id===0?input:null);if(r.lapStart===null&&r.distance>=0)r.lapStart=race.time;if(r.distance>=track.length*(r.lap+1)){const frac=clamp((track.length*(r.lap+1)-before)/Math.max(.0001,r.distance-before),0,1),cross=race.time-dt+frac*dt;r.lap++;r.lastLap=cross-(r.lapStart??0);r.bestLap=r.bestLap===null?r.lastLap:Math.min(r.bestLap,r.lastLap);r.lapStart=cross;if(r.lap>=race.laps){r.finishTime=cross;r.distance=track.length*race.laps;r.s=0;r.v=0}}}if(race.riders.every(r=>r.finishTime!==null))race.status='finished'}
export function standings(race){return [...race.riders].sort((a,b)=>a.finishTime!==null&&b.finishTime!==null?a.finishTime-b.finishTime:a.finishTime!==null?-1:b.finishTime!==null?1:b.distance-a.distance)}
export function compareScenario(cfg){validateConfig(cfg);function run(c){const track=createTrack(c.lift),race=makeRace({...c,laps:1});race.status='running';let steps=0,maxGrade=0;for(let s=0;s<track.length;s+=1)maxGrade=Math.max(maxGrade,Math.abs(track.sample(s).grade));while(race.riders[0].finishTime===null&&steps++<24000)stepRace(race,1/60,track,c);if(race.riders[0].finishTime===null)throw Error('单圈计算未完成');return{lap:race.riders[0].finishTime,maxGrade:maxGrade*100,testGrip:grip(c,track,track.editS),targetKmh:targets(track,{id:0,s:track.editS,v:0},c).target*3.6}}return{baseline:run(defaults()),current:run(cfg)}}
