const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
// Forward is +Z: the rider's right is -X, so positive model yaw turns left.
export function readRideInput(keys,pointers){const held=s=>[...pointers.values()].includes(s);return{throttle:keys.has('w')||keys.has('arrowup')||held('throttle')?1:0,brake:keys.has('s')||keys.has('arrowdown')||keys.has(' ')||held('brake')?1:0,steer:(keys.has('a')||keys.has('arrowleft')||held('left')?1:0)-(keys.has('d')||keys.has('arrowright')||held('right')?1:0)}}
export const angle=a=>Math.atan2(Math.sin(a),Math.cos(a));
export const length=70+Math.PI*16,roadWidth=6;
export function road(s,lane=0){s=clamp(s,0,length);let x,z,heading;if(s<35){x=0;z=s-35;heading=0}else if(s<35+Math.PI*16){const a=(s-35)/16;x=16-16*Math.cos(a);z=16*Math.sin(a);heading=a}else{x=32;z=-(s-35-Math.PI*16);heading=Math.PI}return{x:x+Math.cos(heading)*lane,z:z-Math.sin(heading)*lane,heading,s}}
export function nearest(x,z){let s;if(z>=0){const a=clamp(Math.atan2(z,16-x),0,Math.PI);s=35+16*a}else s=x<16?clamp(z+35,0,35):clamp(35+Math.PI*16-z,35+Math.PI*16,length);const p=road(s),dx=x-p.x,dz=z-p.z,lane=dx*Math.cos(p.heading)-dz*Math.sin(p.heading);return{...p,lane,distance:Math.hypot(dx,dz)}}
export function surfaceAt(x,z){const p=nearest(x,z),mud=p.s>36&&p.s<84&&p.lane>1.2&&p.distance<roadWidth;return{...p,name:p.distance>roadWidth?'草地缓冲':mud?'内线泥地':'外线硬土',mu:p.distance>roadWidth?.28:mud?.45:.94,mud}}
export const gates=[22,43,60,79,101,length-3];
export function newRide(){return{x:0,z:-32,heading:0,velocityHeading:0,speed:0,steer:0,yaw:0,roll:0,pitch:0,time:0,status:'ready',gate:0,penalty:0,contacts:0,contactCooldown:0,offroadTime:0,mudTime:0,hardTime:0,distance:0,slip:0,started:false,feedback:'按 W / ↑ 或油门开始。先直线加速，入弯前制动。'}}
export function recover(r){const s=r.gate?gates[r.gate-1]+.6:3,p=road(s);Object.assign(r,{x:p.x,z:p.z,heading:p.heading,velocityHeading:p.heading,speed:0,steer:0,yaw:0,roll:0,slip:0});if(r.started)r.penalty+=3;r.feedback='已回到最近通过的检查点；计时开始后救援加 3 秒。'}
export function stepRide(r,dt,input={}){if(!Number.isFinite(dt)||dt<=0||dt>.05)throw Error('固定时间步须在 0～0.05 秒');if(r.status==='finished')return;const throttle=clamp(input.throttle||0,0,1),brake=clamp(input.brake||0,0,1),steer=clamp(input.steer||0,-1,1);if(r.status==='ready'&&throttle>.01){r.status='running';r.started=true}if(!r.started)return;r.time+=dt;r.contactCooldown=Math.max(0,r.contactCooldown-dt);let surface=surfaceAt(r.x,r.z);r.steer+=(steer-r.steer)*(1-Math.exp(-dt*7));const maxWheel=.48/(1+r.speed*.055),desiredYaw=r.speed/1.9*Math.tan(r.steer*maxWheel),traction=surface.mu*9.81,turnBudget=traction*Math.sqrt(Math.max(.2,1-brake*brake*.65));r.yaw+=(clamp(desiredYaw,-2.2,2.2)-r.yaw)*(1-Math.exp(-dt*8));r.heading=angle(r.heading+r.yaw*dt);const slip=angle(r.heading-r.velocityHeading),maxVelocityTurn=turnBudget/Math.max(r.speed,1);r.velocityHeading=angle(r.velocityHeading+clamp(slip,-maxVelocityTurn*dt,maxVelocityTurn*dt));r.slip=angle(r.heading-r.velocityHeading);const drag=surface.distance>roadWidth?1.8:.18,accel=throttle*5.2*Math.max(.15,Math.cos(r.slip))-brake*traction-drag-.012*r.speed*r.speed-Math.abs(r.slip)*1.1;r.speed=clamp(r.speed+accel*dt,0,18);const before={x:r.x,z:r.z};r.x+=Math.sin(r.velocityHeading)*r.speed*dt;r.z+=Math.cos(r.velocityHeading)*r.speed*dt;r.distance+=r.speed*dt;r.roll+=(clamp(-r.yaw*r.speed/9.81,-.72,.72)-r.roll)*(1-Math.exp(-dt*8));r.pitch+=(accel*.022-r.pitch)*(1-Math.exp(-dt*8));surface=surfaceAt(r.x,r.z);if(surface.distance>roadWidth)r.offroadTime+=dt;else if(surface.mud)r.mudTime+=dt;else r.hardTime+=dt;
 // The grass is drivable; the continuous outer barrier resolves penetration.
 if(surface.distance>9){const center=road(surface.s),dx=r.x-center.x,dz=r.z-center.z,d=Math.hypot(dx,dz),nx=dx/d,nz=dz/d;r.x=center.x+nx*8.95;r.z=center.z+nz*8.95;const vx=Math.sin(r.velocityHeading),vz=Math.cos(r.velocityHeading),out=vx*nx+vz*nz;if(out>0){const tx=vx-out*nx,tz=vz-out*nz;r.velocityHeading=Math.atan2(tx,tz);r.heading=r.velocityHeading;r.speed*=.32;r.yaw=0}if(r.contactCooldown===0){r.contacts++;r.penalty+=2;r.contactCooldown=1.2}r.feedback='碰到缓冲护栏：速度损失，本次加 2 秒。'}else r.feedback=surface.distance>roadWidth?'驶入草地：滚动阻力增加，尽快回到赛道。':Math.abs(r.slip)>.15?'抓地不足，车头方向与行驶方向出现偏差。':surface.mud?'内线泥地：路程较短，入弯前需要更多减速。':r.speed>10&&surface.s<35?'即将入弯：松油门、提前制动，再转向。':'外线硬土：路程较长，但抓地更好。';
 if(r.gate<gates.length){const g=road(gates[r.gate]),fx=Math.sin(g.heading),fz=Math.cos(g.heading),a=(before.x-g.x)*fx+(before.z-g.z)*fz,b=(r.x-g.x)*fx+(r.z-g.z)*fz,lateral=(r.x-g.x)*Math.cos(g.heading)-(r.z-g.z)*Math.sin(g.heading);if(a<=0&&b>0&&Math.abs(lateral)<=roadWidth+.4){r.gate++;if(r.gate===gates.length){r.status='finished';r.speed=0;r.feedback='完成发卡弯！比较用时、泥地停留和失误，再换一条线试试。'}}}
 return surface;
}
export function guideInput(r,line='outer'){const p=nearest(r.x,r.z),lane=p.s>27&&p.s<88?(line==='inner'?3:-3):0,lookahead=clamp(4+r.speed*.6,5,11),target=road(p.s+lookahead,lane),dx=target.x-r.x,dz=target.z-r.z,alpha=angle(Math.atan2(dx,dz)-r.heading),curvature=2*Math.sin(alpha)/Math.max(3,Math.hypot(dx,dz)),wheel=Math.atan(1.9*curvature),maxWheel=.48/(1+r.speed*.055),limit=p.s>20&&p.s<90?(line==='inner'?6:9):11;return{steer:clamp(wheel/maxWheel,-1,1),throttle:clamp((limit-r.speed)*1.5,0,1),brake:clamp((r.speed-limit)*.6,0,1)}}
