import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {makeBike} from './scene.mjs';
import {road,length,gates,newRide,stepRide,guideInput,surfaceAt,recover,readRideInput} from './ride-model.mjs';
const $=id=>document.getElementById(id),V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
let state=newRide(),mode='manual',view='follow',paused=false,last=0,acc=0,tick=0,recorded=false,ready=false;
const history=[],keys=new Set,pointers=new Map;
function readInput(){return readRideInput(keys,pointers)}
const canvas=$('ride-world'),scene=new T.Scene;scene.background=new T.Color('#90aaa7');scene.fog=new T.FogExp2('#90aaa7',.0025);
let renderer,camera,orbit,bike,wheelAngle=0;const follow=V(),look=V(),mapTextures=[];
function add(g,m,p,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;p.add(o);return o}
function label(text,color='#f1e5c8'){const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#183c32';ctx.fillRect(0,0,1024,128);ctx.fillStyle=color;ctx.font='bold 65px "Microsoft YaHei", sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,68,980);const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(10,1.25),new T.MeshBasicMaterial({map,side:T.DoubleSide}))}
async function init(){renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;camera=new T.PerspectiveCamera(52,1,.1,350);orbit=new OrbitControls(camera,canvas);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.48;orbit.minDistance=10;orbit.maxDistance=135;orbit.enabled=false;const sun=new T.DirectionalLight('#ffe4b9',3);sun.position.set(-35,65,-25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-55,right:55,top:60,bottom:-60,near:1,far:150});sun.shadow.normalBias=.055;scene.add(sun,new T.HemisphereLight('#d9ebeb','#6c7452',2));
 const loader=new T.TextureLoader;for(const id of ['brown_mud_dry','aerial_grass_rock']){const map=await loader.loadAsync(`../assets/textures/${id}_diff_1k.jpg`);map.wrapS=map.wrapT=T.RepeatWrapping;map.colorSpace=T.SRGBColorSpace;mapTextures.push(map)}const soil=new T.MeshStandardMaterial({map:mapTextures[0],color:'#c9af80',roughness:.97}),mud=new T.MeshStandardMaterial({map:mapTextures[0],color:'#8a6544',roughness:.5}),grass=new T.MeshStandardMaterial({map:mapTextures[1],color:'#93ab73',roughness:1}),dark=new T.MeshStandardMaterial({color:'#384e44'}),cream=new T.MeshStandardMaterial({color:'#eadfb5'}),orange=new T.MeshStandardMaterial({color:'#e1a24a'});
 const ground=new T.PlaneGeometry(78,95);ground.rotateX(-Math.PI/2);for(let i=0;i<ground.attributes.uv.count;i++){const p=ground.attributes.position;ground.attributes.uv.setXY(i,p.getX(i)/9,p.getZ(i)/9)}add(ground,grass,scene,16,-.035,-8).castShadow=false;
 function strip(a,b,start,end,mat,y=.015){const verts=[],uv=[],idx=[];const n=Math.ceil((end-start)/.4);for(let i=0;i<=n;i++){const s=start+(end-start)*i/n;for(const l of [a,b]){const p=road(s,l);verts.push(p.x,y,p.z);uv.push(l/4,s/4)}if(i<n){const j=i*2;idx.push(j,j+2,j+1,j+1,j+2,j+3)}}const g=new T.BufferGeometry;g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const m=add(g,mat,scene);m.castShadow=false;return m}
 strip(-6,6,0,length,soil);strip(1.2,6,36,84,mud,.025);
 const tireGeo=new T.TorusGeometry(.45,.19,6,12);tireGeo.rotateX(Math.PI/2);const marks=[];for(let s=0;s<length;s+=1.15)for(const lane of [-9.1,9.1])marks.push(road(s,lane));for(const s of [0,length])for(let a=0;a<Math.PI;a+=.12){const p=road(s),sign=s===0?-1:1;marks.push({x:p.x+Math.cos(a)*9.1,z:p.z+sign*Math.sin(a)*9.1*Math.cos(p.heading)})}const tires=new T.InstancedMesh(tireGeo,dark,marks.length),dummy=new T.Object3D;marks.forEach((p,i)=>{dummy.position.set(p.x,.19,p.z);dummy.updateMatrix();tires.setMatrixAt(i,dummy.matrix);tires.setColorAt(i,new T.Color(i%8<4?'#e0d5b1':'#35483e'))});tires.castShadow=true;scene.add(tires);
 gates.forEach((s,i)=>{const p=road(s),g=new T.Group;g.position.set(p.x,0,p.z);g.rotation.y=p.heading;scene.add(g);for(const x of [-6.5,6.5]){add(new T.CylinderGeometry(.065,.065,2.2,6),dark,g,x,1.1,0);add(new T.BoxGeometry(.65,.8,.03),i===gates.length-1?cream:orange,g,x+.3,1.7,0)}const line=add(new T.BoxGeometry(12,.014,.11),cream,g,0,.032,0);if(i===gates.length-1){const l=label('FINISH / 终点');l.position.set(0,4.3,0);g.add(l);for(const x of [-6.5,6.5])add(new T.CylinderGeometry(.085,.085,4.9,7),dark,g,x,2.4,0)}else line.material=new T.MeshStandardMaterial({color:'#e0bd64',transparent:true,opacity:.4})});
 const outer=label('外线硬土 / 更稳','#d8edc5');outer.position.set(-5,2.6,22);scene.add(outer);const inner=label('内线泥地 / 更短','#fac381');inner.position.set(16,2.6,2);scene.add(inner);
 const bark=new T.MeshStandardMaterial({color:'#715d42'}),leaf=new T.MeshStandardMaterial({color:'#3e6748'});for(let i=0;i<70;i++){const x=-16+(i%14)*5,z=-45+Math.floor(i/14)*18;if(surfaceAt(x,z).distance<12)continue;const trunk=add(new T.CylinderGeometry(.11,.2,2.8,6),bark,scene,x,1.4,z);for(let j=0;j<3;j++)add(new T.ConeGeometry(1.6-j*.35,2.3,8),leaf,scene,x,2.2+j*.9,z);trunk.castShadow=true}
 bike=makeBike(scene,'#ffbd3f');bike.g.scale.setScalar(1.08);ready=true;resize();setView('follow');$('ride-loading').hidden=true;updateUI();requestAnimationFrame(frame)}
function resize(){if(!renderer)return;const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
const observer=new ResizeObserver(resize);observer.observe(canvas);
function setView(v){view=v;orbit.enabled=v==='overview';$('follow-view').setAttribute('aria-pressed',String(v==='follow'));$('overview-view').setAttribute('aria-pressed',String(v==='overview'));if(v==='overview'){camera.position.set(65,80,-70);orbit.target.set(16,0,-7);orbit.update()}else{follow.set(state.x-Math.sin(state.heading)*8,5.6,state.z-Math.cos(state.heading)*8);look.set(state.x+Math.sin(state.heading)*5,1.2,state.z+Math.cos(state.heading)*5);camera.position.copy(follow);camera.lookAt(look)}}
function restart(nextMode=mode){mode=nextMode;state=newRide();paused=false;acc=0;recorded=false;keys.clear();pointers.clear();$('ride-finish').hidden=true;$('ride-pause').textContent='暂停';$('ride-mode').textContent=mode==='manual'?'自己驾驶':mode==='inner'?'内线示范 / 可随时接管':'外线示范 / 可随时接管';setView('follow');updateUI();canvas.parentElement.scrollIntoView({block:'start',behavior:'smooth'});if(mode==='manual')canvas.focus({preventScroll:true})}
function updateUI(){const s=surfaceAt(state.x,state.z);$('ride-time').textContent=(state.time+state.penalty).toFixed(2)+' s';$('ride-speed').textContent=Math.round(state.speed*3.6);$('ride-feedback').textContent=paused?'已暂停。点击继续，或按 P。':state.feedback;$('ride-surface').textContent=s.name;$('ride-gates').textContent=state.gate+' / '+gates.length;$('ride-slip').textContent=Math.round(Math.abs(state.slip)*180/Math.PI)+'°';$('ride-penalty').textContent=state.penalty.toFixed(0)+' s';if(state.status==='finished'&&!recorded){recorded=true;const name=mode==='manual'?'自己驾驶':mode==='inner'?'内线示范':'外线示范';history.unshift({name,...state});$('ride-finish').hidden=false;$('ride-result').textContent=`${name}：${(state.time+state.penalty).toFixed(2)} 秒，行驶 ${state.distance.toFixed(1)} 米；含 ${state.penalty} 秒罚时。`;$('ride-history').innerHTML=history.slice(0,8).map(r=>`<tr><td>${r.name}</td><td>${(r.time+r.penalty).toFixed(2)} s</td><td>${r.distance.toFixed(1)} m</td><td>${r.mudTime.toFixed(1)} s</td><td>${r.offroadTime.toFixed(1)} s</td><td>${r.contacts} 次 / ${r.penalty} s</td></tr>`).join('')}}
function frame(t){const dt=Math.min((t-last)/1000||0,.05);last=t;if(!document.hidden){if(!paused){acc+=dt;while(acc>=1/120){stepRide(state,1/120,mode==='manual'?readInput():guideInput(state,mode));acc-=1/120}}bike.g.position.set(state.x,.02,state.z);bike.g.rotation.y=state.heading;bike.body.rotation.z=state.roll;bike.body.rotation.x=-state.pitch;if(!paused)wheelAngle+=state.speed*dt/.49;bike.wheels.forEach(w=>w.spin.rotation.x=wheelAngle);if(view==='follow'){const fx=Math.sin(state.heading),fz=Math.cos(state.heading);follow.lerp(V(state.x-fx*8,5.6,state.z-fz*8),1-Math.exp(-dt*5));look.lerp(V(state.x+fx*5,1.3,state.z+fz*5),1-Math.exp(-dt*7));camera.position.copy(follow);camera.lookAt(look)}else orbit.update();renderer.render(scene,camera);tick+=dt;if(tick>.08){updateUI();tick=0}}requestAnimationFrame(frame)}
function togglePause(){paused=!paused;keys.clear();pointers.clear();$('ride-pause').textContent=paused?'继续':'暂停';updateUI()}
document.addEventListener('click',e=>{if(!ready)return;const id=e.target.closest('button')?.id;if(id==='demo-inner')restart('inner');if(id==='demo-outer')restart('outer');if(['drive-self','finish-retry'].includes(id))restart('manual');if(id==='ride-retry')restart();if(id==='ride-recover'){recover(state);updateUI()}if(id==='ride-pause')togglePause();if(id==='follow-view')setView('follow');if(id==='overview-view')setView('overview')});
window.addEventListener('keydown',e=>{if(!ready||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(k==='p'){e.preventDefault();if(!e.repeat)togglePause();return}if(k==='r'){e.preventDefault();if(!e.repeat){recover(state);updateUI()}return}if(['w','s','a','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)){if(e.target.tagName==='BUTTON'&&k===' ')return;e.preventDefault();if(mode!=='manual'){mode='manual';$('ride-mode').textContent='自己驾驶 / 从示范接管'}keys.add(k)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
for(const b of document.querySelectorAll('[data-input]')){b.addEventListener('pointerdown',e=>{if(!ready)return;e.preventDefault();if(mode!=='manual'){mode='manual';$('ride-mode').textContent='自己驾驶 / 从示范接管'}b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.input)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>pointers.delete(e.pointerId))}
function loseFocus(){keys.clear();pointers.clear();if(state.status==='running'&&!paused)togglePause();last=performance.now();acc=0}window.addEventListener('blur',loseFocus);document.addEventListener('visibilitychange',()=>{if(document.hidden)loseFocus();else last=performance.now()});window.addEventListener('pagehide',()=>{observer.disconnect();orbit?.dispose();renderer?.dispose()},{once:true});
init().catch(e=>{$('ride-loading').innerHTML='<strong>驾驶场暂时无法启动</strong><p>请确认浏览器支持 WebGL，或刷新重试。</p><button onclick="location.reload()">重新加载</button>';console.error(e)});
