import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {createTrack,clamp,mix,riderInfo} from './model.mjs';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
function random(seed=912){return()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296)}
function mesh(g,m,parent,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function box(m,parent,s,p){return mesh(new T.BoxGeometry(...s),m,parent,...p)}
function beam(m,parent,a,b,r=.06){const av=V(...a),bv=V(...b),o=mesh(new T.CylinderGeometry(r,r,av.distanceTo(bv),7),m,parent);o.position.copy(av).add(bv).multiplyScalar(.5);o.quaternion.setFromUnitVectors(V(0,1,0),bv.sub(av).normalize());return o}
function merge(geos){const pos=[],norm=[];for(const raw of geos){const g=raw.index?raw.toNonIndexed():raw;pos.push(...g.attributes.position.array);norm.push(...g.attributes.normal.array);if(g!==raw)g.dispose();raw.dispose()}const g=new T.BufferGeometry;g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('normal',new T.Float32BufferAttribute(norm,3));return g}
function sign(text,w,h,fg='#ece8d7',bg='#1d3431'){const c=document.createElement('canvas');c.width=1024;c.height=Math.round(1024*h/w);const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,c.width,c.height);x.fillStyle=fg;x.font=`700 ${Math.round(c.height*.53)}px "Segoe UI","Microsoft YaHei",sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillText(text,c.width/2,c.height/2,c.width*.94);const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map,side:T.DoubleSide}))}
export function makeBike(parent,color){
 const g=new T.Group,body=new T.Group;parent.add(g);g.add(body);const dark=new T.MeshStandardMaterial({color:'#172428',roughness:.75}),steel=new T.MeshStandardMaterial({color:'#abb9b5',metalness:.72,roughness:.34}),paint=new T.MeshStandardMaterial({color,roughness:.43}),white=new T.MeshStandardMaterial({color:'#f0ecdc',roughness:.75}),visor=new T.MeshStandardMaterial({color:'#172d36',roughness:.18,metalness:.4});
 const wheels=[];for(const z of [-.93,1.03]){const pivot=new T.Group;pivot.position.set(0,.48,z);g.add(pivot);const spin=new T.Group;pivot.add(spin);const tire=mesh(new T.TorusGeometry(.39,.12,8,20),dark,spin);tire.rotation.y=Math.PI/2;const rim=mesh(new T.TorusGeometry(.25,.035,5,16),steel,spin);rim.rotation.y=Math.PI/2;const hub=mesh(new T.CylinderGeometry(.065,.065,.31,8),steel,spin);hub.rotation.z=Math.PI/2;for(let j=0;j<8;j++){const a=j/8*Math.PI*2;beam(steel,spin,[0,0,0],[0,Math.sin(a)*.28,Math.cos(a)*.28],.011)}for(let j=0;j<16;j++){const a=j/16*Math.PI*2,t=box(dark,spin,[.25,.08,.10],[0,Math.sin(a)*.485,Math.cos(a)*.485]);t.rotation.x=-a}wheels.push({pivot,spin})}
 for(const x of [-.13,.13]){beam(steel,body,[x,.52,-.93],[x,.8,.1],.05);beam(steel,body,[x,.8,.1],[x,1.22,.56],.06);beam(steel,body,[x,1.22,.56],[x,.53,1.03],.044);beam(steel,body,[x,.82,-.45],[x,1.22,.56],.045)}
 const tank=mesh(new T.CapsuleGeometry(.25,.35,4,8),paint,body,0,1.03,.12);tank.rotation.x=Math.PI/2;box(dark,body,[.40,.14,.90],[0,1.2,-.28]);box(paint,body,[.45,.10,.7],[0,.88,-.96]);box(paint,body,[.43,.09,.85],[0,.96,1.02]);mesh(new T.CylinderGeometry(.21,.23,.45,8),dark,body,0,.64,-.03);box(steel,body,[.48,.08,.40],[0,.47,-.02]);beam(steel,body,[.24,.64,-.05],[.32,.98,-.9],.065);box(white,body,[.43,.42,.10],[0,1.22,.78]);beam(steel,body,[-.49,1.48,.55],[.49,1.48,.55],.033);for(const x of [-.4,.4])beam(dark,body,[x-.08,1.48,.55],[x+.08,1.48,.55],.045);
 // Two wheels and a seated rider are articulated 3D geometry, not a sprite.
 const torso=mesh(new T.CapsuleGeometry(.22,.35,4,8),paint,body,0,1.63,-.15);torso.rotation.x=.25;const helmet=mesh(new T.SphereGeometry(.27,14,12),paint,body,0,2.12,.08);helmet.scale.set(1,1.03,1.12);const glass=mesh(new T.SphereGeometry(.258,12,8,0,Math.PI*2,Math.PI*.28,Math.PI*.3),visor,body,0,2.14,.10);glass.scale.set(1,1,1.17);box(white,body,[.45,.04,.40],[0,2.26,.29]);for(const x of [-1,1]){beam(paint,body,[x*.23,1.78,-.03],[x*.38,1.60,.22],.09);beam(paint,body,[x*.38,1.60,.22],[x*.40,1.48,.55],.078);mesh(new T.SphereGeometry(.085,8,8),dark,body,x*.4,1.48,.55);beam(dark,body,[x*.16,1.30,-.40],[x*.32,.99,.03],.12);beam(dark,body,[x*.32,.99,.03],[x*.30,.56,-.32],.095);box(dark,body,[.20,.17,.40],[x*.3,.54,-.16])}
 return{g,body,wheels};
}
export class ParkScene{
 constructor(canvas,cfg){this.canvas=canvas;this.cfg={...cfg};this.track=createTrack(cfg.lift);this.mode='overview';this.view='full';this.selected=0;this.time=0;this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;
 this.scene=new T.Scene;this.scene.background=new T.Color('#9fb8bd');this.scene.fog=new T.FogExp2('#9fb8bd',.0018);this.camera=new T.PerspectiveCamera(43,1,.12,600);this.camera.position.set(93,90,111);this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(0,1,2);this.controls.enableDamping=true;this.controls.minDistance=12;this.controls.maxDistance=230;this.controls.maxPolarAngle=Math.PI*.475;
 this.sun=new T.DirectionalLight('#ffe0ab',3.3);this.sun.position.set(-45,80,35);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-78,right:78,top:65,bottom:-65,near:1,far:170});this.sun.shadow.normalBias=.075;this.sun.shadow.bias=-.00015;this.scene.add(this.sun);this.hemi=new T.HemisphereLight('#c8e4ee','#5d6448',2);this.scene.add(this.hemi);
 this.world=new T.Group;this.scene.add(this.world);this.bikes=riderInfo.map(r=>makeBike(this.scene,r.color));this.originalMaterials=new Map;this.follow=V();this.aim=V();this.textures={};this.geometryStats={};this.ready=this.load();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.resize();
 }
 async load(){const loader=new T.TextureLoader;await Promise.all(['brown_mud_dry','aerial_grass_rock'].flatMap(id=>['diff','nor_gl','rough'].map(async ch=>{const texture=await loader.loadAsync(`../assets/textures/${id}_${ch}_1k.jpg`);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());if(ch==='diff')texture.colorSpace=T.SRGBColorSpace;this.textures[id+'_'+ch]=texture})));
 const material=(id,color)=>new T.MeshStandardMaterial({map:this.textures[id+'_diff'],normalMap:this.textures[id+'_nor_gl'],roughnessMap:this.textures[id+'_rough'],color,roughness:.95,normalScale:new T.Vector2(.7,.7)});this.mat={ground:material('aerial_grass_rock','#aab08a'),road:material('brown_mud_dry','#bf9262'),mud:material('brown_mud_dry','#8e7458'),base:new T.MeshStandardMaterial({color:'#564f40',roughness:1}),stone:material('aerial_grass_rock','#939488'),wood:new T.MeshStandardMaterial({color:'#81735c',roughness:.91}),leaf:new T.MeshStandardMaterial({color:'#3e6649',roughness:.94}),bark:new T.MeshStandardMaterial({color:'#6a5843',roughness:1}),white:new T.MeshStandardMaterial({color:'#e6e3d1',roughness:.8}),rubber:new T.MeshStandardMaterial({color:'#303c39',roughness:.95}),orange:new T.MeshStandardMaterial({color:'#eb8a40',roughness:.72}),metal:new T.MeshStandardMaterial({color:'#485e60',metalness:.35,roughness:.6}),grass:new T.MeshStandardMaterial({color:'#7c9451',roughness:1,side:T.DoubleSide})};this.build();this.makeWeather();this.setConfig(this.cfg);this.setCamera('overview');return this}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();if(this.mode==='overview')this.overview()}
 overview(){const scale=Math.max(1,1.14/this.camera.aspect);this.camera.position.set(93*scale,90*scale,111*scale);this.controls.target.set(0,1,2);this.controls.update()}
 clear(){const geometries=new Set,materials=new Set;this.world.traverse(o=>{if(o.geometry&&o.material){geometries.add(o.geometry);const original=this.originalMaterials.get(o)||o.material;const ms=Array.isArray(original)?original:[original];for(const m of ms)if(!Object.values(this.mat).includes(m)&&m!==this.clay&&m!==this.wire)materials.add(m)}});for(const g of geometries)g.dispose();for(const m of materials){if(m.map&&!Object.values(this.textures).includes(m.map))m.map.dispose();m.dispose()}this.world.clear();this.originalMaterials.clear()}
 build(){if(this.world.children.length)this.clear();const t=this.track=createTrack(this.cfg.lift),m=this.mat,rnd=random(1007);box(m.base,this.world,[133,2.4,101],[0,-1.07,0]);const ground=new T.PlaneGeometry(132,100,132,100);ground.rotateX(-Math.PI/2);const p=ground.attributes.position,uv=ground.attributes.uv;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),edge=clamp(Math.min(66-Math.abs(x),50-Math.abs(z))/4,0,1),y=mix(.15,t.terrain(x,z),edge);p.setY(i,y);uv.setXY(i,x/11,z/11)}ground.computeVertexNormals();this.ground=mesh(ground,m.ground,this.world);this.ground.castShadow=false;
 const makeRoad=(half,mat,offset,onlyTest=false)=>{const pos=[],uvs=[],idx=[];let count=0;for(let i=0;i<920;i++){const s=i/920*t.length,s2=(i+1)/920*t.length;if(onlyTest&&!t.inTest((s+s2)/2))continue;for(const [d,l]of [[s,-half],[s,half],[s2,-half],[s2,half]]){const q=t.sample(d,l);pos.push(q.x,q.y+offset,q.z);uvs.push(l/3,d/4)}idx.push(count,count+2,count+1,count+1,count+2,count+3);count+=4}const g=new T.BufferGeometry;g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));g.setIndex(idx);g.computeVertexNormals();const o=mesh(g,mat,this.world);o.castShadow=false;return o};
 this.shoulder=makeRoad(3.08,m.mud,-.035);this.road=makeRoad(t.halfWidth,m.road,.025);this.testRoad=makeRoad(t.halfWidth-.02,m.mud,.042,true);this.testRoad.visible=this.cfg.surface!=='dirt';
 // Instanced tire barriers follow the same road data on both edges.
 const tireGeo=new T.TorusGeometry(.37,.14,6,12);tireGeo.rotateX(Math.PI/2);const marks=[];for(let s=0;s<t.length;s+=1.9)for(const lane of [-3.26,3.26]){const q=t.sample(s,lane);marks.push({q,s})}const tires=new T.InstancedMesh(tireGeo,m.rubber,marks.length),dummy=new T.Object3D;marks.forEach(({q},i)=>{dummy.position.set(q.x,q.y+.15,q.z);dummy.rotation.set(.035*Math.sin(i),i*.6,.03*Math.cos(i));dummy.scale.setScalar(1);dummy.updateMatrix();tires.setMatrixAt(i,dummy.matrix);tires.setColorAt(i,new T.Color(i%7<3?'#d4d2bb':'#323d37'))});tires.castShadow=true;tires.receiveShadow=true;this.world.add(tires);
 const waterGeo=new T.CircleGeometry(1,64);waterGeo.rotateX(-Math.PI/2);const wp=waterGeo.attributes.position;for(let i=0;i<wp.count;i++){const x=wp.getX(i),z=wp.getZ(i),a=Math.atan2(z,x),r=1+.035*Math.sin(a*7);wp.setXYZ(i,-12+x*10*r,.91,-15+z*7*r)}waterGeo.computeVertexNormals();this.waterMaterial=new T.MeshStandardMaterial({color:'#4b9291',metalness:.35,roughness:.22,transparent:true,opacity:.91,side:T.DoubleSide});this.water=mesh(waterGeo,this.waterMaterial,this.world);this.water.castShadow=false;
 const waterLines=[];for(let i=0;i<22;i++){const a=rnd()*Math.PI*2,r=Math.sqrt(rnd())*.85,x=-12+Math.cos(a)*r*10,z=-15+Math.sin(a)*r*7;waterLines.push(x,.93,z,x+.45+rnd(),.93,z)}const wg=new T.BufferGeometry;wg.setAttribute('position',new T.Float32BufferAttribute(waterLines,3));this.waterShine=new T.LineSegments(wg,new T.LineBasicMaterial({color:'#b4ded4',transparent:true,opacity:.37}));this.world.add(this.waterShine);
 // Vegetation is excluded from road edges, water and the pit area.
 const trees=[];for(let i=0;i<640;i++){const x=(rnd()-.5)*124,z=(rnd()-.5)*91,q=t.nearest(x,z);if(q.distance<5.4||Math.hypot((x+12)/12,(z+15)/9)<1||z>34&&x< -15||z>20&&rnd()<.76)continue;trees.push({x,z,y:t.terrain(x,z),size:.65+rnd()*.95,a:rnd()*6.28})}
 const crown=merge([0,1,2,3,4].map(i=>{const g=new T.ConeGeometry(1.55-i*.24,2.25-i*.15,9);g.translate(0,2.1+i*.8,0);return g})),trunk=new T.CylinderGeometry(.11,.22,4,6);trunk.translate(0,2,0);const tops=new T.InstancedMesh(crown,m.leaf,trees.length),stems=new T.InstancedMesh(trunk,m.bark,trees.length);trees.forEach((o,i)=>{dummy.position.set(o.x,o.y,o.z);dummy.rotation.set(0,o.a,0);dummy.scale.setScalar(o.size);dummy.updateMatrix();tops.setMatrixAt(i,dummy.matrix);stems.setMatrixAt(i,dummy.matrix);tops.setColorAt(i,new T.Color().setHSL(.26+rnd()*.045,.25+rnd()*.1,.32+rnd()*.23))});tops.castShadow=stems.castShadow=true;tops.receiveShadow=true;this.world.add(tops,stems);
 const rocks=[];for(let i=0;i<270;i++){const a=rnd()*6.28,x=i<60?-12+Math.cos(a)*(10.5+rnd()): (rnd()-.5)*123,z=i<60?-15+Math.sin(a)*(7.5+rnd()):(rnd()-.5)*90;if(t.nearest(x,z).distance<4.9||z>34&&x< -15)continue;rocks.push({x,z,s:.25+rnd()*.95})}const rg=new T.IcosahedronGeometry(1,0),rocksMesh=new T.InstancedMesh(rg,m.stone,rocks.length);rocks.forEach((o,i)=>{dummy.position.set(o.x,t.terrain(o.x,o.z)+.1,o.z);dummy.scale.set(o.s*1.5,o.s*.7,o.s);dummy.rotation.set(rnd(),rnd()*6.28,rnd());dummy.updateMatrix();rocksMesh.setMatrixAt(i,dummy.matrix)});rocksMesh.castShadow=true;rocksMesh.receiveShadow=true;this.world.add(rocksMesh);
 const grassGeo=new T.BufferGeometry;grassGeo.setAttribute('position',new T.Float32BufferAttribute([-.15,0,0,0,.65,0,.1,0,.04,0,0,-.12,.02,.45,0,.04,0,.16],3));grassGeo.computeVertexNormals();const grasses=[];for(let i=0;i<2500;i++){const x=(rnd()-.5)*121,z=(rnd()-.5)*90;if(t.nearest(x,z).distance<3.8||Math.hypot((x+12)/12,(z+15)/9)<1||z>34&&x< -15)continue;grasses.push({x,z,s:.5+rnd()*.8})}const grass=new T.InstancedMesh(grassGeo,m.grass,grasses.length);grasses.forEach((o,i)=>{dummy.position.set(o.x,t.terrain(o.x,o.z),o.z);dummy.scale.setScalar(o.s);dummy.rotation.set(0,rnd()*6.28,0);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix)});this.world.add(grass);
 // Fencing, marshal flags and course infrastructure set a coherent miniature scale.
 for(let s=0;s<t.length;s+=5.2){const q=t.sample(s,4.4),b=t.sample(s+5.2,4.4);if(q.z>16||q.x>46){beam(m.wood,this.world,[q.x,q.y,q.z],[q.x,q.y+1.25,q.z],.06);for(const h of [.5,1])beam(m.wood,this.world,[q.x,q.y+h,q.z],[b.x,b.y+h,b.z],.043)}}
 const testGroup=new T.Group;this.world.add(testGroup);for(const s of [t.editS-24,t.editS+24])for(const lane of [-4.1,4.1]){const q=t.sample(s,lane);beam(m.metal,testGroup,[q.x,q.y,q.z],[q.x,q.y+2.5,q.z],.07);const flag=box(m.orange,testGroup,[.75,1,.05],[q.x+.36,q.y+1.85,q.z]);flag.rotation.y=-.3}const testPoint=t.sample(t.editS,6),label=sign('试验坡 / TEST ZONE',9,1.1,'#2b2f23','#ffbd56');label.position.set(testPoint.x,testPoint.y+3,testPoint.z);label.rotation.y=.4;testGroup.add(label);this.testGroup=testGroup;
 const start=t.sample(0),gate=new T.Group;gate.position.set(start.x,start.y,start.z);gate.rotation.y=Math.atan2(start.forward.x,start.forward.z);this.world.add(gate);for(const x of [-3.9,3.9])beam(m.metal,gate,[x,0,0],[x,5.7,0],.13);box(m.metal,gate,[8.2,.7,.4],[0,5.5,0]);const board=sign('PINE RIDGE / START',8,1,'#fbefd2','#263f39');board.position.set(0,5.55,.23);gate.add(board);for(let x=0;x<12;x++)for(let z=0;z<3;z++){const o=box((x+z)%2?m.rubber:m.white,gate,[.44,.018,.44],[(x-5.5)*.44,.04,(z-1)*.44]);o.receiveShadow=true}
 const pit=new T.Group;pit.position.set(-31,t.terrain(-31,42),42);this.world.add(pit);box(m.mud,pit,[28,.1,10],[0,0,0]);for(let i=0;i<3;i++){const x=(i-1)*8;for(const px of [-2.9,2.9])for(const z of [-2.3,2.3])beam(m.metal,pit,[x+px,0,z],[x+px,3,z],.07);const roofMat=new T.MeshStandardMaterial({color:['#e5ba54','#638c94','#c76545'][i],roughness:.85});const roof=new T.ConeGeometry(4.5,1.2,4);roof.rotateY(Math.PI/4);const o=mesh(roof,roofMat,pit,x,3.5,0);o.scale.z=.82;box(m.wood,pit,[4,.3,1.5],[x,1,-.4]);box(m.metal,pit,[1.2,1.1,1],[x+1.6,.55,1]);const banner=sign(['01 / PIT','02 / SERVICE','03 / RACE'][i],5.5,.65);banner.position.set(x,2.65,2.4);pit.add(banner)}
 for(let i=0;i<16;i++){const x=-48+i*2.25,z=36.8,y=t.terrain(x,z);mesh(new T.CylinderGeometry(.16,.16,.75,6),i%3?m.metal:m.orange,this.world,x,y+.4,z);mesh(new T.SphereGeometry(.18,8,6),m.white,this.world,x,y+.95,z)}
 const signpost=sign('松脊越野公园',15,2.2,'#f7e7b7','#223d36');signpost.position.set(27,t.terrain(27,40)+2,40);this.world.add(signpost);for(const x of [21,33])beam(m.wood,this.world,[x,t.terrain(x,40),40],[x,t.terrain(x,40)+3.4,40],.1);
 this.originalMaterials.clear();for(const root of [this.world,...this.bikes.map(b=>b.g)])root.traverse(o=>{if(o.isMesh)this.originalMaterials.set(o,o.material)});this.geometryStats={trees:trees.length,rocks:rocks.length,grass:grasses.length,tires:marks.length};this.setView(this.view);this.renderer.shadowMap.needsUpdate=true;
 }
 makeWeather(){const rnd=random(203),a=new Float32Array(800*6);for(let i=0;i<800;i++){const x=(rnd()-.5)*130,y=rnd()*50,z=(rnd()-.5)*100;a.set([x,y,z,x-.25,y+1.4,z+.1],i*6)}const g=new T.BufferGeometry;g.setAttribute('position',new T.BufferAttribute(a,3));this.rain=new T.LineSegments(g,new T.LineBasicMaterial({color:'#d7e9e5',transparent:true,opacity:.36,depthWrite:false}));this.rain.frustumCulled=false;this.scene.add(this.rain);this.particles=Array.from({length:200},()=>({x:0,y:-100,z:0,life:0}));this.particleIndex=0;const pg=new T.BufferGeometry;pg.setAttribute('position',new T.BufferAttribute(new Float32Array(600),3));const dot=document.createElement('canvas');dot.width=32;dot.height=32;const ctx=dot.getContext('2d'),fade=ctx.createRadialGradient(16,16,0,16,16,16);fade.addColorStop(0,'rgba(255,255,255,.65)');fade.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=fade;ctx.fillRect(0,0,32,32);this.dust=new T.Points(pg,new T.PointsMaterial({size:.7,map:new T.CanvasTexture(dot),color:'#d4b58c',transparent:true,opacity:.40,depthWrite:false}));this.dust.frustumCulled=false;this.scene.add(this.dust)}
 setConfig(cfg){const rebuild=this.cfg.lift!==cfg.lift;this.cfg={...cfg};if(!this.mat)return;if(rebuild)this.build();this.testRoad.visible=cfg.surface!=='dirt';this.mat.road.color.set('#bf9262').lerp(new T.Color('#6d6651'),cfg.wet*.65);this.mat.mud.color.set(cfg.surface==='mud'?'#847052':cfg.surface==='gravel'?'#a6a392':'#aa835d');for(const mat of [this.mat.road,this.mat.mud])mat.roughness=.95-cfg.wet*.58;this.mat.ground.color.set('#aab08a').lerp(new T.Color('#7c8d7d'),cfg.wet*.4);this.sun.intensity=mix(3.3,1.5,cfg.wet);this.hemi.intensity=mix(2,1.7,cfg.wet);this.scene.background.set('#9fb8bd').lerp(new T.Color('#70888d'),cfg.wet);this.scene.fog.color.copy(this.scene.background);if(this.mode==='test')this.setCamera('test')}
 setView(mode){this.view=mode;this.clay??=new T.MeshStandardMaterial({color:'#c4ceca',roughness:.93});this.wire??=new T.MeshBasicMaterial({color:'#cfdfd0',wireframe:true});for(const [o,m]of this.originalMaterials)o.material=mode==='clay'?this.clay:mode==='wire'?this.wire:m}
 setCamera(mode){this.mode=mode;this.controls.enabled=mode==='overview'||mode==='test';if(mode==='overview')this.overview();if(mode==='test'){const p=this.track.sample(this.track.editS);this.camera.position.set(p.x+16,p.y+14,p.z+24);this.controls.target.set(p.x,p.y+1,p.z);this.controls.update()}this.follow.copy(this.camera.position);this.aim.copy(this.controls.target)}
 update(dt,race,paused=false){if(!this.mat)return;const animDt=paused?0:dt;this.time+=animDt;for(const r of race.riders){const b=this.bikes[r.id],q=this.track.sample(r.s,r.lane),front=this.track.sample(r.s+1.03,r.lane),back=this.track.sample(r.s-.93,r.lane);b.g.position.set(q.x,q.y+.045,q.z);b.g.rotation.set(0,Math.atan2(q.forward.x,q.forward.z),0);b.body.rotation.x=-r.pitch;b.body.rotation.z=r.roll;b.body.position.y=Math.sin(this.time*23+r.id)*.012*r.v/6;for(let i=0;i<2;i++){b.wheels[i].pivot.position.y=.49+(i===0?back.y:front.y)-q.y;b.wheels[i].spin.rotation.x+=r.v*animDt/.49}if(r.v>2&&animDt>0){const p=this.particles[this.particleIndex++%this.particles.length];Object.assign(p,{x:back.x,y:back.y+.25,z:back.z,life:.9+Math.random()*.45})}}
 const rider=race.riders[this.selected],q=this.track.sample(rider.s,rider.lane);if(this.mode==='follow'||this.mode==='helmet'){const close=this.mode==='helmet',back=close?.35:-8,up=close?2.5:5.2,target=this.track.sample(rider.s+(close?10:5),rider.lane);const desired=V(q.x+q.forward.x*back,q.y+up,q.z+q.forward.z*back);this.follow.lerp(desired,1-Math.exp(-dt*(close?9:5)));this.aim.lerp(V(target.x,target.y+(close?1.7:1),target.z),1-Math.exp(-dt*6));this.camera.position.copy(this.follow);this.camera.lookAt(this.aim)}else this.controls.update();this.bikes.forEach((b,i)=>{b.body.visible=!(this.mode==='helmet'&&i===this.selected)});
 if(this.rain){this.rain.visible=this.cfg.wet>.15;if(this.rain.visible){const a=this.rain.geometry.attributes.position.array;this.rain.geometry.setDrawRange(0,Math.floor(800*this.cfg.wet)*2);for(let i=0;i<a.length;i+=6){a[i+1]-=animDt*25;a[i+4]-=animDt*25;if(a[i+1]<0){a[i+1]+=50;a[i+4]+=50}}this.rain.geometry.attributes.position.needsUpdate=true}const ar=this.dust.geometry.attributes.position.array;this.particles.forEach((p,i)=>{p.life-=animDt;if(p.life>0){p.y+=animDt*.45;p.x+=animDt*.3;ar.set([p.x,p.y,p.z],i*3)}else ar[i*3+1]=-100});this.dust.geometry.attributes.position.needsUpdate=true;this.dust.material.color.set(this.cfg.wet>.4?'#cadbd1':'#dcc29a');this.dust.material.size=this.cfg.wet>.4?.35:.7;this.dust.material.opacity=this.cfg.wet>.4?.25:.4}
 if(this.waterShine)this.waterShine.material.opacity=.3+Math.sin(this.time)*.1;this.renderer.render(this.scene,this.camera)
 }
 dispose(){this.resizeObserver.disconnect();this.controls.dispose();this.clear();this.renderer.dispose()}
}
