const params=new URLSearchParams(location.search);
let lang=params.get('lang')==='en'?'en':'zh';
if(!params.has('lang')){try{lang=localStorage.getItem('eanpa-research-language')==='en'?'en':'zh';}catch{}}
if(params.get('embedded')==='1')document.body.classList.add('embedded');
const commit='a197d3dc42577e9b870b471a39d6b1710c5b5633';
const upstream=`https://github.com/SkyeShark/Eanpa-Sky/blob/${commit}/`;
const t=(zh,en)=>lang==='zh'?zh:en;
const mib=n=>(n/1048576).toFixed(2);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let report;
const labels={
 'assets/pbr':['地表材质','Ground materials'], 'assets/terrain':['地形与岩石','Terrain & rocks'],
 'assets/vegetation':['树木与仙人掌','Trees & cacti'],'assets/ringworld':['环世界资源','Ringworld assets'],
 'assets/player':['第一人称角色','First-person model'],'assets/temple':['神庙与道具','Temple & props'],
};
function render(){
 document.documentElement.lang=lang==='zh'?'zh-CN':'en';
 document.title=t('004 · Eanpa Sky 实践记录','004 · Eanpa Sky practice journal');
 document.getElementById('journal-language').value=lang;
 document.getElementById('back-demo').textContent=t('返回演示','Back to demo');
 const engine=report.groups.find(g=>g.path==='engine').bytes;
 const top=report.groups.slice(0,6);
 const other=report.bytes-top.reduce((n,g)=>n+g.bytes,0);
 const bars=[...top,{path:'other',bytes:other}].map(g=>`<div class="bar"><div class="bar-label"><span>${g.path==='other'?t('其他（含代码、草木、音频等）','Other, including code, plants & audio'):t(...(labels[g.path]||[g.path,g.path]))}</span><span>${mib(g.bytes)} MiB</span></div><div class="track"><div class="fill" style="width:${g.bytes/report.bytes*100}%"></div></div></div>`).join('');
 const effects=[
  ['体积云：云团有厚薄和透光','Volumetric clouds: depth and light', '三维噪声叠加生成云密度，沿视线逐段采样；再估算太阳光穿透云层的衰减与散射。风推动密度场，让云形随时间变化。','Layered 3D noise defines density. Ray marching accumulates extinction and scattering along the view, with light sampling toward the sun. Wind moves the density field.','不是实体网格云，也不是流体天气预测；多次采样带来 GPU 开销。','This is a density field, not a fluid weather forecast. Repeated sampling costs GPU time.'],
  ['昼夜：天空和地面一起变色','Day/night: coordinated lighting','按太阳高度插值预设的天空颜色、光强和星空可见度，统一驱动云、主光与环境光；月亮结合贴图与照明表现月相。','A sun-elevation palette drives sky color, cloud lighting, key light and ambient light. Moon textures and lighting provide the lunar appearance.','包含美术设定，不是完整的真实大气求解。','The palette is authored; this is not a full atmospheric solver.'],
  ['云影：云遮住阳光，建筑跟着变暗','Cloud shadows on scene geometry','把云沿光线方向的遮光计算汇总成共享纹理。建筑和地形按世界坐标查询，而不是每个材质各算一遍体积云。','A shared map integrates cloud attenuation along the light direction. Scene surfaces sample it using world positions, avoiding a full cloud march per material.','默认约 10 Hz 更新；范围有限，云内部使用近似。','The default cadence is about 10 Hz; coverage is finite and in-cloud shading is approximate.'],
  ['降雨：雨丝、遮雨和表面冲击','Rain, shelter and impacts','在相机周围布置世界空间雨粒子；沿降雨方向捕获第一层表面深度与法线，用于屋顶遮雨、落点和溅水朝向。','World-space rain particles surround the camera. A depth/normal capture along the rain direction supplies shelter, hit locations and splash orientation.','需要额外渲染通道；不是逐个雨滴的完整物理模拟。','This needs an extra capture pass, not a complete physical simulation of every raindrop.'],
  ['雨后水迹：地面逐渐变湿并反光','Wet surfaces and persistent puddles','GPU 历史纹理分别记录薄层湿润和积水；材质降低粗糙度、调整法线与反射，让水迹在雨后继续保留并逐渐干燥。','GPU history stores wetness and pooled water separately. Materials change roughness, normals and reflectance, preserving water after rain and allowing drying.','没有径流、排水、困水体积或移动物体的完整水量历史。','There is no runoff, drainage, trapped-water volume or complete moisture history on moving objects.'],
  ['科幻天空：环世界、红巨星与护盾','Sci-fi skies: ring, giant and shield','环世界由曲面地形、纹理和遮光逻辑组成；红巨星使用大角直径光源的近似，配合护盾及破碎月球几何。','Ringworld combines curved terrain, textures and occlusion. The red-giant scene approximates an extended light source with shield and fragmented-moon geometry.','相应模型和地形增加下载量，切换会构建新的渲染管线。','Extra geometry and textures increase payload; switching prepares new rendering pipelines.'],
 ];
 const cards=effects.map(e=>`<article class="card"><h3>${t(e[0],e[1])}</h3><p>${t(e[2],e[3])}</p><p class="muted">${t(e[4],e[5])}</p></article>`).join('');
 const shots=[['01-earth-cumulus.jpg','Earth 积云 · 原版','Earth cumulus · original'],['04-earth-rain.jpg','降雨与地面水迹 · 原版','Rain and wet ground · original'],['06-orbital-halo.jpg','环世界 · 原版','Orbital / Halo · original'],['02-earth-sunset.jpg','18.5h 暮色 · 原版','18.5h dusk · original'],['03-earth-night.jpg','24h 夜间 · 原版','24h night · original'],['07-shieldworld.jpg','护盾世界 · 原版默认视角','Shieldworld · original default view']];
 document.getElementById('journal').innerHTML=`
 <div class="eyebrow">004 / PRACTICE JOURNAL · ${report.date} · v0.2.1</div>
 <h1>${t('天空、天气，以及它们的代价','Sky, weather, and their cost')}</h1>
 <p class="lead">${t('先运行原版，再用实测数据理解开销。本页保留效果原理、操作记录和验证边界，随我们的实践更新。','We run the original first, then examine the costs. This journal preserves mechanisms, observations and verification limits as our work progresses.')}</p>
 <nav class="nav" aria-label="${t('记录导航','Journal navigation')}"><a href="#resources">${t('资源为什么大','Resource costs')}</a><a href="#mechanisms">${t('效果与原理','Effects & mechanisms')}</a><a href="#practice">${t('我们的实践','Our practice')}</a><a href="#gallery">${t('实测截图','Screenshots')}</a></nav>
 <p><a href="/lab/" target="_top">${t('最新实践：进入听雨小院，对比同场景天气与自然声音 →','New: enter the courtyard to try extracted effects →')}</a></p>
 <section id="resources"><h2>${t('大的是哪里？先区分三个概念','Where does the cost come from?')}</h2>
 <span class="tag">${t('磁盘实测 · 固定版本缓存','Measured disk cache · pinned version')}</span>
 <div class="metrics"><div class="metric"><strong>${(report.bytes/1048576).toFixed(1)} MiB</strong><span>${t('本地缓存总量','Total local cache')}</span></div><div class="metric"><strong>${report.files}</strong><span>${t('已缓存上游文件','Cached upstream files')}</span></div><div class="metric"><strong>${mib(engine)} MiB</strong><span>${t('天空与天气引擎源码','Sky/weather engine source')}</span></div></div>
 <p class="muted">${t('统计范围：预取源码并体验三种天空后，磁盘中实际保存的原始文件。不是单次首屏下载量，也不是内存或显存；缓存含预览贴图与完整贴图。','Scope: files stored after code prefetch and three sky environments. This is not one page transfer, RAM or VRAM; preview and full-resolution textures may both be cached.')}</p>
 <div class="split"><div><h3>${t('① 下载和磁盘：完整演示的素材占大头','① Download & disk: scene assets dominate')}</h3>${bars}</div><div><h3>${t('两个地表文件就占约 139.4 MiB','Two ground files alone total about 139.4 MiB')}</h3><p>${t('它们分别存放 14 层 2K 地表材质的颜色/高度，以及法线/粗糙度/环境遮蔽信息。加上岩石、植被、神庙、角色和环世界，这个演示的体积远超天空源码本身。','These hold fourteen 2K ground layers: albedo/height in one, normal/roughness/AO in the other. Rocks, vegetation, temple, player and Ringworld make the demo much larger than the sky source.')}</p><p>${t('降低“天空画质”仍然保留地形、建筑和环境遮蔽，因此不能期待素材下载量随之大幅减少。','Lowering sky quality retains terrain, architecture and ambient occlusion, so it does not substantially shrink those downloads.')}</p><div class="callout">${t('减小下载体积：优先按需加载场景、减少地表材质层数和纹理分辨率，替换大型模型。仅压缩脚本的收益很小。','To reduce payload, load scene assets on demand, reduce material layers and texture resolution, and replace large models. Minifying scripts offers little benefit here.')}</div></div></div>
 <div class="grid"><article class="card"><span class="tag">${t('源码核查 · 未做本机 GPU 计时','Source inspection · no local GPU timing')}</span><h3>${t('② 渲染计算：一个画面，要算好几遍','② Rendering: several passes for one frame')}</h3><p>${t('均衡档云层配置为 44 个视线采样、14 个光照采样、3 个云渲染 pass，并使用降分辨率和缓存。实际工作量受缓存、跳步、提前退出和画面覆盖影响，不能简单相乘得到精确耗时。','Balanced configures 44 view samples, 14 light samples and 3 cloud passes, with reduced resolution and caches. Caching, skipping, early exits and screen coverage prevent a simple product from predicting exact time.')}</p><p>${t('除此之外还有云影、太阳阴影、天空环境反射、局部反射、环境遮蔽和雨表面捕获。均衡档还配置 10,000 个雨粒子与 700 个水花。','Cloud/sun shadows, sky and local reflections, ambient occlusion and rain-surface captures add work. Balanced also configures 10,000 rain particles and 700 splashes.')}</p></article><article class="card"><span class="tag">${t('原理与上游说明 · 实际显存未测','Mechanism & upstream docs · VRAM unmeasured')}</span><h3>${t('③ 内存与显存：文件大小不等于展开后的资源','③ Memory: stored bytes are not GPU residency')}</h3><p>${t('运行时需要几何缓冲、解码或转码后的纹理、mipmap、深度图和多张浮点渲染目标。KTX2 可能转码为 GPU 压缩格式，不能一律按 RGBA 展开估算。','Runtime needs geometry buffers, decoded/transcoded textures, mipmaps, depth maps and floating-point targets. KTX2 can transcode to GPU compression, so assuming uncompressed RGBA everywhere is wrong.')}</p><p>${t('示例：一张未压缩 4096² RGBA8 纹理约 64 MiB，完整 mipmap 后约 85.3 MiB；这只是算例。Performance 档的默认三组云全景缓存，上游记录合计约 60 MiB，省计算也需要显存。','Example only: uncompressed 4096² RGBA8 is 64 MiB, about 85.3 MiB with a full mip chain. Upstream documents roughly 60 MiB for the default three Performance cloud captures: saving computation also uses memory.')}</p></article></div>
 <div class="callout"><h3>${t('为什么加载完还要等？','Why wait after downloads finish?')}</h3><p>${t('纹理要处理并上传 GPU，场景要构建；TSL 节点图还要生成着色器，由驱动编译各渲染管线，并准备反射与首帧。切换天空可能重做其中一部分。所以“网络快”不等于“启动快”。当前尚未测量各阶段耗时与实际显存峰值。','Textures need processing and upload; scenes need assembly. TSL graphs generate shaders, drivers compile pipelines, and reflections/first-frame resources must be prepared. Sky changes repeat some work. Fast networking does not imply fast startup; stage timings and peak VRAM remain unmeasured.')}</p></div>
 <details><summary>${t('查看最大的 12 个缓存文件','Inspect the 12 largest cached files')}</summary><div class="table-wrap"><table><thead><tr><th>${t('文件','File')}</th><th>MiB</th></tr></thead><tbody>${report.largest.map(f=>`<tr><td><code>${escape(f.path)}</code></td><td>${mib(f.bytes)}</td></tr>`).join('')}</tbody></table></div></details>
 </section>
 <section id="mechanisms"><h2>${t('看到的效果，背后在做什么','What produces each visible effect')}</h2><p class="lead">${t('核心是共享时间、风和天气状态，让天空、光照、阴影与材质同步响应。下面是源码核查结论，不代表每种边界条件均已实测。','Shared time, wind and weather state coordinate sky, lighting, shadows and materials. These are source-based explanations, not exhaustive runtime verification.')}</p><div class="grid">${cards}</div><p class="muted" style="margin-top:16px">${t('Performance 用分批捕获并插值的云全景减少重复体积计算；Balanced / High 保留实时体积云。缓存方式会牺牲精细云形变化、多层视差和快速穿云的准确性。','Performance amortizes volume rendering into blended panorama captures; Balanced / High render live cloud volumes. Caching trades away fine evolution, multilayer parallax and accuracy during fast cloud fly-throughs.')}</p></section>
 <section id="practice"><h2>${t('我们的实践记录','Our practice journal')}</h2><div class="timeline">
 <article><time>2026-09-14 / 25</time><h3>${t('融雪联动与持续运行检查','Snowmelt and runtime checks')}</h3><p>${t('新增“日间积雪 → 融雪”导览：12:30 积雪 45 秒，再放晴观察 90 秒。积雪减少量补入宿主泥土与浅洼，不增加雨量或雨声。日照和雨量控制演示融化速度，夜间较慢。','A daytime snow-to-thaw tour builds snow for 45 seconds at 12:30, then clears for a 90-second observation. Snow loss replenishes host soil and pools without adding rain or rain sounds. Sunlight and rain influence the visual thaw rate; nights are slower.')}</p><p>${t('事件历史最多保留 600 条，资源趋势最多 120 份，另外记录总数与丢弃数量。40 项检查通过，覆盖融水分配、暂停、溢出、步长和反复切换的数值边界。浏览器观察时长另记，不能代替数小时或多设备稳定性验收。','Event history retains at most 600 entries and resource trends at most 120 samples, with total and discard counts. All 40 checks pass, including melt allocation, pause, overflow, timestep consistency and repeated-cycle bounds. Browser observation duration is recorded separately and does not replace multi-hour or cross-device acceptance.')}</p><p class="muted">${t('归一化演示储量，不是真实雪深、温度、水文或融水路径求解。','Normalized visual reservoirs, not measured snow depth, temperature, hydrology or meltwater paths.')}</p></article>
 <article><time>2026-09-14 / 24</time><h3>${t('启动预览与自动画质','Startup preview and adaptive quality')}</h3><p>${t('增加不依赖三维引擎的院落示意，明确标记尚非实时天气；五阶段进度按实际准备完成推进。默认自动画质，根据持续帧率与提交耗时调整云分辨率、环境反射更新频率和轻量档遮蔽效果；降档与恢复采用不同等待时间，避免频繁跳变。手动均衡/省电可覆盖自动选择并在刷新后保留。','An engine-independent courtyard illustration is labeled as a preview, with five stages tied to real completion. Auto quality uses sustained frame rate and submission time to adjust cloud resolution, sky-environment refresh and light-tier occlusion. Asymmetric thresholds and cooldowns prevent frequent switching. Manual Balanced/Eco modes override automation and persist across reloads.')}</p><p class="muted">${t('预览可见不等于真实天气已就绪；本轮不宣称缩短完整编译时间。暂停、后台、天气过渡、镜头移动期间不积累自动画质判断依据。','Preview visibility does not mean live weather is ready; this round makes no claim of faster full compilation. Pauses, background intervals, weather transitions and camera movement do not build adaptation evidence.')}</p></article>
 <article><time>2026-09-14 / 23</time><h3>${t('启动与降雪开销优化','Startup and snowfall optimization')}</h3><p>${t('远山、草地、泥土和积雪简化局部反射，保留天空照明、云影与夜灯；石径、水面和窗户保留完整反射。雪花碰撞系数每帧预计算，只提交可见雪花。两次启动约 29.2 / 36.3 秒，上轮约 42.3 秒；独立碰撞基准中位耗时减少 31.7%。31 项检查通过。','Matte landscape, earth and snow use simplified reflections while retaining sky lighting, cloud shadows and lamps; paths, water and windows keep full reflections. Snow collision coefficients are prepared once per frame and only visible flakes are submitted. Two startups took 29.2 / 36.3 seconds versus the prior 42.3 seconds; the CPU collision benchmark median fell 31.7%. All 31 checks passed.')}</p><p class="muted">${t('启动是同设备少量观察，受缓存和负载影响；查询基准不是整帧或 GPU 提速。哑光表面的局部反射有所简化，多设备与长期稳定性仍待验证。','Startup observations are limited to one device and affected by cache and load. Query timing is not whole-frame or GPU acceleration. Matte local reflections are simplified; cross-device and endurance checks remain open.')}</p></article>
 <article><time>2026-09-14 / 22</time><h3>${t('单设备验收与启动分段','Single-device acceptance and startup timing')}</h3><p>${t('现有 11 份测试文件共 29 项检查通过，增加启动分段与有限长度的近期帧耗时记录。本次导航到就绪约 42.6 秒，其中反射与材质编译约 28.8 秒、云渲染编译约 4.8 秒；雪景存在性能压力。多设备兼容、长时间稳定性和人工听感仍待验收。','All 29 checks across 11 existing test files pass. Added startup stages and bounded recent frame-submission timings. This navigation took about 42.6 seconds, including 28.8 seconds for reflection/material compilation and 4.8 seconds for clouds. Snow still has performance pressure; device coverage, endurance and listening remain unverified.')}</p></article>
 <article><time>2026-09-14 / 21</time><h3>${t('水岸退缩、同步过渡与演示进度','Shorelines, synchronized transitions and demo progress')}</h3><p>${t('新增随地形退缩的水洼边缘和缓慢消退的岸边湿痕。雾化跟随引擎云雨过渡进度，快速切换时从当前状态继续。自动演示以常驻卡片显示四阶段、阶段剩余时间和总倒计时；收起设置后仍可暂停或结束。','Puddle edges follow terrain height as water retreats, leaving damp traces. Fog follows the engine transition clock and continues from its current state on interruption. A persistent demo card shows four stages and remaining time, with an exit outside the settings panel.')}</p></article>
 <article><time>2026-09-14 / 20</time><h3>${t('20 · 天空光线、雨停地面与声音层次','20 · Sky light, ground drying and sound variation')}</h3><p>${t('新增“看天空光线”和“演示雨起 → 雨停”入口。雨停演示先降雨 40 秒，再观察 70 秒放晴与退水，保留当前时段；可以中止，手动切天气也会退出。泥土含水与浅洼水量分别保留，晴天和风会加快干燥。不同天气的远山雾化与散射光平滑过渡；近处接触声增加六组音色变体和距离滤波。','Added Sky & light and a rain-to-clearing demo: 40 seconds of rain, then 70 seconds of clearing, with time preserved. Stop it or choose weather manually to exit. Soil moisture outlasts pools; sunshine and wind speed drying. Atmospheric visibility transitions smoothly, and contact sounds use six timbre variants with distance filtering.')}</p></article>
 <article><time>2026-09-14 / 19</time><h3>${t('碰撞、全景声音与操作修复','Collision, distant audio and control fixes')}</h3><p>${t('修复冰雹侧入屋檐时被抬到屋顶的问题，统一建筑、地面与树冠近似表面，补充异常粒子回收。远处增加碰撞驱动的整体冰雹声场。设置默认收起、暂停常驻；暂停时调场景会恢复播放，手动机位标记自由视角并记录实际位置。树冠仍为近似碰撞，积雪不含热力与融雪排水。','Fixed hail jumping onto roofs on side entry, shared authored surface and canopy proxies, and reclaimed escaped particles. Distant hail gets an impact-driven diffuse bed. Settings collapse; Pause stays visible; scene changes resume playback, and manual views record actual camera coordinates. Canopy collision remains approximate, without thermal snow or meltwater.')}</p></article>
 <article><time>2026-09-14 / 18</time><h3>${t('复现碰撞、声场与暂停状态问题','Reproducing collision, audio and pause issues')}</h3><p>${t('通过页面观察、状态记录与函数复现定位屋檐侧入错误、全景声音覆盖不足、暂停后按钮与画面不同步，以及自由机位标签失真；保留修复前截图作为对照。','UI observations, state reports and function probes reproduced roof side-entry errors, missing distant audio, paused control divergence and stale camera labels. Before-fix evidence is retained.')}</p></article>
 <article><time>2026-09-14 / 17</time><h3>${t('冰雹碰撞与整片雪景','Hail impacts and landscape snow')}</h3><p>${t('新增冰雹：快速下落，按石径、屋顶、泥土、水面和残雪区分反弹与声音；最多三次衰减反弹，落点驱动短促敲击。树冠、林带、草地与山体现在共享积雪进度，直接修改现有材质，不复制场景模型。仍是视觉近似，尚无破碎、冰雹堆积或热力融雪。','Added fast hail with surface-specific rebound and sound on stone, roofs, earth, water and snow. Up to three damped rebounds trigger impact sounds. Canopies, forest, grass and hills share snow history through existing materials, without duplicating models. This remains a visual approximation without fracture, hail piles or thermal melting.')}</p></article>
 <article><time>2026-09-14 / 16</time><h3>${t('同机位晴阴雨雪：飘雪与积雪','Clear, overcast, rain and snow in one view')}</h3><p>${t('新增降雪：复用阴天天空，慢落雪片在屋顶和地面高度终止；屋顶与露天院落渐渐积雪，檐下不铺雪。天气按钮保留时段、机位与灯光；声音转为轻柔风声。积雪使用加速视觉时间，尚无树冠与远山积雪、冰雹或融雪排水。','Added snow on the overcast sky: slow flakes stop at roof or ground height, and exposed surfaces gradually gain snow cover. Shelter stays clear. Weather buttons preserve time, camera and lights, while audio shifts to soft wind. Accumulation uses accelerated visual time; canopy and distant snow, hail and meltwater remain future work.')}</p></article>
 <article><time>2026-09-14 / 15</time><h3>${t('二维波动场：涟漪传播与叠加','2D wave fields: propagation and overlap')}</h3><p>${t('三个 64×64 水面网格由雨滴落点驱动，固定时间步求解带阻尼波动，更新动态水面顶点与法线。水洼不再使用旧圈层和持续正弦摆动。新增波动开关和单次水滴观察入口，雨停后原波纹自然衰减。','Rain impacts drive three 64×64 fields with fixed-step damped waves and dynamic surface vertices and normals. Puddles no longer use old rings or continuous sine oscillation. A wave toggle and single-drop control support inspection; existing waves decay after rain stops.')}</p><p>${t('使用 CPU 小网格及动态顶点，不是完整流体、径流或精确水深求解。','Uses small CPU grids and dynamic vertices, not full fluids, runoff or precise depth simulation.')}</p><a href="/lab/" target="_top">${t('观察水面波动 →','Inspect the water waves →')}</a></article>
 <article><time>2026-09-14 / 14</time><h3>${t('修正水花的弹珠感','Correcting marble-like splashes')}</h3><p>${t('定位到宿主新增球体水花尺寸过大、抛起过高、三颗同轨迹重复和寿命末尾突然消失。改为毫米级软边薄片，沿投影速度拉伸，加入阻力、材质差异、事件随机与淡出；回到地面后终止，不做二次反弹。','Oversized added spheres, high launches, repeated three-droplet patterns and abrupt removal produced the marble look. Millimetre soft sprites now stretch along projected velocity, with drag, material variation, per-event randomness and fading; ground contact ends the droplet without rebound.')}</p><a href="/lab/" target="_top">${t('查看修正后的水花 →','Inspect the revised splashes →')}</a></article>
 <article><time>2026-09-14 / 13</time><h3>${t('院前雨幕与地面落点','Courtyard rain and ground contact')}</h3><p>${t('针对雨丝稀疏、地面反馈难辨认，补充院前 480 个错时雨滴周期、同步水花和渐淡水圈；三处浅洼逐渐蓄水与退水，泥地增加几何细分。夜雨随局部灯光增强，未通过抬高全局曝光实现。','Added 480 staggered courtyard drop cycles with matching splashes and fading rings, gradually filled depressions and finer earth geometry. Nearby lamps improve night-rain visibility without raising global exposure.')}</p><p>${t('附加雨区限定于当前无遮挡院前，使用观察者附近的局部雨量。蓄水、落点与灯光散射均为展示近似，不是完整流体或全场景遮挡求解。','The extra rain is limited to the authored open courtyard and driven by nearby rainfall. Water filling, contacts and scattering are visual approximations, not a full fluid or scene-wide occlusion solver.')}</p><a href="/lab/" target="_top">${t('查看降雨与地面 →','See rain and ground effects →')}</a></article>
 <article><time>2026-09-14 / 12</time><h3>${t('夜景光线与独立开灯','Night lighting and independent switches')}</h3><p>${t('自动、开灯、关灯独立于天气和时间，可调整亮度并分别启用茶亭、步道、客房。暖色聚光、茶具补光、步道与窗口近处光共同形成局部夜景；水滴与落点圈接受实际光照。自动模式按演示时间表平滑渐变。','Auto, On and Off are independent of weather and time, with dimming and pavilion/path/room zones. Warm spot, tea-set fill, path and window lights form a local night scene; drops and impact rings receive scene lighting. Auto fades on an authored schedule.')}</p><p>${t('新增局部灯光阴影导致本机 WebGPU 渲染错误，最终保留日光阴影，不增加局部阴影贴图。暖光补光与窗口光是近似，未实现完整室内全局光照。','Added local shadows caused a WebGPU rendering error on this device. The final version retains sunlight shadows without additional local shadow maps. Fill and window spill approximate lighting rather than full indoor global illumination.')}</p><a href="/lab/" target="_top">${t('进入夜景，切换开关 →','Explore the night lighting →')}</a></article>
 <article><time>2026-09-14 / 11</time><h3>${t('天气与时间独立组合','Independent weather and time')}</h3><p>${t('修正快捷入口把天气与时间绑定的问题：夜晚不再停雨，切降雨不再跳回午后。天气和时段分成两行并分别显示选中状态；雨景与闪电入口也保留当前时间。导览和组合预设继续联动天气、时间与机位，并明确标注。','Fixed shortcuts coupling weather and time: Night no longer stops rain and Rain no longer resets the afternoon. Separate rows track their own selection; rain and lightning actions preserve time. Guided and combined presets remain explicitly linked to weather, time and viewpoint.')}</p><a href="/lab/" target="_top">${t('自由组合天气与时段 →','Combine weather and time →')}</a></article>
 <article><time>2026-09-14 / 10</time><h3>${t('完整听雨：远景、近景与声音','A complete rain scene across distance and sound')}</h3><p>${t('新增三层山脊与林带、天气雾化、粗糙泥土和局部浅洼、碎石、前景茶具，以及檐口滴水和落点涟漪。滴水事件同步触发距离与方向匹配的近处声音；自然雨雷底声继续保留。四个机位和隐藏界面支持分层观察；滴水/远景可开关，近处声音可独立调整。','Added three ridge layers, forest, weather haze, rough earth, local depressions, gravel, tea utensils, eave drops and impact rings. Drop events trigger nearby sounds with matching distance and direction over the natural rain/thunder bed. Four viewpoints, a hidden-UI mode and separate layer/detail-volume controls support inspection.')}</p><p>${t('屋顶余水采用局部储水近似；近处短音为合成，树叶层为滤波，不冒充各材质实录。没有完整屋面汇流、泥浆或建筑声学求解。','Roof runoff uses a local reservoir approximation. Short impacts are synthesized and foliage sound is filtered, not material-specific recordings. This is not full runoff, mud dynamics or architectural acoustics.')}</p><a href="/lab/" target="_top">${t('打开完整听雨 →','Open the full rain experience →')}</a></article>

 <article><time>2026-09-14 / 09</time><h3>${t('让雨与闪电更容易看到','Making rain and lightning easier to see')}</h3><p>${t('修正体验入口：夜晚晴空本身不会下雨，普通降雨也没有雷电。首页新增看泥地雨景、观看闪电两个按钮，分别进入低机位降雨与雷暴真实落雷演示。院前改为泥地和窄石径对照，使用浅起伏与积水遮罩；保持粒子数量，雨域半径从 45 米收紧到 28 米。','Night with no weather does not rain, and ordinary rain has no lightning. Two prominent buttons open a low rain viewpoint or prepare a real storm strike. Earth and narrow stone paths provide wet-surface contrast, with shallow relief and a cavity mask. Rain radius drops from 45 to 28 metres with the same particle count.')}</p><p>${t('泥地仍是视觉近似；没有泥浆流动、屋檐滴水、排水或脚印系统。','Earth remains a visual approximation, without mud flow, eave dripping, drainage or footprints.')}</p></article>

 <article><time>2026-09-14 / 08</time><h3>${t('听雨山居：天气应用于民宿导览','Rain Garden Stay: weather in a guesthouse tour')}</h3><p>${t('新增入口门架与三间客房，以抵达庭院、花园散步、檐下品茶、夜间归房四站串联天气、机位、声音与灯光。每站可手动改变天气；进入茶亭和查看归途按钮实际移动相机。补齐无云晴天、太阳雨、阴天、强风暴入口，固定版本八种天气预设均可选择。暮色和夜晚属于时间，不额外计为天气。','Added an entry gate and three guest rooms. Four stops connect weather, camera, sound and lighting. Change weather at any stop and use actual viewpoint actions. Added cloudless, sunshower, overcast and cyclone controls, exposing all eight pinned presets. Dusk and night are time settings, not additional weather types.')}</p><p>${t('这是虚构民宿展示原型；雪、冰雹、沙尘和独立浓雾天气仍未实现。页面内“天气覆盖说明”记录范围与限制。','This is a fictional guesthouse prototype. Snow, hail, dust storms and dedicated dense fog remain unimplemented; the coverage panel describes the scope.')}</p><a href="/lab/" target="_top">${t('进入民宿体验 →','Enter the guesthouse tour →')}</a></article>

 <article><time>2026-09-14 / 07</time><h3>${t('听雨小院：场景适配与声音修正','Listening Garden: scene adaptation and corrected audio')}</h3><p>${t('新建包含屋檐、石径、树木、花坛和夜灯的小院；晴天、降雨、雷暴、暮色、夜晚保持当前机位。旧版噪声合成已替换为自然雨声与雷声，首次开启加载约 0.4 MiB；风声保留轻量合成。声音读取 GPU 局部雨量与遮挡，支持分层检查，静音先淡出再暂停。','A garden with a roof, stone path, trees, planting beds and night lights compares clear, rain, storm, dusk and night without moving the camera. Natural rain and thunder replace the old noise synthesis, adding about 0.4 MiB on first enable. Quiet wind remains synthesized. Audio reads GPU local rainfall and shelter, supports isolated layers, and fades before suspension.')}</p><p>${t('本次浏览器验证：录音加载成功，露天/檐下遮挡值为 0/1；闪电对应雷声已触发，44 米事件延迟约 0.13 秒。声音输出与事件检查不等于人工听感验收。初次运行仍需编译着色器。','Browser verification: recordings loaded, outdoor/roof shelter measured 0/1, and a 44-metre strike triggered thunder after about 0.13 seconds. Output and event checks do not replace listening tests. Initial shader compilation remains necessary.')}</p><p><a href="/lab/" target="_top">${t('进入小院，从“可以用在哪里？”查看扩展说明 →','Enter the garden and open application guidance →')}</a></p></article>

 <article><time>2026-09-14 / 06</time><h3>${t('从效果到用途：一键场景体验','From effects to uses: guided presets')}</h3><p>${t('新增建筑雨景、落日景观和雨中材质三个配置，同步设置天气、时间和机位，保留观察提示。参数面板默认收起，机位平滑切换；增加五类应用说明，区分效果原型与完整业务系统。三个配置仍使用同一示意庭院。','Three presets set weather, time and viewpoints with observation prompts. Controls collapse by default and viewpoints ease between positions. Five application explanations separate visual prototypes from complete products. All presets use the same demonstration courtyard.')}</p></article>
 <article><time>2026-09-14 / 05</time><h3>${t('天气声场：风、雨与雷','Weather soundscape: wind, rain and thunder')}</h3><p>${t('为独立庭院加入合成风声、立体声雨声、屋顶雨滴和雷声。音量跟随引擎实际雨量与风速；根据相机是否位于屋顶下改变声场。雷声绑定闪电事件，按距离延迟并调整方向、响度与高频。提供开启、静音、音量和输出强度显示；暂停或离开页面时声音也暂停。','Added procedural wind, stereo rain, roof patter and thunder. Sound follows actual rain and wind, with roof shelter based on camera position. Thunder follows lightning events with distance-based delay, direction and attenuation. Includes enable, mute, volume and an output meter; audio pauses with the scene or hidden page.')}</p><p class="muted">${t('声音由 Web Audio 合成，没有新增音频素材下载；属于氛围效果，并非完整建筑声学模拟。','Web Audio synthesis adds no audio downloads. This is an atmospheric effect, not a full architectural acoustics simulation.')}</p></article>
 <article><time>2026-09-14 / 04</time><h3>${t('能力提取：风雨观测庭','Extraction: weather courtyard')}</h3><p>${t('新增程序化庭院，复用上游体积云、云影、昼夜、降雨、湿润历史与反射管线。省去沙漠、植被、角色和地表纹理阵列，提供四个机位、两档预算、暂停与观察记录导出。雨粒子 5,000、水花 350、表面捕获 512²、天气过渡 12 秒。','A procedural courtyard reuses clouds, shadows, day/night, rain, wetness history and reflections. No desert, vegetation, player or ground arrays. Four viewpoints, two budgets, pause and session export. Uses 5,000 rain particles, 350 splashes, 512² capture and 12s transitions.')}</p><a href="/lab/" target="_top">${t('打开独立演示 →','Open the demo →')}</a></article>
 <article><time>2026-09-14 / 01</time><h3>${t('固定版本，运行库本身','Pin the version and run the original')}</h3><p>${t('创建 004 子项目；用原始沙漠、神庙与控制面板演示能力。原始文件按需下载，校验 Git blob 哈希后缓存，不提交完整上游仓库。','Created project 004 and ran the original desert, temple and controls. Files are fetched on demand and checked against Git blob hashes; the complete upstream repository is not committed.')}</p><p class="muted">${t('证据：原版 7 张截图、入口/模块/WASM 校验；232 个缓存文件字节内容复核通过。','Evidence: seven original screenshots, entry/module/WASM checks and verified contents of 232 cached files.')}</p></article>
 <article><time>2026-09-14 / 02</time><h3>${t('观察天空、昼夜和降雨','Observe skies, time and rain')}</h3><p>${t('实际切换 Earth、Orbital / Halo、Shieldworld；对比 10.5h、18.5h、24h；等待 Rain 和 Dark Storm 过渡完成，观察雨丝与地面水迹。','Switched Earth, Orbital / Halo and Shieldworld; compared 10.5h, 18.5h and 24h; waited for Rain and Dark Storm transitions and observed streaks and wet ground.')}</p><p class="muted">${t('闪电按钮出现排队反馈，但未抓到闪电瞬间；默认 Shieldworld 截图未包含巨星圆盘和破碎月球。帧率读数仅供观察，不构成基准测试。','The lightning button showed queue feedback, but no strike instant was captured. The default Shieldworld screenshot excludes the giant disc and fragmented moon. FPS readings are observations, not benchmarks.')}</p></article>
 <article><time>2026-09-14 / 03</time><h3>${t('中文界面与实践入口','Chinese UI and a practice entry')}</h3><p>${t('新增默认中文、可切换英文的界面适配；覆盖控件、加载阶段、天气过渡和操作提示。语言偏好保存在本机；实践入口可在演示中打开，关闭后继续当前场景。','Added a Chinese-first UI with English switching for controls, loading stages, weather transitions and instructions. Preference stays on this device. The journal opens over the demo and closes back to the current scene.')}</p><p class="muted">${t('改动限于界面适配、记录页和本地服务；上游引擎与场景模块仍按固定哈希提供。此轮没有降低画质或裁剪资源。','Changes are limited to UI adaptation, this journal and the local server. Upstream engine and scene modules remain hash-pinned. This iteration does not reduce quality or trim assets.')}</p></article>
 </div><div class="callout"><h3>${t('还没有验证什么','What remains unverified')}</h3><p>${t('实际显存/内存峰值、各渲染通道 GPU 耗时、手机性能、长期稳定性、所有云型与天气组合、完整雨后干燥、屋檐遮雨和全部角色碰撞。原版出现过 uv 属性警告，未将其描述为无警告运行。','Peak RAM/VRAM, per-pass GPU timing, mobile performance, long-term stability, every cloud/weather combination, a full drying cycle, roof shelter and all player collisions remain unverified. Original UV-attribute warnings were observed.')}</p></div></section>
 <section id="gallery"><h2>${t('原版实测截图','Original-demo screenshots')}</h2><p class="muted">${t('以下来自第一轮原版验证，因此保留英文界面；不是本轮中文界面的截图，也没有生成或合成效果。','These were captured during the first original-demo run and retain English controls. They are not captures of the new Chinese UI, and were not generated or composited.')}</p><div class="gallery">${shots.map(s=>`<figure><a href="/research-assets/${s[0]}" target="_blank" rel="noopener"><img loading="lazy" src="/research-assets/${s[0]}" alt="${t(s[1],s[2])}"></a><figcaption>${t(s[1],s[2])}</figcaption></figure>`).join('')}</div></section>
 <div class="sources"><strong>${t('固定版本依据','Pinned-version sources')}</strong><br><a href="${upstream}engine/sky_system.js" target="_blank" rel="noopener">${t('天空源码','Sky source')}</a><a href="${upstream}engine/quality_presets.js" target="_blank" rel="noopener">${t('画质参数','Quality presets')}</a><a href="${upstream}docs/SKY_SYSTEM_INTEGRATION.md" target="_blank" rel="noopener">${t('云影与缓存取舍','Cloud shadows & cache tradeoffs')}</a><a href="${upstream}engine/RAIN.md" target="_blank" rel="noopener">${t('降雨与地表水','Rain & surface water')}</a><a href="${upstream}KNOWN_ISSUES.md" target="_blank" rel="noopener">${t('已知限制','Known limitations')}</a><a href="/resource-report.json" target="_blank">${t('本次资源统计','Resource snapshot')}</a><a href="/original/" target="_blank" rel="noopener">${t('打开未汉化的原版入口','Open original English entry')}</a></div>
 <footer>${t('代码 MIT；素材分别授权。原版截图及素材权利归对应作者。本研究仅本地运行，尚未部署。','Code is MIT; assets have separate terms and retain their authors’ rights. This research runs locally and is not deployed.')}<br>commit: <code>${commit}</code></footer>`;
}
document.getElementById('journal-language').addEventListener('change',event=>{lang=event.target.value;try{localStorage.setItem('eanpa-research-language',lang);}catch{}render();});
window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===parent&&event.data?.type==='eanpa-language'){lang=event.data.lang==='en'?'en':'zh';if(report)render();}});
try{const response=await fetch('/resource-report.json');if(!response.ok)throw Error(response.status);report=await response.json();render();}catch{document.getElementById('journal').textContent=t('资源记录读取失败，请刷新后重试。','Could not load the resource snapshot. Please reload.');}
