export const SITE = 'https://yydshly.github.io/0913_codex_project/';
export const exhibits = [
  {id:'railway',project:'003',title:'白鹭河谷',en:'VALLEY IN SEASONS',zone:'山水与天气',type:'四季铁路场景',color:'#789b67',position:[-8,-11],image:'railway.png',alt:'白鹭河谷 V38 春季实际场景，山林、铁路与跌水',caption:'003 · V38 春季实际效果',summary:'一列小火车，穿过不断变化的四季。',skills:['三种地形构图与四季切换','列车、站房和人物生活','水流、植被与动物活动'],try:'参观车站、拱桥与河岸三个看点；揭开站房屋顶，再在同一机位比较春秋。',boundary:'风格化场景原型；不是测绘地形或完整生态模拟。',source:'本仓库独立场景，源自 Mountain Railway Diorama 研究。',path:'003-mountain-railway-diorama/scene.html',research:'003-mountain-railway-diorama/guide.html'},
  {id:'weather',project:'004',title:'听雨山居',en:'A HOUSE IN THE RAIN',zone:'山水与天气',type:'天气与声音体验',color:'#609db1',position:[8,-11],image:'weather.jpg',alt:'听雨山居实际雨景，屋檐、院落与声音控件',caption:'004 · 檐下雨景实际效果',summary:'在屋檐下，看看一场雨如何改变庭院。',skills:['晴雨、昼夜、雪与冰雹','地面水迹、雨滴和波纹','露天与檐下的声音层次'],try:'切换晴天和降雨，走到屋檐下，再观察地面与远处山林。',boundary:'声音需在作品内开启；天气过渡与初次加载需要时间。',source:'本仓库庭院场景，天气能力研究自 Eanpa Sky。',path:'004-eanpa-sky/lab/',research:'004-eanpa-sky/'},
  {id:'nature',project:'008',title:'山林生成工坊',en:'THE SHAPE OF NATURE',zone:'地形与运动',type:'道路、地表与树木',color:'#bd9352',position:[-8,1],image:'nature.png',alt:'自然环境实验中的泥土道路、松林与坡面草地',caption:'008 · 道路与地表实际效果',summary:'从一条土路开始，理解一片山林怎样长出来。',skills:['道路贴合地形与路面过渡','单株树木与成片森林','草、岩石和地表材质组合'],try:'沿道路近看地面，再观察树干和远处树冠，比较各自承担的细节。',boundary:'限定地形与配置下的生成原型；不是任意路网或生态生成器。',source:'本仓库独立自然环境与共享组件研究。',path:'008-terrain-motion-lab/outdoor.html?layout=valley&view=sunrise#stage',research:'008-terrain-motion-lab/capabilities.html'},
  {id:'motion',project:'010',title:'松脊驾驶练习',en:'LEARNING THE CORNER',zone:'地形与运动',type:'驾驶与即时反馈',color:'#c97954',position:[8,1],image:null,alt:'',caption:'展台赛道为导览示意；进入查看实际驾驶场',summary:'同一个弯，试试两种路线与不同的刹车时机。',skills:['自由转向、加速与制动','内外路线和路面抓地差异','检查点、罚时与驾驶示范'],try:'先看内线示范，再自己驾驶。转弯前松开油门，试着更早制动。',boundary:'平面运动与视觉倾斜模型，未实现完整悬挂和实车物理。',source:'本仓库独立驾驶原型，Mini Moto 用作研究参考。',path:'010-mini-moto-comparison/ride.html',research:'010-mini-moto-comparison/'},
  {id:'city',project:'009',title:'城景图鉴',en:'PLACES WORTH A VISIT',zone:'图鉴与界面',type:'城市与景点表达',color:'#aa9a66',position:[-8,13],image:'city.png',alt:'西安城市景区图鉴样稿的实际展示页面',caption:'009 · 西安样稿展示；画中插画为用户样稿',summary:'把一个城市值得探索的地方，放到一张图中。',skills:['景点筛选与特色说明','区域图鉴和细节查看','地点来源与位置核对'],try:'先看西安样稿整体，再查看具体地点；把画面表达与位置依据分开理解。',boundary:'当前样稿有已记录的位置问题，不能作为准确导航地图。',source:'用户样稿与本仓库内容、地理核对研究。',path:'009-city-landmark-map/',research:'009-city-landmark-map/archive.html'},
  {id:'visual',project:'011',title:'界面与感知',en:'MOTION WITH MEANING',zone:'图鉴与界面',type:'内容、设计与动效',color:'#9780b3',position:[8,13],image:'visual.png',alt:'前端视觉实验室的听雨山居雪景与可融冰霜实际页面',caption:'011 · 天气作品页与冰霜实际效果',summary:'让进入、切换和返回，都有清楚的视觉回应。',skills:['内容结构与视觉设计','进入、展开和返回的动效','云雾、冰霜等局部场景效果'],try:'从看图体验进入天气作品，切换晴雨雪，再展开图片并返回。',boundary:'局部页面特效不等于天气仿真；部分效果取决于浏览器能力。',source:'本仓库前端实验室，包含 GSAP 与 Canvas UI 的研究实践。',path:'011-frontend-visual-lab/',research:'011-frontend-visual-lab/research.html'}
];
export const getExhibit = id => exhibits.find(item => item.id === id) || exhibits[0];
export const adjacent = (id, step) => exhibits[(exhibits.findIndex(x=>x.id===getExhibit(id).id)+step+exhibits.length)%exhibits.length];
export function exhibitUrl(id,kind='path') {const item=getExhibit(id); return new URL(item[kind],SITE).href;}
