import {exhibits,getExhibit,adjacent,exhibitUrl} from './exhibits.mjs';
const $=id=>document.getElementById(id);let selected=getExhibit(location.hash.slice(1)),hall=null,frameTimer=null;let returnFocus=null;
for(const item of exhibits){const b=document.createElement('button');b.className='exhibit-chip';b.style.setProperty('--chip',item.color);b.dataset.id=item.id;b.setAttribute('aria-label','查看'+item.title);b.innerHTML=`<span class="chip-no">${item.project}</span><span><span class="chip-title">${item.title}</span><span class="chip-type">${item.type}</span></span>`;b.onclick=()=>select(item.id);$('exhibit-nav').append(b);}
function select(id,move=true){selected=getExhibit(id);const x=selected;document.documentElement.style.setProperty('--accent',x.color);$('zone').textContent=x.zone;$('project').textContent='展品 '+x.project;$('exhibit-en').textContent=x.en;$('exhibit-title').textContent=x.title;$('summary').textContent=x.summary;$('caption').textContent=x.caption;$('cover').hidden=false;$('cover-image').hidden=!x.image;if(x.image){$('cover-image').src='assets/'+x.image;$('cover-image').alt=x.alt;}$('skills').replaceChildren(...x.skills.map(s=>{const li=document.createElement('li');li.textContent=s;return li;}));$('try').textContent=x.try;$('source').textContent=x.source;$('boundary').textContent=x.boundary;$('enter').textContent=x.id==='railway'?'进入参观样板 ↗':'进入作品 ↗';$('research').href=exhibitUrl(x.id,'research');document.querySelectorAll('.exhibit-chip').forEach(b=>b.setAttribute('aria-current',String(b.dataset.id===id)));hall?.select(id,move);if(move){document.querySelector('.hall-heading').classList.add('compact');document.querySelector('.hall-heading h1').textContent=x.title+' · 展台';$('hall-caption').textContent='近看主题缩景，进入作品体验完整效果。';}history.replaceState(null,'','#'+id);$('announce').textContent='已选择'+x.title+'，'+x.type;}
function overview(){hall?.overview();document.querySelector('.hall-heading').classList.remove('compact');document.querySelector('.hall-heading h1').innerHTML='六件作品，<br>六种看世界的方式。';$('hall-caption').textContent='点击展台近看，或从下方选择作品。';}
$('overview').onclick=overview;$('brand').onclick=e=>{e.preventDefault();overview();};$('prev').onclick=()=>select(adjacent(selected.id,-1).id);$('next').onclick=()=>select(adjacent(selected.id,1).id);
$('cover-image').addEventListener('error',()=>{$('cover').hidden=true;});
function enter(){if(selected.id==='railway'){location.href='valley.html';return;}returnFocus=document.activeElement;const item=selected;const url=exhibitUrl(item.id);$('experience-title').textContent=item.project+' / '+item.title;$('open-alone').href=url;$('experience-status').textContent='正在打开作品页面…';$('experience').showModal();document.body.classList.add('experience-open');hall?.setActive(false);$('frame-host').replaceChildren();const frame=document.createElement('iframe');frame.title=item.title+'完整作品';frame.referrerPolicy='no-referrer';frame.setAttribute('allow','fullscreen; autoplay');frame.setAttribute('sandbox','allow-scripts allow-same-origin allow-pointer-lock allow-downloads');frame.addEventListener('load',()=>{clearTimeout(frameTimer);$('experience-status').textContent='作品页面已打开，场景资源可能仍在加载。';});frame.src=url;$('frame-host').append(frame);frameTimer=setTimeout(()=>{$('experience-status').textContent='加载较慢，可用右上角“单独打开”。';},20000);$('close-experience').focus();}
function cleanup(){clearTimeout(frameTimer);$('frame-host').replaceChildren();document.body.classList.remove('experience-open');hall?.setActive(true);returnFocus?.focus();}
$('enter').onclick=enter;$('close-experience').onclick=()=>$('experience').close();$('experience').addEventListener('close',cleanup);$('retry').onclick=()=>location.reload();
window.addEventListener('keydown',e=>{if($('experience').open)return;if(e.target.closest('button,a,summary,input,textarea,select'))return;if(e.key==='ArrowRight'){e.preventDefault();select(adjacent(selected.id,1).id);}if(e.key==='ArrowLeft'){e.preventDefault();select(adjacent(selected.id,-1).id);}if(e.key==='Escape')overview();});
select(selected.id,false);
try{const {createHall}=await import('./hall.mjs');hall=await createHall($('canvas-host'),$('labels'),select);hall.select(selected.id,false);hall.setActive(!$('experience').open);$('loading').hidden=true;}
catch(error){console.error('展馆加载失败',error);$('loading').hidden=true;$('fallback').hidden=false;$('labels').hidden=true;}
window.addEventListener('pagehide',()=>{clearTimeout(frameTimer);$('frame-host').replaceChildren();hall?.dispose();});
window.addEventListener('pageshow',event=>{if(event.persisted)location.reload();});
