const upstream='https://github.com/nickfromlater/whistlevale/blob/f3d769e8ea54d2f5a47d12f27773541b484c6302/';
export const lessons=[
 {title:'第一个三角形',short:'三角形',see:'先把三个坐标变成屏幕上的一个面。',change:'JavaScript 提供顶点；顶点着色器把坐标投影到屏幕；显卡覆盖三角形区域，片元着色器决定颜色。',try:'进入下一步，看看同一套绘制流程怎样接收更多三角形。',three:'BufferGeometry、材质和 renderer.render() 封装了数据上传、程序选择与绘制调用。',native:'Builder.vertex() 组织顶点，uploadTriangles() 将数据交给显卡。',source:upstream+'railway.js#L49',code:'gl.bindBuffer(gl.ARRAY_BUFFER, vertexBuffer);\ngl.bufferData(gl.ARRAY_BUFFER, vertices, gl.STATIC_DRAW);\ngl.drawElements(gl.TRIANGLES, count, gl.UNSIGNED_INT, 0);'},
 {title:'把三角形组成车站',short:'形体',see:'车站、屋顶、长椅和小车出现了。此时每种表面只有基色。',change:'几何生成器把盒体、圆柱等拆成三角形，再给每个顶点写入位置、朝向、颜色与材料编号。启用深度测试，近处的表面遮住远处。',try:'拖动画面观察屋顶与站房的遮挡。几何从这一步起保持相同，后续变化主要来自渲染处理。',three:'BoxGeometry、CylinderGeometry、Mesh 和场景层级，承担大部分基础组织工作。模型比例与零件仍需要作者设计。',native:'makeLoco() 用盒体、圆柱和重复排列构造机车零件。',source:upstream+'railway.js#L838',code:'const normal = normalize(cross(sub(b, a), sub(c, a)));\nvertices.push(...position, ...normal, ...color, materialId);\ngl.enable(gl.DEPTH_TEST);'},
 {title:'光照带来体积感',short:'光照',see:'迎光面亮，背光面暗，同一块颜色开始有体积。',change:'用表面法线与光线方向的点积计算受光量，再补少量环境光。法线是一根代表“表面朝向”的方向向量。',try:'拖动“光线方向”，观察屋顶两侧的明暗交换。也可以切换“表面朝向”，查看法线的颜色表示。',three:'DirectionalLight、环境光与内置受光材质处理这些计算。',native:'片元着色器组合日光、环境光与夜间灯光。',source:upstream+'railway.js#L218',code:'float diffuse = max(dot(normalize(normal), lightDirection), 0.0);\nvec3 color = baseColor * (ambient + sunlight * diffuse);'},
 {title:'表面有了材料差别',short:'材质',see:'桌沿出现木纹，屋顶有拼缝，车漆和金属会反光。',change:'着色器根据材料编号执行不同公式：坐标生成条纹或砖缝，表面朝向与视线共同影响高光。此处没有加载纹理图片。',try:'近看站房，改变“车漆与金属粗糙度”。越光滑，高光越集中；再关闭本步，对照只有光照的结果。',three:'内置材质提供粗糙度和金属度；程序纹理可用 ShaderMaterial 或定制着色器实现。',native:'材料编号进入不同分支，分别计算木纹、砖缝、车漆与金属反光。',source:upstream+'railway.js#L182',code:'if (materialId == WOOD) color *= woodPattern(worldPosition);\nfloat specular = pow(max(dot(normal, halfDirection), 0.0), shininess);'},
 {title:'让屋檐投下阴影',short:'阴影',see:'车站和小车在地面投下影子，位置关系更明确。',change:'先从光源方向画一张深度图，再从相机方向画场景。比较两者深度，判断表面是否被挡住。小范围多次采样使边缘稍柔和。',try:'移动光线，观察地面的影子；切换“光源深度图”，看见第一遍绘制的真实中间结果。',three:'开启投影与接收阴影后，Three.js 帮助安排额外绘制、纹理与深度比较。',native:'原作缓存静态阴影，再叠加动态列车；本实验只缓存整张未变化的阴影图。',source:upstream+'railway.js#L485',code:'gl.bindFramebuffer(gl.FRAMEBUFFER, shadowFramebuffer);\ndrawSceneFromLight();\ngl.bindFramebuffer(gl.FRAMEBUFFER, null);\ndrawSceneFromCameraWithShadowDepth();'},
 {title:'时间驱动物体',short:'动画',see:'小车沿直轨往返，轮上的标记随着位移转动。',change:'每帧根据经过时间更新小车位置，用位移除以轮半径计算转角，再更新模型矩阵。几何数据继续复用。',try:'暂停后拖动画面，观察模型仍可从任意角度观看；切换光线，确认影子属于当前小车位置。',three:'Object3D 变换、动画系统可以管理更新；运行路线与车轮关系仍需编写。',native:'原作根据轨道与车轮相位计算列车位置、曲柄、连杆与滑块。',source:upstream+'trains.js#L298',code:'const x = Math.sin(time * 0.44) * 2.7;\nconst wheelAngle = -x / wheelRadius;\nconst model = translation(x, 0.235, 2.5);'},
 {title:'把场景当作微缩模型拍摄',short:'摄影',see:'焦点落在站房附近，较远处变柔和；亮度经过统一整理。',change:'先把场景画到颜色和深度纹理，再画一次全屏三角形。根据离焦距离采样邻近颜色，最后进行色调映射和显示颜色转换。',try:'调整“景深强度”和“曝光”，再点击“去掉本步，对照”。相机、模型与光线保持当前设置。',three:'渲染目标与后处理通道负责组织多遍绘制；着色算法可以自己编写。',native:'原作 POSTFS 还包含泛光、抗锯齿处理、暗角与细颗粒；本实验只实现景深、色调与颜色转换。',source:upstream+'railway.js#L258',code:'float blur = abs(depth - focusDepth) / max(depth, 1.0);\nvec3 color = depthAwareBlur(sceneColor, sceneDepth, blur);\noutColor = vec4(toSRGB(aces(color * exposure)), 1.0);'}
];
