import * as T from './vendor/three.module.js';
import {surface,enrichWorld,detailedActor} from './art.js';
import {buildChapter,journal} from './chapter.js';
import {buildDungeons} from './dungeon.js';
import {MAPS} from './maps.mjs';
import {TALENTS,CAPACITY,combatStats} from './equipment.mjs';
import {createGame,update,action,PORTAL,OBSTACLES,distance,findPath,POINTS,TREE_POINTS,objective,nearby,interact,service,snapshot,restore,getPoints,inventoryAction} from './game-state.mjs';
const $=s=>document.querySelector(s),canvas=$('#world');
let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('#loading').innerHTML='<p>当前浏览器无法启用 3D 图形。<br>请开启硬件加速后重新打开。</p>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new T.Scene();scene.background=new T.Color('#142222');scene.fog=new T.FogExp2('#111c21',.005);
const camera=new T.OrthographicCamera(-20,20,15,-15,.1,150);camera.position.set(27,33,27);camera.lookAt(0,0,0);
scene.add(new T.HemisphereLight('#a8ccd6','#3e3427',1.05));
const moon=new T.DirectionalLight('#b4d1de',2.1);moon.position.set(-15,26,8);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);Object.assign(moon.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:.5,far:80});moon.shadow.normalBias=.035;scene.add(moon);
const mats=new Map();function mat(c,emissive){const key=c+'|'+emissive;if(!mats.has(key)){const wood=['#5a4b32','#65543a','#45352a','#655640','#3b3027','#302f27','#49493a','#5e5841','#65503b','#67573f','#756348','#786449','#8f7850','#695c44','#75463b'].includes(c);mats.set(key,new T.MeshStandardMaterial({color:c,roughness:wood?.87:.73,map:emissive?null:surface(wood?'wood':'stone'),bumpMap:emissive?null:surface(wood?'wood':'stone'),bumpScale:wood?.045:.085,...(emissive?{emissive,emissiveIntensity:4}: {})}));}return mats.get(key);}
const boxG=new T.BoxGeometry(1,1,1);function box(x,y,z,w,h,d,c,parent=scene){const m=new T.Mesh(boxG,mat(c));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function cylinder(x,y,z,rt,rb,h,c,n=10,parent=scene){const m=new T.Mesh(new T.CylinderGeometry(rt,rb,h,n),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function sphere(x,y,z,r,c,parent=scene){const m=new T.Mesh(new T.IcosahedronGeometry(r,1),mat(c));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
let seed=173;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
box(0,-.55,0,56,1,56,'#242d29');box(0,-1.05,0,57,.35,57,'#101e1d');
const stoneShape=new T.Shape();stoneShape.moveTo(-.46,-.45);stoneShape.lineTo(.44,-.48);stoneShape.lineTo(.49,.39);stoneShape.lineTo(-.42,.47);stoneShape.closePath();
const stoneGeo=new T.ExtrudeGeometry(stoneShape,{depth:.7,bevelEnabled:true,bevelSize:.045,bevelThickness:.07,bevelSegments:1,steps:1});stoneGeo.rotateX(-Math.PI/2);stoneGeo.center();
const groundSurface=new T.Mesh(new T.PlaneGeometry(56,56),new T.MeshStandardMaterial({color:'#665e4b',map:surface('stone'),bumpMap:surface('stone'),bumpScale:.17,roughness:.94}));groundSurface.rotation.x=-Math.PI/2;groundSurface.position.y=-.07;groundSurface.receiveShadow=true;scene.add(groundSurface);
const cobbles=new T.InstancedMesh(stoneGeo,mat('#aeb4b3'),98*98);cobbles.receiveShadow=true;const dummy=new T.Object3D(),color=new T.Color();let index=0;
for(let x=-49;x<49;x++)for(let z=-49;z<49;z++){
 const wx=x*.56+(z%2)*.28,wz=z*.56;const worn=Math.sin(wx*.55+Math.sin(wz*.3)*2)+Math.sin(wz*.61+wx*.21);const missing=worn>1.02&&rand()>.17;
 dummy.position.set(wx+(rand()-.5)*.08,-.018+rand()*.04,wz+(rand()-.5)*.07);dummy.rotation.set((rand()-.5)*.035,(rand()-.5)*.18,(rand()-.5)*.03);dummy.scale.set(missing?0:.47+rand()*.06,.07+rand()*.07,missing?0:.45+rand()*.07);dummy.updateMatrix();cobbles.setMatrixAt(index,dummy.matrix);color.setHSL(.13+rand()*.06,.04+rand()*.11,.32+rand()*.14);cobbles.setColorAt(index++,color);
}scene.add(cobbles);
// Uneven dirt, grass, scattered stone and raised edges break the tile grid.
for(let i=0;i<220;i++){let x=(rand()-.5)*35,z=(rand()-.5)*35;if(Math.hypot(x,z)<3)continue;const m=sphere(x,.06,z,.06+rand()*.19,rand()>.5?'#36403b':'#6a6758');m.scale.y=.45;}
for(let i=0;i<210;i++){const x=(rand()-.5)*36,z=(rand()-.5)*36;if(Math.abs(x)<9&&Math.abs(z)<7&&rand()>.1)continue;const h=.16+rand()*.3;const m=new T.Mesh(new T.ConeGeometry(.09,h,3),mat('#465144'));m.position.set(x,h/2,z);scene.add(m);}
for(let i=-27;i<=27;i++){box(i,.18,-27,.95,.48,.7,'#49534b');box(-27,.18,i,.7,.48,.95,'#49534b');if(Math.abs(i)>4)box(i,.18,27,.95,.48,.7,'#39453f');box(27,.18,i,.7,.48,.95,'#39453f');}
const flames=[],lights=[];
function fire(x,z,scale=1,y=0){const group=new T.Group();group.position.set(x,y,z);scene.add(group);for(let i=0;i<3;i++){const mesh=new T.Mesh(new T.ConeGeometry((.22-i*.05)*scale,(.95-i*.15)*scale,5),new T.MeshBasicMaterial({color:['#e95c17','#ffb434','#ffe7a0'][i],transparent:true,opacity:.88}));mesh.position.y=(.4+i*.12)*scale;group.add(mesh);flames.push({mesh,base:mesh.scale.y,phase:rand()*6});}const light=new T.PointLight('#ff8c3d',12*scale,8*scale,2);light.position.set(x,y+1.4*scale,z);scene.add(light);lights.push(light);return group;}
function torch(x,z){box(x,1.05,z,.15,2,.15,'#3b3027');box(x,1.9,z,.32,.24,.32,'#554b39');fire(x,z,.58,1.92);}
function building(o,variant){const {x,z,w,d}=o;const h=3.4;box(x,.25,z,w+.3,.5,d+.3,'#53564b');box(x,1.85,z,w,h,d,variant?'#625b48':'#77705b');for(let j=0;j<4;j++){for(let k=0;k<Math.floor(w);k++)box(x-w/2+.5+k, .65+j*.7,z+d/2+.03,.92,.6,.1,j%2?'#6d6b57':'#646552');}
 for(const dx of [-w/2+.1,w/2-.1])for(const dz of [-d/2+.1,d/2-.1])box(x+dx,2,z+dz,.22,3.6,.22,'#302f27');box(x,3.35,z,w+.2,.24,d+.2,'#34352d');
 for(const side of [-1,1]){const roof=box(x+side*w*.25,3.95,z,w*.65,.2,d+.8,'#303a39');roof.rotation.z=-side*.48;for(let k=0;k<7;k++){const beam=box(x+side*w*.25,4.08,z-d/2-.3+k*(d+.6)/6,w*.66,.1,.08,'#4e5146');beam.rotation.z=-side*.48;}}box(x,4.57,z,.22,.22,d+.9,'#666555');
 box(x+.25,1.22,z+d/2+.08,1.05,2.05,.15,'#282d28');for(let k=0;k<5;k++)box(x-.18+k*.21,1.22,z+d/2+.17,.035,1.9,.06,'#59513c');box(x+.58,1.2,z+d/2+.23,.12,.12,.08,'#a89256');
 for(const dx of [-w*.32,w*.32]){box(x+dx,2.15,z+d/2+.1,.75,.88,.18,'#292e29');const pane=box(x+dx,2.15,z+d/2+.21,.58,.7,.03,'#f7b95e');pane.material=mat('#ad6731','#d97521');box(x+dx,2.15,z+d/2+.25,.06,.78,.05,'#4e4532');box(x+dx,2.15,z+d/2+.25,.7,.06,.05,'#4e4532');}
 box(x, .28,z+d/2+.7,1.7,.3,1.2,'#707262');torch(x+w/2+.5,z+d/2+.3);}
OBSTACLES.slice(0,3).forEach(building);
function crate(x,z,size=1){box(x,size*.5,z,size,size,size,'#5a4b32');for(const dx of [-.43,.43])box(x+dx*size,size*.5,z+size*.51,.09,size,.08,'#292e27');for(const y of [.12,.88])box(x,y*size,z+size*.52,size,.08,.08,'#928062');}
for(const o of OBSTACLES.slice(3,5)){crate(o.x,o.z,1.3);crate(o.x+1,o.z+.7,.9);crate(o.x-.2,o.z+.1,.65);}
for(const p of [[-11,-5],[5,-10],[12,-3],[-9,8],[8,11]]){cylinder(p[0],.55,p[1],.42,.38,1,'#65543a');for(const y of [.2,.75])cylinder(p[0],y,p[1],.44,.44,.08,'#292f2b');}
// The fence frames the play space without obstructing the foreground camera.
for(let x=-16;x<17;x+=.8){if(Math.abs(x)>3)box(x,.9,-16,.16,1.8,.16,'#49493a');if(x>6)box(16,.9,x,.16,1.8,.16,'#454737');}for(const x of [-10,10]){box(x,1.25,-16,13,.12,.13,'#5e5841');box(x,.6,-16,13,.12,.13,'#5e5841');}
function tree(x,z){cylinder(x,1.2,z,.13,.33,2.4,'#4a4538',6);for(let j=0;j<3;j++){const m=new T.Mesh(new T.ConeGeometry(1.65-j*.35,2.5,7),mat(j===1?'#293e37':'#20372f'));m.position.set(x,2.3+j*.9,z);m.castShadow=true;scene.add(m);}}
for(const p of TREE_POINTS)tree(...p);
const camp={x:-7,z:5};for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const rock=sphere(camp.x+Math.cos(a)*.95,.16,camp.z+Math.sin(a)*.95,.23,'#676b5c');rock.scale.y=.65;}
for(let i=0;i<4;i++){const wood=box(camp.x,.2,camp.z,1.4,.19,.2,'#45352a');wood.rotation.y=i*.8;}fire(camp.x,camp.z,1.25,.2);box(-8,.4,7,2,.5,.55,'#655640');torch(6,5);torch(13,10);torch(-13,-3);
const portal=new T.Group();portal.position.set(PORTAL.x,.08,PORTAL.z);scene.add(portal);cylinder(0,0,0,1.8,1.9,.2,'#4b5f5b',12,portal);cylinder(0,.12,0,1.36,1.36,.06,'#79d5e0',32,portal).material=mat('#4abacb','#258fa4');
const ring=new T.Mesh(new T.TorusGeometry(1.43,.045,6,64),new T.MeshBasicMaterial({color:'#9feef2'}));ring.rotation.x=Math.PI/2;ring.position.y=.18;portal.add(ring);
for(let i=0;i<10;i++){const a=i/10*Math.PI*2;const stone=box(Math.cos(a)*1.9,.15,Math.sin(a)*1.9,.55,.3,.45,'#7e9d95',portal);stone.rotation.y=-a;const rune=box(Math.cos(a)*1.75,.32,Math.sin(a)*1.75,.16,.02,.09,'#94e9f1',portal);rune.material=mat('#a2f2f6','#50bfde');}
const portalLight=new T.PointLight('#5ce3ff',18,9,2);portalLight.position.set(PORTAL.x,1.6,PORTAL.z);scene.add(portalLight);
const animateWorld=enrichWorld({scene,box,cylinder,sphere,mat,portal,PORTAL,OBSTACLES,flames,lights});
function actor(enemy=false,boss=false){return detailedActor(scene,enemy,boss);}
function disposeActor(a){scene.remove(a.g);const geometries=new Set(),materials=new Set();a.g.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)materials.add(o.material);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}
const hero=actor();const selection=new T.Mesh(new T.RingGeometry(.5,.54,48),new T.MeshBasicMaterial({color:'#c9d6b4',transparent:true,opacity:.48,side:T.DoubleSide}));selection.rotation.x=-Math.PI/2;selection.position.y=.13;scene.add(selection);
let state=createGame(),paused=false,last=performance.now(),soundOn=false,audioCtx;const enemyMeshes=new Map(),dropMeshes=new Map(),effects=[],keys=new Set();let joy={x:0,z:0},noticeUntil=0,shake=0,hitStop=0,combo=0;const numbers=[];let movePath=[],attackTarget=null,repath=0,pendingInteraction=null;const SAVE_KEY='emberfall-chapter-v3';let checkpointText=snapshot(state),storedSave=null;try{const saved=localStorage.getItem(SAVE_KEY)||localStorage.getItem('emberfall-chapter-v2');if(restore(saved)){storedSave=saved;checkpointText=saved;}}catch{}
const chapter=buildChapter({scene,box,cylinder,sphere,mat,actor,tree,onPoint:travelTo});
const overworld=new T.Group();for(const child of [...scene.children])if(child!==hero.g&&child!==selection&&child!==chapter.guide&&!child.isHemisphereLight&&!child.isDirectionalLight)overworld.add(child);scene.add(overworld);
const dungeons=buildDungeons({scene,box,cylinder,sphere,mat,actor});
let renderedArea=null;
function syncArea(){if(renderedArea===state.area)return;renderedArea=state.area;overworld.visible=state.area==='overworld';dungeons.setArea(state.area);scene.background.set(MAPS[state.area].color);scene.fog.color.set(MAPS[state.area].color);moon.intensity=state.area==='overworld'?2.1:1.3;for(const a of enemyMeshes.values())disposeActor(a);enemyMeshes.clear();for(const m of dropMeshes.values()){scene.remove(m);m.geometry.dispose();}dropMeshes.clear();for(const e of effects){scene.remove(e.m);e.m.geometry.dispose();e.m.material.dispose();}effects.length=0;movePath=[];attackTarget=null;pendingInteraction=null;for(const n of numbers)n.el.remove();numbers.length=0;cameraFocus.set(state.player.x,0,state.player.z);routeButtons();resize();}
function routeButtons(){const routes=state.area==='overworld'?['west','east','altar','fire']:state.area==='crypt'?['lever-west','lever-east','descent','crypt-exit']:['ritual','depths-chest','depths-exit','rift-home'];const target=$('#route-options');target.replaceChildren();for(const id of routes){const p=getPoints(state).find(p=>p.id===id);const b=document.createElement('button');b.textContent=p.name.replace('共鸣机关','机关').replace('沉钟墓穴','墓穴');b.onclick=()=>travelTo(id);target.appendChild(b);}}

function tone(freq,duration=.08,type='triangle',vol=.04){if(!soundOn)return;try{audioCtx??=new AudioContext();audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.4,audioCtx.currentTime+duration);gain.gain.setValueAtTime(vol,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration);}catch{}}
function showNotice(text){$('#notice').textContent=text;$('#notice').style.opacity='1';noticeUntil=performance.now()+3000;}
function particles(x,z,c,count=12,y=.6){for(let i=0;i<count;i++){const m=new T.Mesh(new T.IcosahedronGeometry(.035+rand()*.04,0),new T.MeshBasicMaterial({color:c,transparent:true}));m.position.set(x,y,z);scene.add(m);effects.push({m,t:0,life:.4+rand()*.5,v:new T.Vector3((rand()-.5)*5,rand()*4,(rand()-.5)*5)});}}
function circle(x,z,c,max,life=.6){const m=new T.Mesh(new T.RingGeometry(.85,1,64),new T.MeshBasicMaterial({color:c,transparent:true,opacity:.85,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.set(x,.23,z);scene.add(m);effects.push({m,t:0,life,max});}
function floating(x,z,text,color='#f0d7a3'){const el=document.createElement('span');el.className='damage-number';el.textContent=text;el.style.color=color;$('#game').appendChild(el);numbers.push({el,x,z,t:0});}
function slash(x,z,face){combo++;const m=new T.Mesh(new T.RingGeometry(1.45,2.55,40,1,0,Math.PI*1.15),new T.MeshBasicMaterial({color:combo%3===0?'#a8e9ff':'#ffe2ae',side:T.DoubleSide,transparent:true,opacity:.9,blending:T.AdditiveBlending,depthWrite:false,toneMapped:false}));m.rotation.x=-Math.PI/2;m.rotation.z=-face+Math.PI*.04;m.position.set(x,.9,z);scene.add(m);effects.push({m,t:0,life:.21});}
function modal(title,body,button='继续旅程',mode='resume'){paused=true;keys.clear();joy={x:0,z:0};$('#modal-actions').replaceChildren();$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal-primary').textContent=button;$('#modal-primary').dataset.mode=mode;if(!$('#modal').open)$('#modal').showModal();}
function saveCheckpoint(){checkpointText=snapshot(state);try{localStorage.setItem(SAVE_KEY,checkpointText);$('#save-status').textContent='检查点已保存';}catch{$('#save-status').textContent='本次会话检查点';}}
function showHelp(){modal('旅人的手册','点击地面 / WASD：移动<br>点击敌人：追击 · J / 右键：近战<br>空格：闪避预警攻击 · Q：星陨<br>R：药剂 · E：附近交互 · B：行囊<br><br>先探索林地与采场，取得两枚封印后进入北方墓穴。启动上下层机关、救援斥候，击败熔心领主后带战利品回城。<br>M 查看区域地图；B 装备战利品并分配技能点。<br><br>篝火恢复并记录检查点；红色区域在收缩完成后造成伤害。');}
function restart(next=createGame()){state=next;renderedArea=null;dungeons.reset();syncArea();for(const a of enemyMeshes.values())disposeActor(a);enemyMeshes.clear();for(const m of dropMeshes.values()){scene.remove(m);m.geometry.dispose();}dropMeshes.clear();for(const e of effects){scene.remove(e.m);e.m.geometry.dispose();e.m.material.dispose();}effects.length=0;movePath=[];attackTarget=null;pendingInteraction=null;for(const n of numbers)n.el.remove();numbers.length=0;paused=false;keys.clear();hud();showNotice(state.stage==='intro'?'第一章 · 余火的请求\n与营地守夜人交谈。':'旅程继续\n'+objective(state).title);}
function retry(){const deaths=state.deaths;const loaded=restore(checkpointText)||createGame();loaded.deaths=Math.max(deaths,loaded.deaths);restart(loaded);}
function travelTo(id){if(paused)return;const poi=getPoints(state).find(p=>p.id===id);if(!poi)return;if(distance(state.player,poi)<2.7){interact(state,id);handleEvents();return;}const path=findPath(state.player,poi);if(!path.length){showNotice('此处无法抵达，请靠近后再试。');return;}movePath=path;attackTarget=null;pendingInteraction=id;circle(poi.x,poi.z,'#f3da91',.8,.55);}
function openService(kind,message=''){if(kind==='warden'){const intro=state.stage==='intro';modal('守夜人 · 伊芙',intro?'“星门的核心被拖进了北方裂隙。去朽木林地与沉石采场，取回两枚封印，才能唤醒断门祭坛。”<br><br>你可以自由选择路线。带上药剂，在红色攻击预警结束前闪开。':journal(state),'离开');if(intro)addDialogButton('接受委托 · 找回封印',()=>{service(state,'accept');$('#modal').close();paused=false;handleEvents();});if(state.scoutRescued&&!state.scoutReward)addDialogButton('领取斥候救援奖励',()=>{service(state,'claim-scout');handleEvents();openService('warden');});if(state.stage==='done')addDialogButton(`开启远征 ${state.cycle+2} · 保留装备与等级`,()=>{service(state,'expedition');handleEvents();$('#modal').close();paused=false;});}
else{modal('铁匠 · 余烬工坊',`余烬 <strong>${state.gold}</strong>　长剑 +${state.weapon}　护甲 +${state.armor}<p id="shop-note">${message||'每级武器增加 10 点近战伤害；每级护甲减少 3 点受击伤害。'}</p>`,'离开');for(const[type,label]of[['weapon',`强化长剑 · ${state.weapon>=2?'已满级':(state.weapon?55:30)+' 余烬'}`],['armor',`强化护甲 · ${state.armor>=2?'已满级':(state.armor?55:30)+' 余烬'}`],['buy','购买药剂 · 18 余烬']]){addDialogButton(label,()=>{service(state,type);const msg=state.events.findLast(e=>e.type==='notice')?.text||'';handleEvents();openService('forge',msg);},state[type]>=2&&type!=='buy');}addDialogButton('整理与出售装备',showJournal);}}
function addDialogButton(label,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=fn;$('#modal-actions').appendChild(b);}
function showJournal(){modal('旅人行囊',inventoryHTML(),'收起行囊');$('#modal-body').querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{inventoryAction(state,b.dataset.type,Number(b.dataset.item));handleEvents();showJournal();});$('#modal-body').querySelectorAll('[data-talent]').forEach(b=>b.onclick=()=>{inventoryAction(state,'learn',b.dataset.talent);handleEvents();showJournal();});}
function inventoryHTML(){const stats=combatStats(state),shop=getPoints(state).some(p=>p.id==='forge'&&distance(p,state.player)<3);const desc=i=>`斩击 +${i.attack} · 护甲 +${i.defense} · 星陨 +${i.spell}`;return `<div class="bag-summary">Lv. ${state.level}　斩击 ${stats.attack}　减伤 ${stats.defense}　星陨 ${stats.spell}<br>${state.gold} 余烬 · 行囊 ${state.inventory.length}/${CAPACITY} · 技能点 ${state.skillPoints}</div><div class="equipment-slots">${Object.entries(state.equipped).map(([slot,id])=>`<div><small>${{weapon:'武器',armor:'护甲',charm:'护符'}[slot]}</small><strong>${state.inventory.find(i=>i.id===id)?.name||'尚未装备'}</strong></div>`).join('')}</div><div class="inventory-grid">${state.inventory.map(i=>{const worn=state.equipped[i.slot]===i.id,old=state.inventory.find(v=>v.id===state.equipped[i.slot]);return `<article class="item-card ${i.rarity==='史诗'?'epic':''}"><small>${i.rarity} · ${{weapon:'武器',armor:'护甲',charm:'护符'}[i.slot]}</small><strong>${i.name}</strong><p>${desc(i)}</p>${old&&!worn?`<small>当前：${old.name}<br>${desc(old)}</small>`:''}<div><button data-type="equip" data-item="${i.id}" ${worn?'disabled':''}>${worn?'已装备':'装备'}</button>${shop&&!worn?`<button data-type="sell" data-item="${i.id}">出售 +${i.value}</button>`:''}</div></article>`;}).join('')||'<p class="bag-empty">战利品会在靠近时自动拾取。探索宝箱、击碎木桶或击败敌人，获得武器、护甲与护符。</p>'}</div><h3>战技研习</h3><div class="talent-grid">${Object.entries(TALENTS).map(([id,t])=>`<div><strong>${t.name} ${state.talents[id]}/${t.max}</strong><p>${t.description||t.desc||''}</p><button data-talent="${id}" ${!state.skillPoints||state.talents[id]>=t.max?'disabled':''}>研习 · 1 技能点</button></div>`).join('')}</div><p class="bag-foot">升级获得技能点。穿戴、研习与交易会保存进度；出售装备需要靠近营地铁匠。</p>`;}
function showWorldMap(){modal('边境远征图',`<div class="world-map-flow">${Object.entries(MAPS).map(([id,m],index)=>`<article class="region-card ${state.area===id?'current':''}"><small>0${index+1} · ${state.area===id?'当前位置':state.visited.includes(id)?'已探索':'尚未抵达'}</small><h3>${m.name}</h3><p>${m.level}</p><span>${id==='overworld'?`边境封印 ${state.seals.length}/2`:id==='crypt'?`共鸣机关 ${state.levers.length}/2 · 斥候${state.scoutRescued?'已获救':'待救援'}`:state.bossDead?'核心已取得':'熔心领主仍在深处'}</span></article>`).join('<div class="map-connector">↓ 阶梯连接 ↑</div>')}</div><p>区域通过入口与阶梯相连。折返保留清理进度，领主倒下后开启直达营地的回城裂隙。</p>`,'返回游戏');addDialogButton('追踪当前目标',()=>{$('#modal').close();paused=false;travelTo(objective(state).target);});}
$('#world-map').onclick=showWorldMap;

function showSaveTransfer(){modal('旅程存档', '<p>复制存档文字可在其他浏览器恢复。导入前会显示存档摘要；确认恢复会替换本浏览器的检查点。</p><label for="save-text">存档文字</label><textarea id="save-text" spellcheck="false"></textarea><p id="save-note">当前显示最近检查点。</p>','返回游戏');$('#save-text').value=checkpointText;addDialogButton('检查并恢复这份存档',()=>{const loaded=restore($('#save-text').value);if(!loaded){$('#save-note').textContent='无法识别这份存档，请检查是否完整复制。';return;}modal('恢复旅程',`位置：${MAPS[loaded.area].name}<br>Lv. ${loaded.level} · ${loaded.inventory.length} 件装备<br>${objective(loaded).title}<p>确认后替换当前检查点。</p>`,'取消');addDialogButton('确认恢复',()=>{restart(loaded);saveCheckpoint();$('#modal').close();paused=false;last=performance.now();});});}
$('#modal-primary').onclick=()=>{const mode=$('#modal-primary').dataset.mode;$('#modal').close();if(mode==='restart'){restart();saveCheckpoint();}else if(mode==='retry')retry();else if(mode==='load'){restart(restore(checkpointText)||createGame());$('#save-status').textContent='已读取检查点';if(state.phase==='won')state.phase='explore';}else paused=false;last=performance.now();canvas.focus();};
$('#modal').addEventListener('cancel',e=>{if(['won','dead'].includes(state.phase)){e.preventDefault();return;}paused=false;last=performance.now();});
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>travelTo(b.dataset.route));$('#journal').onclick=showJournal;$('#track').onclick=()=>travelTo(objective(state).target);$('#prompt').onclick=()=>act('interact');$('#help').onclick=showHelp;$('#pause').onclick=()=>{if(!$('#modal').open){modal('长夜暂歇','进度在接取任务、取得封印和篝火休息时保存。<br>死亡后可从最近检查点重试。');addDialogButton('查看行囊',showJournal);addDialogButton('备份 / 恢复存档',showSaveTransfer);addDialogButton('开始新旅程',()=>{modal('开始新的旅程','这会覆盖本浏览器的当前检查点。','确认开始','restart');});}};
$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').textContent='声音：'+(soundOn?'开':'关');$('#sound').setAttribute('aria-label',soundOn?'关闭声音':'开启声音');tone(420,.2);};
function act(type){if(paused)return;if(type==='attack'){const close=state.enemies.filter(e=>distance(state.player,e)<3.1).sort((a,b)=>distance(state.player,a)-distance(state.player,b))[0];if(close)state.player.face=Math.atan2(close.x-state.player.x,close.z-state.player.z);}action(state,type);}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));$('#interact').onclick=()=>act('interact');
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(!$('#modal').open){e.preventDefault();$('#pause').click();}return;}if(paused)return;if(e.code==='KeyB'){showJournal();return;}if(e.code==='KeyM'){showWorldMap();return;}keys.add(e.code);if(e.repeat)return;const map={KeyJ:'attack',Space:'dash',KeyQ:'nova',KeyR:'potion',KeyE:'interact'};if(map[e.code])act(map[e.code]);});addEventListener('keyup',e=>keys.delete(e.code));
addEventListener('blur',()=>{keys.clear();joy={x:0,z:0};if(!paused&&!['dead','won'].includes(state.phase))modal('长夜暂歇','返回营地后继续旅程。');});
const ray=new T.Raycaster(),ground=new T.Plane(new T.Vector3(0,1,0),0);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(paused)return;canvas.focus();const rect=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=new T.Vector3();if(ray.ray.intersectPlane(ground,hit)){
 const target=state.enemies.find(en=>Math.hypot(en.x-hit.x,en.z-hit.z)<1.35);movePath=[];attackTarget=null;pendingInteraction=null;
 if(e.button===2||e.shiftKey){state.player.face=Math.atan2(hit.x-state.player.x,hit.z-state.player.z);act('attack');}
 else if(target){attackTarget=target.id;repath=0;}
 else{const poi=getPoints(state).find(p=>Math.hypot(p.x-hit.x,p.z-hit.z)<1);if(poi){travelTo(poi.id);return;}movePath=findPath(state.player,{x:hit.x,z:hit.z});if(movePath.length)circle(hit.x,hit.z,'#dec992',.5,.45);}
}});
const stick=$('#stick');let stickPointer=null;function joystick(e){const r=stick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/35,y=(e.clientY-r.top-r.height/2)/35;const n=Math.max(1,Math.hypot(x,y));x/=n;y/=n;joy={x:(x+y)*Math.SQRT1_2,z:(y-x)*Math.SQRT1_2};stick.firstElementChild.style.transform=`translate(${x*25}px,${y*25}px)`;}stick.onpointerdown=e=>{stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);joystick(e);};stick.onpointermove=e=>{if(stickPointer===e.pointerId)joystick(e);};function clearStick(){stickPointer=null;joy={x:0,z:0};stick.firstElementChild.style.transform='';}stick.onpointerup=clearStick;stick.onpointercancel=clearStick;
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);const view=state.area==='overworld'?(h>w?17:13.5):(h>w?12:11);camera.left=-view*w/h;camera.right=view*w/h;camera.top=view;camera.bottom=-view;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
const mm=$('#minimap').getContext('2d');function minimap(){mm.clearRect(0,0,180,150);mm.strokeStyle='#53665e';mm.strokeRect(15,4,150,142);const scale=2.5;mm.fillStyle='#697368';for(const o of (state.area==='overworld'?OBSTACLES:MAPS[state.area].rooms))mm.fillRect(90+(o.x-o.w/2)*scale,75+(o.z-o.d/2)*scale,o.w*scale,o.d*scale);for(const p of getPoints(state)){if(p.type==='chest'&&state.opened.includes(p.id))continue;mm.fillStyle=p.id===objective(state).target?'#f5d992':p.type==='seal'?'#7ec5b7':'#849d9b';mm.beginPath();mm.arc(90+p.x*scale,75+p.z*scale,p.id===objective(state).target?3.4:2,0,7);mm.fill();}for(const e of state.enemies){mm.fillStyle=e.boss?'#f1bc74':e.kind==='archer'?'#d5a076':'#dc7964';mm.fillRect(88+e.x*scale,73+e.z*scale,e.boss?5:3,e.boss?5:3);}mm.fillStyle='#fff9df';mm.beginPath();mm.arc(90+state.player.x*scale,75+state.player.z*scale,3,0,7);mm.fill();}
let hudTick=0;function hud(){const p=state.player;$('#hp').textContent=Math.ceil(p.hp);$('#mp').textContent=Math.floor(p.mp);$('#hp-max').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('#mp-max').textContent=`${Math.floor(p.mp)} / 100`;$('#hp-fluid').style.height=`${p.hp/p.maxHp*100}%`;$('#mp-fluid').style.height=p.mp+'%';$('#potions').textContent=`药剂 × ${state.potions}`;$('#level').textContent='Lv. '+state.level;$('#kills').textContent=state.kills+' 击败';$('#xp').style.width=state.xp+'%';$('#wave').textContent=objective(state).step;$('#gold').textContent=state.gold+' 余烬';$('#enemy-count').textContent=state.enemies.length+' 敌人';const boss=state.enemies.find(e=>e.boss);$('#boss').hidden=!boss;if(boss)$('#boss i').style.width=boss.hp/boss.maxHp*100+'%';for(const type of ['attack','dash','nova','potion']){const el=$(`[data-action="${type}"] em`),time=p[type];el.style.height=(time>0?'100%':'0');el.textContent=time>0?time.toFixed(1):'';}
const active=state.phase==='combat',q=objective(state),n=nearby(state);$('#route-options').hidden=state.stage==='intro';$('#zone-status').textContent=state.area!=='overworld'?MAPS[state.area].name:active?'战斗中':state.player.z<-16?'墓穴入口':state.player.x<-14?'朽木林地':state.player.x>14?'沉石采场':'余火营地';$('.map-title span').textContent=$('#zone-status').textContent;$('#objective').textContent=q.title;$('#objective-detail').textContent=q.detail;$('#track').textContent='前往 · '+POINTS.find(p=>p.id===q.target).name;$('#prompt').textContent=n?'E · '+n.name:active?'避开红色预警 · J 斩击 · Q 星陨 · R 药剂':'点击地面移动 · 点击地点名称前往 · B 行囊';$('#prompt').classList.toggle('available',!!n);$('.chapter').textContent=`远征 ${state.cycle+1} / ${MAPS[state.area].name}`;$('#journal').textContent=state.skillPoints?`行囊 B · ${state.skillPoints} 点可用`:'行囊 B';$('#quest-steps').textContent=`${state.stage!=='intro'?'✓':'○'} 接取委托　${state.seals.length}/2 封印　${state.bossDead?'✓':'○'} 核心`;minimap();}
function handleEvents(){for(const e of state.events){if(e.type==='area'){syncArea();showNotice(e.text);}if(e.type==='checkpoint')saveCheckpoint();if(e.type==='dialog')openService(e.kind);if(e.type==='impact'){circle(e.x,e.z,'#e07954',e.r,.25);particles(e.x,e.z,'#d8956e',12);if(e.r>2)shake=.24;}if(e.type==='loot')particles(e.x,e.z,'#f8d994',18);if(e.type==='attack'){slash(e.x,e.z,e.face);tone(150,.1,'sawtooth',.018);}if(e.type==='nova'){circle(e.x,e.z,'#75eaff',5.5);particles(e.x,e.z,'#abf4ff',35);tone(600,.5);shake=.12;}if(e.type==='hit'){particles(e.x,e.z,'#ffe3a0',12,1.2);floating(e.x,e.z,e.amount);hitStop=.045;shake=.15;}if(e.type==='kill'){particles(e.x,e.z,e.boss?'#e9c078':'#7c94a1',18);tone(240,.09);}if(e.type==='heal'){circle(e.x,e.z,'#a6e8a3',1.5);tone(700,.2);}if(e.type==='hurt'){$('#game').classList.remove('hurt');void $('#game').offsetWidth;$('#game').classList.add('hurt');shake=.24;tone(65,.15,'sawtooth');}if(e.type==='dash'){circle(state.player.x,state.player.z,'#bddcd4',1);tone(260,.12);}if(e.type==='enemyAttack')circle(e.x,e.z,'#db886c',e.boss?1.7:1,.3);if(e.type==='notice'||e.type==='wave')showNotice(e.text);if(e.type==='dead')modal('余火熄灭',`你击败了 ${state.kills} 个敌人。<br>检查点后的进度将回退；避开红色预警，在篝火旁休整。`,'从检查点重试','retry');if(e.type==='won')modal('长夜破晓',`你取回了星门核心，完成了本次远征。<br>装备与成长已保留。向守夜人领取救援奖励，或开启下一次远征。<br>击败 ${state.kills} 个敌人 · 达到 Lv. ${state.level}<br>用时 ${Math.floor(state.time/60)} 分 ${Math.floor(state.time%60)} 秒`,'返回营地整备','resume');}state.events.length=0;}
const cameraFocus=new T.Vector3(0,0,3);
function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-last)/1000,.04);last=now;if(hitStop>0){hitStop-=dt;dt*=.12;}if(!paused){let sx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),sy=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const input={x:(sx+sy)*Math.SQRT1_2+joy.x,z:(sy-sx)*Math.SQRT1_2+joy.z};if(Math.hypot(input.x,input.z)>.05){movePath=[];attackTarget=null;pendingInteraction=null;}else{const en=state.enemies.find(e=>e.id===attackTarget);if(en){repath-=dt;if(distance(state.player,en)<2.3){movePath=[];act('attack');}else if(repath<=0){movePath=findPath(state.player,en);repath=.6;}}else attackTarget=null;while(movePath.length&&distance(state.player,movePath[0])<.19)movePath.shift();if(movePath.length){input.x=movePath[0].x-state.player.x;input.z=movePath[0].z-state.player.z;const n=Math.hypot(input.x,input.z);input.x/=n;input.z/=n;}}update(state,dt,input);if(pendingInteraction){const poi=getPoints(state).find(p=>p.id===pendingInteraction);if(poi&&distance(state.player,poi)<2.15){movePath=[];const id=pendingInteraction;pendingInteraction=null;interact(state,id);}}if(keys.has('KeyJ'))act('attack');handleEvents();const p=state.player;hero.g.position.set(p.x,0,p.z);hero.g.rotation.y=p.face;hero.g.visible=p.invuln<=0||Math.sin(now*.045)>-.5;hero.legs.forEach((m,i)=>m.rotation.x=Math.hypot(input.x,input.z)>.1?Math.sin(now*.012+i*Math.PI)*.5:0);hero.hand.rotation.x=p.attack>.12?Math.sin((.46-p.attack)*10)*-2.5:0;hero.hand.rotation.z=p.attack>.12?Math.sin((.46-p.attack)*10)*-.9:0;hero.cape.rotation.x=-.12+Math.sin(now*.007)*.07;hero.cape.rotation.z=Math.sin(now*.004)*.045;selection.position.set(p.x,.13,p.z);
for(const e of state.enemies){let a=enemyMeshes.get(e.id);if(!a){a=actor(true,e.boss);if(e.kind==='brute')a.baseScale*=1.22;if(e.kind==='archer'){a.cape.material.color.set('#69784b');const bow=new T.Mesh(new T.TorusGeometry(.4,.035,5,16,Math.PI),mat('#b69562'));bow.position.set(.4,1.1,.35);a.g.add(bow);}enemyMeshes.set(e.id,a);}a.g.position.set(e.x,Math.sin(now*.006+e.id)*.025,e.z);a.g.rotation.y=e.face;a.legs.forEach((m,i)=>m.rotation.x=Math.sin(now*.009+i*Math.PI)*.45);a.hand.rotation.x=e.cooldown>.85?-1.2:0;a.g.scale.setScalar(a.baseScale*(e.hit>0?1.05:1));a.health.visible=e.hp<e.maxHp||distance(p,e)<5;a.health.quaternion.copy(camera.quaternion);a.health.quaternion.premultiply(a.g.quaternion.clone().invert());a.healthFill.scale.x=Math.max(0,e.hp/e.maxHp);a.healthFill.position.x=-(1-e.hp/e.maxHp)*.425;}
for(const[id,a]of enemyMeshes)if(!state.enemies.some(e=>e.id===id)){disposeActor(a);enemyMeshes.delete(id);}
for(const d of state.drops){let m=dropMeshes.get(d.id);if(!m){m=new T.Mesh(new T.OctahedronGeometry(d.item?.32:.19),mat(d.item?(d.item.rarity==='史诗'?'#dbaaee':'#8bd6ef'):'#94d997',d.item?'#758fc4':'#66bb77'));scene.add(m);dropMeshes.set(d.id,m);}m.position.set(d.x,.42+Math.sin(now*.003)*.12,d.z);m.rotation.y=now*.001;}
for(const[id,m]of dropMeshes)if(!state.drops.some(d=>d.id===id)){scene.remove(m);m.geometry.dispose();dropMeshes.delete(id);}
for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.t+=dt;if(e.t>e.life){scene.remove(e.m);e.m.geometry.dispose();e.m.material.dispose();effects.splice(i,1);continue;}e.m.material.opacity=1-e.t/e.life;if(e.v){e.m.position.addScaledVector(e.v,dt);e.v.y-=6*dt;}if(e.max)e.m.scale.setScalar(.3+e.t/e.life*e.max);}
for(const f of flames){f.mesh.scale.y=.8+Math.sin(now*.008+f.phase)*.2;f.mesh.rotation.y=now*.001+f.phase;}lights.forEach((l,i)=>l.intensity=(l.userData.baseIntensity||70)*(1+Math.sin(now*.014+i)*.1));ring.rotation.z=now*.0002;portalLight.intensity=85+Math.sin(now*.002)*12;if(state.area==='overworld')animateWorld(now);if(state.area==='overworld'&&rand()<.35)particles(PORTAL.x+(rand()-.5)*2,PORTAL.z+(rand()-.5)*2,'#82e7f4',1,.25);
cameraFocus.lerp(new T.Vector3(p.x,0,p.z),.075);camera.position.set(27+cameraFocus.x,33,27+cameraFocus.z);camera.lookAt(cameraFocus);chapter.update(state,camera,now);dungeons.update(state,now);if(shake>0){camera.position.x+=(rand()-.5)*shake;shake=Math.max(0,shake-dt);}hudTick+=dt;if(hudTick>.1){hud();hudTick=0;}}
for(let i=numbers.length-1;i>=0;i--){const n=numbers[i];if(!paused)n.t+=dt;if(n.t>.85){n.el.remove();numbers.splice(i,1);continue;}const pos=new T.Vector3(n.x,2.3+n.t*1.5,n.z).project(camera);n.el.style.left=(pos.x*.5+.5)*innerWidth+'px';n.el.style.top=(-pos.y*.5+.5)*innerHeight+'px';n.el.style.opacity=1-n.t/.85;}if(now>noticeUntil)$('#notice').style.opacity=0;renderer.render(scene,camera);}
syncArea();hud();$('#loading').remove();showNotice('第一章 · 余火的请求\n点击守夜人，与她交谈。');if(storedSave){modal('继续旅程',`发现本浏览器的检查点。<br>${objective(restore(storedSave)).title}`,'继续游戏','load');addDialogButton('新的旅程',()=>{$('#modal').close();restart();saveCheckpoint();});}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_emberfall_status',description:'读取当前试炼状态、生命、等级与敌人数量。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({phase:state.phase,paused,area:state.area,position:{x:state.player.x,z:state.player.z},stage:state.stage,seals:state.seals,gold:state.gold,objective:objective(state).title,hp:state.player.hp,level:state.level,enemies:state.enemies.length})});register({name:'prepare_emberfall_save_restore',description:'校验用户提供的旅程备份文字并展示恢复确认面板。不会立即覆盖进度，须在游戏界面确认恢复。',inputSchema:{type:'object',properties:{save:{type:'string'}},required:['save'],additionalProperties:false},execute:input=>{const loaded=restore(input.save);if(!loaded)throw Error('Invalid save');modal('恢复旅程',`位置：${MAPS[loaded.area].name}<br>Lv. ${loaded.level} · ${loaded.inventory.length} 件装备<br>${objective(loaded).title}<p>确认后替换当前检查点。</p>`,'取消');addDialogButton('确认恢复',()=>{restart(loaded);saveCheckpoint();$('#modal').close();paused=false;last=performance.now();});return{valid:true,area:loaded.area,level:loaded.level,confirmationRequired:true};}});register({name:'set_emberfall_pause',description:'暂停或恢复当前试炼；不会重开游戏。',inputSchema:{type:'object',properties:{paused:{type:'boolean'}},required:['paused'],additionalProperties:false},execute:input=>{if(typeof input?.paused!=='boolean')throw Error('paused must be boolean');if(['won','dead'].includes(state.phase))throw Error('Trial has ended');if(input.paused)modal('长夜暂歇','营地会等待你的归来。');else{$('#modal').close();paused=false;last=performance.now();}return{paused};}});addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
