import {MAPS,DUNGEON_POINTS,TRAPS,onFloor} from './maps.mjs';
import {ITEMS,TALENTS,CAPACITY,makeItem,combatStats,equip,learn} from './equipment.mjs';
export const ARENA=27;
export const PORTAL={x:-4,z:-1};
export const OBSTACLES=[{x:-8,z:-9,w:5,d:4},{x:0,z:-11,w:5,d:4},{x:9,z:-7,w:4,d:5},{x:-12,z:3,w:2,d:3},{x:11,z:7,w:3,d:3},{x:15,z:-1,w:2,d:3},{x:22,z:5,w:3,d:2},{x:-21,z:1,w:2,d:2},{x:-2,z:-23,w:1.8,d:1.8},{x:3,z:-23,w:1.8,d:1.8}];
export const TREE_POINTS=[[-15,-12],[-14,-14],[14,-13],[13,-15],[-16,9],[-15,13],[15,13],[-9,-16],[6,-17]];
for(let i=0;i<24;i++){if(i%3===0)continue;const a=i/24*Math.PI*2,x=-19+Math.cos(a)*(4.5+(i%3)),z=8+Math.sin(a)*5;if(x>-26&&x<-13&&z<18&&z>0)TREE_POINTS.push([x,z]);}
for(let i=TREE_POINTS.length-1;i>=0;i--){const[x,z]=TREE_POINTS[i];if(x<-13&&x>-21&&z>6&&z<10)TREE_POINTS.splice(i,1);}
OBSTACLES.push(...TREE_POINTS.map(([x,z])=>({x,z,w:.55,d:.55})),{x:-12,z:6,w:1.8,d:2.2});
export const POINTS=[{id:'warden',name:'守夜人 · 伊芙',x:-4,z:4,type:'npc'},{id:'fire',name:'余火篝火',x:-7,z:5,type:'rest'},{id:'forge',name:'铁匠工作台',x:-10,z:-4,type:'forge'},{id:'west',name:'朽木封印',x:-19,z:8,type:'seal'},{id:'east',name:'沉石封印',x:20,z:0,type:'seal'},{id:'altar',name:'沉钟墓穴入口',x:0,z:-20,type:'travel',to:'crypt'},{id:'portal',name:'归途星门',...PORTAL,type:'portal'},{id:'chest-camp',name:'旅人补给箱',x:3,z:7,type:'chest'},{id:'chest-west',name:'林地遗物箱',x:-20,z:15,type:'chest'},{id:'chest-east',name:'矿工补给箱',x:22,z:-5,type:'chest'}];
POINTS.push(...DUNGEON_POINTS);
export function getPoints(s){return POINTS.filter(p=>(p.area||'overworld')===(s.area||'overworld'));}
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function createGame(){return{phase:'camp',stage:'intro',area:'overworld',regions:{},visited:['overworld'],levers:[],scoutRescued:false,scoutReward:false,cycle:0,inventory:[],equipped:{weapon:null,armor:null,charm:null},talents:{blade:0,arcane:0,vigor:0},skillPoints:0,breakables:[],wave:0,time:0,kills:0,level:1,xp:0,potions:3,gold:0,weapon:0,armor:0,seals:[],opened:[],bossDead:false,player:{area:'overworld',x:-1,z:5,hp:100,maxHp:100,mp:100,face:Math.PI,invuln:0,dashTime:0,attack:0,dash:0,nova:0,potion:0},enemies:[],drops:[],hazards:[],projectiles:[],events:[],serial:0,deaths:0};}
function emit(s,type,data={}){s.events.push({type,...data});}
function notice(s,text){emit(s,'notice',{text});return false;}
export function canStand(x,z,r=.42,area='overworld'){const map=MAPS[area];return !!map&&Number.isFinite(x)&&Number.isFinite(z)&&Math.abs(x)<map.bounds-r&&Math.abs(z)<map.bounds-r&&onFloor(x,z,r,area)&&!(area==='overworld'?OBSTACLES:map.solids).some(o=>Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r);}
function move(a,dx,dz,r=.42){if(canStand(a.x+dx,a.z,r,a.area))a.x+=dx;if(canStand(a.x,a.z+dz,r,a.area))a.z+=dz;}
function navigation(p){const area=p.area||'overworld';const field=new Map(),queue=[];const px=Math.round(p.x),pz=Math.round(p.z);for(let r=0;r<3&&!queue.length;r++)for(let x=px-r;x<=px+r;x++)for(let z=pz-r;z<=pz+r;z++)if(canStand(x,z,.78,area)){queue.push({x,z});field.set(x+','+z,0);}
for(let i=0;i<queue.length;i++){const a=queue[i],cost=field.get(a.x+','+a.z);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=a.x+dx,z=a.z+dz,key=x+','+z;if(!field.has(key)&&canStand(x,z,.78,area)){field.set(key,cost+1);queue.push({x,z});}}}return field;}
function waypoint(s,e,p){let clear=true;const dist=distance(e,p);for(let t=.5;t<dist;t+=.5)if(!canStand(e.x+(p.x-e.x)*t/dist,e.z+(p.z-e.z)*t/dist,e.boss?.75:.45,s.area)){clear=false;break;}if(clear)return p;const x=Math.round(e.x),z=Math.round(e.z);let best=null,score=Infinity;for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++){const xx=x+dx,zz=z+dz,cost=s.nav.get(xx+','+zz);if(cost===undefined||!canStand((e.x+xx)/2,(e.z+zz)/2,.78,s.area))continue;const v=cost+Math.hypot(e.x-xx,e.z-zz)*.75;if(v<score){score=v;best={x:xx,z:zz};}}return best||p;}
export function findPath(start,end){const area=start.area||'overworld';if(!canStand(end.x,end.z,.4,area))return[];const field=navigation({...end,area});let x=Math.round(start.x),z=Math.round(start.z);if(!field.has(x+','+z)){let best=null;for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)if(field.has((x+dx)+','+(z+dz))&&(!best||Math.hypot(x+dx-start.x,z+dz-start.z)<best.d))best={x:x+dx,z:z+dz,d:Math.hypot(x+dx-start.x,z+dz-start.z)};if(!best)return[];x=best.x;z=best.z;}
const path=[{x,z}];for(let i=0;i<150;i++){const cost=field.get(x+','+z);if(cost===0){path.push({...end});return path;}let next=null;for(const[dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const n=field.get((x+dx)+','+(z+dz));if(n!==undefined&&n<cost){next={x:x+dx,z:z+dz};break;}}if(!next)return[];({x,z}=next);path.push(next);}return[];}
const alive=s=>s.phase!=='dead';
const near=(s,id,r=3)=>{const p=getPoints(s).find(p=>p.id===id);return !!p&&distance(s.player,p)<r;};
function spawn(s,kind,x,z,zone){if(!canStand(x,z,.8,s.area)){const ox=x,oz=z;let found=false;for(let r=1;r<=3&&!found;r++)for(let dx=-r;dx<=r&&!found;dx++)for(let dz=-r;dz<=r&&!found;dz++)if(canStand(ox+dx,oz+dz,.8,s.area)){x=ox+dx;z=oz+dz;found=true;}}const hp=Math.round({grunt:82,archer:62,brute:150,boss:1400}[kind]*(1+s.cycle*.4)*(s.area==='depths'&&!['boss'].includes(kind)?1.3:1));s.enemies.push({id:++s.serial,area:s.area,x,z,homeX:x,homeZ:z,hp,maxHp:hp,kind,zone,boss:kind==='boss',speed:{grunt:2.05,archer:1.8,brute:1.35,boss:1.55}[kind],cooldown:1.1,hit:0,face:0,aggro:false,attackCount:0});}
function populate(s){for(const [kind,x,z]of [['grunt',-17,7],['grunt',-22,8],['archer',-22,5],['brute',-18,11],['grunt',-17,12],['archer',-23,10]])spawn(s,kind,x,z,'west');for(const[kind,x,z]of[['brute',19,2],['brute',23,0],['grunt',18,-3],['grunt',23,-3],['archer',22,-7],['archer',18,5],['grunt',24,3]])spawn(s,kind,x,z,'east');}
export function objective(s){
 if(s.stage==='intro')return{title:'余火之外',detail:'与守夜人交谈，踏上边境与墓穴的远征。',target:'warden',step:'营地'};
 if(s.stage==='seals')return{title:`边境封印 · ${s.seals.length}/2`,detail:'自由探索林地与采场。击败守卫，取得石碑封印后开启北方墓穴。',target:s.seals.includes('west')?'east':'west',step:'I · 野外'};
 if(s.stage==='crypt'){if(s.area==='overworld')return{title:'进入沉钟墓穴',detail:'前往北方墓穴入口。两枚封印会打开阶梯。',target:'altar',step:'II · 地下城'};return{title:`唤醒共鸣机关 · ${s.levers.length}/2`,detail:'探索东西两翼，击败机关守卫。西翼有被困的斥候。',target:s.levers.length===2?'descent':s.levers.includes('lever-west')?'lever-east':'lever-west',step:'II · 墓穴上层'};}
 if(s.stage==='depths'){if(s.area==='overworld')return{title:'重返熔心圣所',detail:'从墓穴入口返回地下城，机关进度已保留。',target:'altar',step:'III · 深处'};if(s.area==='crypt')return{title:'深入熔心圣所',detail:'两侧机关已开启，北方封印门通往下层。',target:'descent',step:'III · 深处'};return{title:'挑战熔心领主',detail:s.enemies.some(e=>e.boss)?'避开熔火与裂地预警，攻击间隙切入。':'清理圣所守卫，前往北方王座唤醒领主。',target:'ritual',step:'III · 首领'};}
 if(s.stage==='return')return{title:'携战利品返回营地',detail:s.area==='overworld'?'在星门交付核心，结算远征。装备和成长会保留。':'核心已取得。使用回城裂隙，或沿阶梯返回。',target:s.area==='depths'?'rift-home':s.area==='crypt'?'crypt-exit':'portal',step:'IV · 归途'};
 return{title:`远征 ${s.cycle+1} 已完成`,detail:'整理战利品、分配技能点，与守夜人开启更高难度远征。',target:s.area==='depths'?'rift-home':s.area==='crypt'?'crypt-exit':'warden',step:'回城成长'};}
export function interactables(s){return getPoints(s).filter(p=>(p.type!=='chest'||!s.opened.includes(p.id))&&(p.id!=='rift-home'||s.bossDead)&&!(p.id==='scout'&&s.scoutRescued));}
export function nearby(s){return interactables(s).filter(p=>distance(s.player,p)<2.7).sort((a,b)=>distance(s.player,a)-distance(s.player,b))[0]||null;}
export function interact(s,id){if(!alive(s))return false;const poi=id?getPoints(s).find(p=>p.id===id):nearby(s);if(!poi||distance(s.player,poi)>3)return notice(s,'靠近人物、石碑或补给箱，按 E 交互。');
 if(poi.type==='npc'){emit(s,'dialog',{kind:'warden'});return true;}
 if(poi.type==='forge'){emit(s,'dialog',{kind:'forge'});return true;}
 if(poi.type==='rest')return service(s,'rest');
 if(poi.type==='travel')return travel(s,poi.id);
 if(poi.type==='lever'){if(s.levers.includes(poi.id))return notice(s,'机关已启动。');const zone=poi.id==='lever-west'?'crypt-west':'crypt-east';if(s.enemies.some(e=>e.zone===zone))return notice(s,'先清理这座机关附近的守卫。');s.levers.push(poi.id);s.gold+=30;emit(s,'notice',{text:`共鸣机关已启动 · ${s.levers.length}/2`});emit(s,'checkpoint');return true;}
 if(poi.type==='rescue'){if(s.scoutRescued)return false;if(s.enemies.some(e=>e.zone==='crypt-west'))return notice(s,'先击败西翼守卫，再解救斥候。');s.scoutRescued=true;emit(s,'notice',{text:'斥候已获救\n回营地向守夜人领取信物和技能点。'});emit(s,'checkpoint');return true;}
 if(poi.type==='chest'){if(s.opened.includes(poi.id))return notice(s,'箱子已经取空。');s.opened.push(poi.id);s.gold+=22;s.potions=Math.min(9,s.potions+1);emit(s,'notice',{text:'发现补给 · 余烬 +22 · 药剂 +1'});emit(s,'loot',poi);if(s.area!=='overworld'||poi.id==='chest-west')dropItem(s,poi.x,poi.z,s.area==='depths'?'moon':s.area==='crypt'?'guard':'fang');return true;}
 if(poi.type==='seal'){if(s.stage==='intro')return notice(s,'先与守夜人交谈，了解封印的用途。');if(s.seals.includes(poi.id))return notice(s,'这枚封印已收入行囊。');if(s.enemies.some(e=>e.zone===poi.id))return notice(s,'封印仍被侵蚀。先击败这片区域的所有守卫。');s.seals.push(poi.id);s.gold+=35;s.player.hp=Math.min(s.player.maxHp,s.player.hp+40);if(s.seals.length===2)s.stage='crypt';emit(s,'notice',{text:`取得${poi.name} · ${s.seals.length}/2\n余烬 +35 · 已记录检查点`});emit(s,'checkpoint');return true;}
 if(poi.type==='boss'){if(s.bossDead)return notice(s,'领主已倒下，使用北侧回城裂隙。');if(s.enemies.some(e=>e.boss))return notice(s,'领主已苏醒，避开红色预警！');if(s.enemies.some(e=>e.zone==='depths-guard'))return notice(s,'先击败圣所大厅的守卫，才能激活王座。');spawn(s,'boss',0,-17,'boss');s.enemies.at(-1).aggro=true;s.phase='combat';emit(s,'wave',{text:'熔心领主 · 裂隙之王'});return true;}
 if(poi.type==='portal'){if(s.stage==='done')return notice(s,'远征已结算。与守夜人交谈开启下一次远征。');if(!s.bossDead)return notice(s,'星门等待熔心核心。探索墓穴，击败地下深处的领主。');s.gold+=120;s.stage='done';s.phase='explore';emit(s,'checkpoint');emit(s,'won');return true;}return false;}
export function service(s,type){if(!alive(s))return false;
 if(type==='accept'){if(!near(s,'warden'))return false;if(s.stage!=='intro')return notice(s,'两处石碑的封印，是打开北方祭坛的钥匙。');s.stage='seals';s.phase='explore';s.gold+=15;populate(s);emit(s,'notice',{text:'任务已接取 · 余烬 +15\n西侧林地或东侧采场，选择你的路线。'});emit(s,'checkpoint');return true;}
 if(type==='rest'){if(!getPoints(s).some(p=>p.type==='rest'&&distance(s.player,p)<3))return false;if(s.enemies.some(e=>e.aggro&&distance(s.player,e)<8)||s.hazards.some(h=>distance(s.player,h)<5))return notice(s,'附近仍有敌意，暂时无法休息。');s.player.hp=s.player.maxHp;s.player.mp=100;s.potions=Math.max(2,s.potions);s.phase=s.stage==='intro'?'camp':'explore';emit(s,'heal',s.player);emit(s,'notice',{text:'在余火旁休息\n生命与法力恢复 · 药剂补足至 2 · 已保存'});emit(s,'checkpoint');return true;}
 if(type==='claim-scout'){if(!near(s,'warden')||!s.scoutRescued||s.scoutReward)return false;if(s.inventory.length>=CAPACITY)return notice(s,'背包已满，先到铁匠处出售装备。');s.scoutReward=true;s.inventory.push(makeItem('scout',++s.serial,s.cycle));s.skillPoints++;s.gold+=50;emit(s,'notice',{text:'救援回报 · 斥候的信物 · 技能点 +1 · 余烬 +50'});emit(s,'checkpoint');return true;}
 if(type==='expedition'){if(!near(s,'warden')||s.stage!=='done')return false;s.cycle++;s.stage='crypt';s.bossDead=false;s.levers=[];s.scoutRescued=false;s.scoutReward=false;s.regions={};s.opened=s.opened.filter(id=>!DUNGEON_POINTS.some(p=>p.id===id));s.phase='explore';emit(s,'notice',{text:`远征 ${s.cycle+1} 开启 · 更强敌人与成长战利品`});emit(s,'checkpoint');return true;}
 if(!near(s,'forge'))return false;
 if(type==='buy'){if(s.potions>=9)return notice(s,'最多携带 9 瓶药剂。');if(s.gold<18)return notice(s,'余烬不足，需要 18。');s.gold-=18;s.potions++;emit(s,'checkpoint');emit(s,'notice',{text:'购买药剂 · 余烬 −18'});return true;}
 if(['weapon','armor'].includes(type)){if(s[type]>=2)return notice(s,'这件装备已强化至当前上限。');const cost=s[type]===0?30:55;if(s.gold<cost)return notice(s,`余烬不足，需要 ${cost}。`);s.gold-=cost;s[type]++;emit(s,'checkpoint');emit(s,'notice',{text:`${type==='weapon'?'旅人长剑':'游侠护甲'} +${s[type]}\n${type==='weapon'?'每次斩击伤害 +10':'每次受击减伤 +3'}`});return true;}return false;}
function damage(s,e,amount){if(e.hp<=0)return;e.hp-=amount;e.hit=.18;e.aggro=true;emit(s,'hit',{x:e.x,z:e.z,amount});if(e.hp<=0){s.kills++;s.xp+=e.boss?150:30;s.gold+=e.kind==='brute'?16:10;emit(s,'kill',{x:e.x,z:e.z,boss:e.boss});if(e.boss||s.kills%3===0)dropItem(s,e.x,e.z,e.boss?'ember':s.area==='crypt'?'moon':s.area==='depths'?'guard':s.kills%2?'fang':'hide');if(s.kills%3===0)s.drops.push({id:++s.serial,x:e.x,z:e.z});while(s.xp>=100){s.xp-=100;s.level++;s.skillPoints++;s.player.maxHp+=12;s.player.hp=Math.min(s.player.maxHp,s.player.hp+30);s.player.mp=Math.min(100,s.player.mp+35);emit(s,'notice',{text:`等级提升 · Lv. ${s.level}\n生命上限 +12`});}if(e.boss){s.bossDead=true;s.stage='return';s.gold+=100;emit(s,'notice',{text:'取得星门核心\n返回营地，与蓝色星门交互。'});emit(s,'checkpoint');}}}
export function action(s,type){if(!alive(s))return false;const p=s.player;if(type==='interact')return interact(s);
 if(type==='attack'&&p.attack<=0){p.attack=.46;emit(s,'attack',{x:p.x,z:p.z,face:p.face});for(const e of s.enemies){const a=Math.atan2(e.x-p.x,e.z-p.z);if(e.hp>0&&distance(p,e)<2.65&&Math.cos(a-p.face)>-.15)damage(s,e,combatStats(s).attack);}for(const b of s.breakables)if(distance(p,b)<2.65&&Math.cos(Math.atan2(b.x-p.x,b.z-p.z)-p.face)>-.15)breakObject(s,b);s.breakables=s.breakables.filter(b=>b.hp>0);return true;}
 if(type==='dash'&&p.dash<=0){p.dash=1.65;p.dashTime=.22;p.invuln=.38;emit(s,'dash');return true;}
 if(type==='nova'&&p.nova<=0){if(p.mp<35)return notice(s,'法力不足，稍待片刻。');p.mp-=35;p.nova=6;emit(s,'nova',{x:p.x,z:p.z});for(const e of s.enemies)if(e.hp>0&&distance(p,e)<5.5){damage(s,e,combatStats(s).spell);if(s.talents.arcane)e.slow=1.5+s.talents.arcane*.5;}for(const b of s.breakables)if(distance(p,b)<5.5)breakObject(s,b);s.breakables=s.breakables.filter(b=>b.hp>0);return true;}
 if(type==='potion'&&p.potion<=0){if(!s.potions)return notice(s,'药剂用尽。拾取补给，或返回营地整备。');if(p.hp>=p.maxHp)return notice(s,'生命值已满。');s.potions--;p.hp=Math.min(p.maxHp,p.hp+65);p.potion=1;emit(s,'heal',p);return true;}return false;}
const inCamp=p=>(p.area||'overworld')==='overworld'&&p.x>-13&&p.x<13&&p.z>-13&&p.z<12;
function hurt(s,amount){const p=s.player;if(p.invuln>0||inCamp(p))return;p.hp=Math.max(0,p.hp-Math.max(2,amount*(1+s.cycle*.15)-combatStats(s).defense));p.invuln=.36;emit(s,'hurt');}
function telegraph(s,e,x,z,r,delay,amount,type='slam'){s.hazards.push({id:++s.serial,owner:e.id,x,z,r,left:delay,total:delay,amount,type,originX:e.x,originZ:e.z});}
export function update(s,dt,input={x:0,z:0}){if(!alive(s))return;dt=Math.min(.05,Math.max(0,dt));s.time+=dt;const p=s.player;for(const k of['attack','dash','nova','potion','invuln'])p[k]=Math.max(0,p[k]-dt);p.mp=Math.min(100,p.mp+dt*4.5);const len=Math.hypot(input.x,input.z);if(len>0)p.face=Math.atan2(input.x,input.z);if(p.dashTime>0){move(p,Math.sin(p.face)*17*dt,Math.cos(p.face)*17*dt);p.dashTime-=dt;}else if(len>0)move(p,input.x/Math.max(1,len)*5*dt,input.z/Math.max(1,len)*5*dt);
 s.navTimer=(s.navTimer||0)-dt;if(s.navTimer<=0){s.nav=navigation(p);s.navTimer=.65;}
 for(const e of s.enemies){if(e.hp<=0)continue;e.hit=Math.max(0,e.hit-dt);e.slow=Math.max(0,(e.slow||0)-dt);e.cooldown-=dt;const d=distance(p,e),safe=inCamp(p);const wasAggro=e.aggro;e.aggro=e.boss?s.area==='depths'&&distance(p,{x:0,z:-15})<13:!safe&&(e.aggro?d<12:d<7.8);if(e.boss&&wasAggro&&!e.aggro){e.hp=e.maxHp;notice(s,'你离开了王座区域，领主恢复了力量。');}if(!e.aggro){if(distance(e,{x:e.homeX,z:e.homeZ})>.25){const a=Math.atan2(e.homeX-e.x,e.homeZ-e.z);move(e,Math.sin(a)*e.speed*dt,Math.cos(a)*e.speed*dt);}continue;}
 const target=waypoint(s,e,p);e.face=Math.atan2(target.x-e.x,target.z-e.z);const reach=e.kind==='archer'?8:e.boss?3:1.55;
 if(d>reach&&!(e.windup>0)){let dx=Math.sin(e.face),dz=Math.cos(e.face);for(const other of s.enemies){if(other===e||other.hp<=0)continue;const sep=distance(e,other);if(sep>0&&sep<.85){dx+=(e.x-other.x)/sep*.55;dz+=(e.z-other.z)/sep*.55;}}move(e,dx*e.speed*(e.slow>0?.5:1)*dt,dz*e.speed*(e.slow>0?.5:1)*dt,e.boss?.7:.4);}else if(e.kind==='archer'&&d<4){move(e,-Math.sin(e.face)*e.speed*dt,-Math.cos(e.face)*e.speed*dt);}
 e.windup=Math.max(0,(e.windup||0)-dt);if(d<=reach&&e.cooldown<=0){e.attackCount++;const delay=e.boss?1.05:e.kind==='archer'?.65:.55;e.windup=delay;e.cooldown=e.boss?(e.hp<e.maxHp*.5?2.25:3):e.kind==='archer'?2.2:1.6;if(e.boss){telegraph(s,e,p.x,p.z,2.6,delay,32);if(e.hp<e.maxHp*.5){telegraph(s,e,p.x+3.2,p.z,2,1.4,22);telegraph(s,e,p.x-3.2,p.z,2,1.4,22);}}else if(e.kind==='archer')telegraph(s,e,p.x,p.z,.65,delay,14,'arrow');else telegraph(s,e,e.x+Math.sin(e.face)*.8,e.z+Math.cos(e.face)*.8,e.kind==='brute'?1.45:1.05,delay,e.kind==='brute'?20:12);}}
 s.hazards=s.hazards.filter(h=>{h.left-=dt;if(h.left>0)return true;if(!s.enemies.some(e=>e.id===h.owner&&e.hp>0))return false;if(h.type==='arrow'){const len=Math.hypot(h.x-h.originX,h.z-h.originZ)||1;s.projectiles.push({id:++s.serial,x:h.originX,z:h.originZ,dx:(h.x-h.originX)/len,dz:(h.z-h.originZ)/len,left:3,amount:h.amount});}else{emit(s,'impact',h);if(distance(p,h)<h.r+.3)hurt(s,h.amount);}return false;});
 s.projectiles=s.projectiles.filter(a=>{a.left-=dt;a.x+=a.dx*8*dt;a.z+=a.dz*8*dt;if(a.left<=0||!canStand(a.x,a.z,.1,s.area))return false;if(distance(p,a)<.5){hurt(s,a.amount);return false;}return true;});
 s.enemies=s.enemies.filter(e=>e.hp>0);s.drops=s.drops.filter(d=>{if(distance(p,d)<1.2){if(d.item){if(s.inventory.length>=CAPACITY){if(!d.warned){notice(s,'背包已满，先出售不需要的装备。');d.warned=true;}return true;}s.inventory.push(d.item);emit(s,'notice',{text:`拾取 ${d.item.rarity} · ${d.item.name}\nB 打开背包比较和装备`});return false;}p.hp=Math.min(p.maxHp,p.hp+20);p.mp=Math.min(100,p.mp+12);emit(s,'heal',d);return false;}return true;});
 for(const trap of TRAPS.filter(t=>t.area===s.area)){const pulse=(s.time+trap.offset)%5;if(pulse>3.8&&distance(p,trap)<trap.r)hurt(s,12);}
 if(p.hp<=0){s.phase='dead';s.deaths++;emit(s,'dead');return;}if(s.stage!=='intro')s.phase=s.enemies.some(e=>e.aggro)?'combat':'explore';}
export function dropItem(s,x,z,key){s.drops.push({id:++s.serial,x,z,item:makeItem(key,++s.serial,s.cycle)});}
function breakObject(s,b){if(b.hp<=0)return;b.hp=0;s.gold+=7;emit(s,'loot',b);if(b.reward)dropItem(s,b.x,b.z,b.reward);}
export function inventoryAction(s,type,id){if(!alive(s))return false;if(type==='equip'||type==='learn'){const ok=type==='equip'?equip(s,id):learn(s,id);if(ok)emit(s,'checkpoint');return ok;}if(type==='sell'){if(!near(s,'forge')||Object.values(s.equipped).includes(id))return false;const at=s.inventory.findIndex(i=>i.id===id);if(at<0)return false;s.gold+=s.inventory[at].value;s.inventory.splice(at,1);emit(s,'checkpoint');return true;}return false;}
function fillRegion(s){if(s.area==='crypt'){for(const[k,x,z,zone]of[['grunt',0,4,'crypt-hall'],['archer',3,-2,'crypt-hall'],['brute',-15,0,'crypt-west'],['grunt',-18,3,'crypt-west'],['archer',-19,-4,'crypt-west'],['brute',15,0,'crypt-east'],['grunt',18,3,'crypt-east'],['archer',19,-4,'crypt-east'],['grunt',0,-15,'crypt-north'],['archer',4,-19,'crypt-north']])spawn(s,k,x,z,zone);s.breakables=[{id:++s.serial,x:-3,z:16,hp:1,reward:'ash'},{id:++s.serial,x:-16,z:-3,hp:1,reward:null},{id:++s.serial,x:16,z:4,hp:1,reward:'guard'}];}if(s.area==='depths'){for(const[k,x,z]of[['brute',-4,5],['archer',5,0],['grunt',0,2],['brute',4,6],['grunt',-20,3],['archer',-18,6]])spawn(s,k,x,z,'depths-guard');s.breakables=[{id:++s.serial,x:-3,z:18,hp:1,reward:'moon'},{id:++s.serial,x:-20,z:6,hp:1,reward:null}];}}
export function travel(s,id){const p=getPoints(s).find(p=>p.id===id&&p.type==='travel');if(!alive(s)||!p||distance(s.player,p)>3)return false;if(id==='altar'&&s.seals.length<2)return notice(s,'需要两枚边境封印才能进入墓穴。');if(id==='descent'&&s.levers.length<2)return notice(s,'先启动东西两翼的共鸣机关。');if(id==='rift-home'&&!s.bossDead)return notice(s,'击败领主后回城裂隙才会稳定。');const from=s.area,to=p.to;s.regions[from]={enemies:s.enemies,drops:s.drops,breakables:s.breakables};const old=s.regions[to];delete s.regions[to];s.area=to;s.enemies=old?.enemies||[];s.drops=old?.drops||[];s.breakables=old?.breakables||[];s.hazards=[];s.projectiles=[];s.navTimer=0;if(!s.visited.includes(to)||(!old&&to!=='overworld')){fillRegion(s);if(!s.visited.includes(to))s.visited.push(to);}const spawn=to==='overworld'?{x:0,z:-18}:to==='crypt'&&from==='depths'?{x:0,z:-18}:MAPS[to].spawn;if(id==='rift-home')Object.assign(spawn,{x:-4,z:2});Object.assign(s.player,spawn,{area:to,invuln:1,dashTime:0});if(to==='depths'&&!['return','done'].includes(s.stage))s.stage='depths';else if(to==='crypt'&&s.stage==='seals')s.stage='crypt';s.phase='explore';emit(s,'area',{from,to,text:MAPS[to].name});emit(s,'checkpoint');return true;}
export function snapshot(s){const{nav,navTimer,events,...data}=s;return JSON.stringify({version:3,data:{...data,enemies:s.enemies.filter(e=>e.hp>0),hazards:[],projectiles:[],player:{...s.player,invuln:0,dashTime:0,attack:0,dash:0,nova:0,potion:0}}});}
export function restore(text){try{if(typeof text!=='string'||text.length>1000000)return null;const save=JSON.parse(text),d=save.data;if(![2,3].includes(save.version)||!d)return null;if(save.version===2){Object.assign(d,{area:'overworld',regions:{},visited:['overworld'],levers:[],scoutRescued:false,scoutReward:false,cycle:0,inventory:[],equipped:{weapon:null,armor:null,charm:null},talents:{blade:0,arcane:0,vigor:0},skillPoints:Math.max(0,d.level-1),breakables:[]});d.player.area='overworld';if(d.stage==='boss')d.stage='crypt';d.enemies=d.enemies.filter(e=>!e.boss).map(e=>({...e,area:'overworld'}));}
 if(!MAPS[d.area]||!['intro','seals','crypt','depths','return','done'].includes(d.stage)||!['camp','explore','combat','won'].includes(d.phase))return null;
 for(const k of['time','kills','level','xp','potions','gold','weapon','armor','serial','deaths','cycle','skillPoints'])if(!Number.isFinite(d[k])||d[k]<0)return null;
 if(d.weapon>2||d.armor>2||d.potions>9||!Array.isArray(d.seals)||d.seals.length>2||new Set(d.seals).size!==d.seals.length||d.seals.some(v=>!['west','east'].includes(v)))return null;
 if(!d.player||!canStand(d.player.x,d.player.z,.4,d.area)||!Number.isFinite(d.player.hp)||d.player.hp<=0||!Number.isFinite(d.player.maxHp)||d.player.maxHp<100||d.player.hp>d.player.maxHp||!Number.isFinite(d.player.mp))return null;
 const validEnemies=(en,area)=>Array.isArray(en)&&en.length<60&&en.every(e=>['grunt','archer','brute','boss'].includes(e.kind)&&Number.isFinite(e.hp)&&e.hp>0&&canStand(e.x,e.z,.1,area));if(!validEnemies(d.enemies,d.area))return null;
 if(!Array.isArray(d.opened)||d.opened.some(id=>!POINTS.some(p=>p.id===id&&p.type==='chest'))||!Array.isArray(d.drops)||!Array.isArray(d.breakables))return null;
 if(!Array.isArray(d.inventory)||d.inventory.length>CAPACITY||d.inventory.some(i=>!ITEMS[i.key]||i.name!==ITEMS[i.key].name||i.slot!==ITEMS[i.key].slot||!Number.isFinite(i.id)||['attack','defense','spell','value'].some(k=>!Number.isFinite(i[k])||i[k]<0)))return null;
 if(!d.equipped||Object.entries(d.equipped).some(([slot,id])=>!['weapon','armor','charm'].includes(slot)||(id!==null&&!d.inventory.some(i=>i.id===id&&i.slot===slot))))return null;
 if(!d.talents||Object.entries(TALENTS).some(([key,t])=>!Number.isInteger(d.talents[key])||d.talents[key]<0||d.talents[key]>t.max))return null;
 if(!Array.isArray(d.levers)||d.levers.some(id=>!['lever-west','lever-east'].includes(id))||new Set(d.levers).size!==d.levers.length||!d.regions||Object.entries(d.regions).some(([area,r])=>!MAPS[area]||!validEnemies(r.enemies,area)||!Array.isArray(r.drops)||!Array.isArray(r.breakables)))return null;
 const validItem=i=>i&&ITEMS[i.key]&&i.name===ITEMS[i.key].name&&i.slot===ITEMS[i.key].slot&&i.rarity===ITEMS[i.key].rarity&&Number.isInteger(i.id)&&i.id>0&&['attack','defense','spell','value'].every(k=>Number.isFinite(i[k])&&i[k]>=0);
 const validRegion=(r,area)=>r.drops.length<300&&r.drops.every(v=>Number.isFinite(v.id)&&canStand(v.x,v.z,0,area)&&(!v.item||validItem(v.item)))&&r.breakables.length<100&&r.breakables.every(v=>Number.isFinite(v.id)&&canStand(v.x,v.z,0,area)&&Number.isFinite(v.hp)&&(!v.reward||ITEMS[v.reward]));
 if(d.inventory.some(i=>!validItem(i))||new Set(d.inventory.map(i=>i.id)).size!==d.inventory.length||!validRegion(d,d.area)||Object.entries(d.regions).some(([area,r])=>!validRegion(r,area)))return null;
 if(!Array.isArray(d.visited)||d.visited.some(a=>!MAPS[a])||!['scoutRescued','scoutReward','bossDead'].every(k=>typeof d[k]==='boolean'))return null;
 if(!['face','invuln','dashTime','attack','dash','nova','potion'].every(k=>Number.isFinite(d.player[k])))return null;
 return{...createGame(),...d,player:{...d.player,area:d.area},events:[],hazards:[],projectiles:[]};}catch{return null;}}
