import test from 'node:test';
import {MAPS} from './maps.mjs';
import {makeItem,combatStats} from './equipment.mjs';
import assert from 'node:assert/strict';
import {createGame,service,interact,update,action,POINTS,canStand,findPath,snapshot,restore,objective,inventoryAction,dropItem} from './game-state.mjs';
const at=(s,id)=>Object.assign(s.player,POINTS.find(p=>p.id===id));
function accepted(){const s=createGame();at(s,'warden');assert.equal(service(s,'accept'),true);return s;}
function defeatZone(s,zone){for(const e of s.enemies.filter(e=>e.zone===zone)){Object.assign(s.player,{x:e.x,z:e.z});while(e.hp>0){s.player.nova=0;s.player.mp=100;action(s,'nova');}}update(s,.01);}

test('quest requires conversation nearby and can only be accepted once',()=>{const s=createGame();assert.equal(service(s,'accept'),false);at(s,'warden');assert.equal(service(s,'accept'),true);assert.equal(s.enemies.length,13);assert.ok(restore(snapshot(s)));assert.ok(s.enemies.every(e=>canStand(e.x,e.z,.8)));assert.equal(service(s,'accept'),false);assert.equal(s.gold,15);});
test('seals cannot be collected with guards alive, or collected twice',()=>{const s=accepted();at(s,'west');assert.equal(interact(s,'west'),false);defeatZone(s,'west');at(s,'west');assert.equal(interact(s,'west'),true);const gold=s.gold;assert.equal(interact(s,'west'),false);assert.equal(s.gold,gold);assert.deepEqual(s.seals,['west']);});
function enterCrypt(s){s.seals=['west','east'];s.stage='crypt';at(s,'altar');assert.equal(interact(s,'altar'),true);}
function enterDepths(s){enterCrypt(s);defeatZone(s,'crypt-west');at(s,'lever-west');interact(s,'lever-west');defeatZone(s,'crypt-east');at(s,'lever-east');interact(s,'lever-east');at(s,'descent');assert.equal(interact(s,'descent'),true);}
test('two floors, gated mechanisms, rescue, victory and next expedition preserve growth',()=>{const s=accepted();for(const zone of ['east','west']){defeatZone(s,zone);at(s,zone);assert.equal(interact(s,zone),true);}assert.equal(s.stage,'crypt');at(s,'altar');interact(s,'altar');assert.equal(s.area,'crypt');at(s,'descent');assert.equal(interact(s,'descent'),false);at(s,'scout');assert.equal(interact(s,'scout'),false);for(const z of ['crypt-west','crypt-east']){defeatZone(s,z);at(s,z==='crypt-west'?'lever-west':'lever-east');interact(s,z==='crypt-west'?'lever-west':'lever-east');}at(s,'scout');assert.equal(interact(s,'scout'),true);at(s,'descent');interact(s,'descent');assert.equal(s.area,'depths');at(s,'ritual');assert.equal(interact(s,'ritual'),false);defeatZone(s,'depths-guard');at(s,'ritual');assert.equal(interact(s,'ritual'),true);assert.equal(interact(s,'ritual'),false);defeatZone(s,'boss');assert.equal(s.stage,'return');at(s,'rift-home');interact(s,'rift-home');assert.equal(s.area,'overworld');at(s,'portal');interact(s,'portal');assert.equal(s.stage,'done');assert.equal(s.phase,'explore');at(s,'warden');assert.equal(service(s,'claim-scout'),true);assert.equal(service(s,'claim-scout'),false);const level=s.level,items=s.inventory.length;assert.equal(service(s,'expedition'),true);assert.equal(s.cycle,1);assert.equal(s.level,level);assert.equal(s.inventory.length,items);assert.deepEqual(s.levers,[]);at(s,'altar');interact(s,'altar');assert.equal(s.enemies.length,10);assert.ok(s.enemies.every(e=>e.maxHp>62));});
test('altar and return portal enforce prerequisites and distance',()=>{const s=accepted();assert.equal(interact(s,'altar'),false);at(s,'altar');assert.equal(interact(s,'altar'),false);at(s,'portal');assert.equal(interact(s,'portal'),false);});
test('chests are one-time and currency upgrades have real costs and caps',()=>{const s=createGame();at(s,'chest-camp');interact(s,'chest-camp');assert.equal(s.gold,22);assert.equal(s.potions,4);assert.equal(interact(s,'chest-camp'),false);at(s,'forge');assert.equal(service(s,'weapon'),false);assert.equal(s.weapon,0);s.gold=100;assert.equal(service(s,'weapon'),true);assert.equal(s.gold,70);assert.equal(service(s,'weapon'),true);assert.equal(s.gold,15);assert.equal(service(s,'weapon'),false);assert.equal(service(s,'buy'),false);s.gold=18;assert.equal(service(s,'buy'),true);assert.equal(s.gold,0);});
test('rest refills resources only near campfire and records checkpoint',()=>{const s=createGame();s.player.hp=15;s.potions=0;assert.equal(service(s,'rest'),false);at(s,'fire');assert.equal(service(s,'rest'),true);assert.equal(s.player.hp,100);assert.equal(s.potions,2);assert.ok(s.events.some(e=>e.type==='checkpoint'));});
test('snapshot round trip keeps progression and rejects malformed saves',()=>{const s=accepted();defeatZone(s,'west');at(s,'west');interact(s,'west');at(s,'fire');service(s,'rest');const text=snapshot(s),r=restore(text);assert.ok(r);assert.deepEqual(r.seals,['west']);assert.equal(r.gold,s.gold);assert.equal(r.enemies.length,7);assert.deepEqual(r.events,[]);assert.equal(restore('{invalid'),null);const bad=JSON.parse(text);bad.data.gold=-1;assert.equal(restore(JSON.stringify(bad)),null);bad.data.gold=1;bad.data.player.x=Infinity;assert.equal(restore(JSON.stringify(bad)),null);});
test('melee respects facing, cooldown and weapon growth',()=>{const s=accepted(),e=s.enemies[0];Object.assign(s.player,{x:e.x,z:e.z-1,face:0});const hp=e.hp;action(s,'attack');assert.equal(e.hp,hp-29);assert.equal(action(s,'attack'),false);s.player.attack=0;s.weapon=1;action(s,'attack');assert.equal(e.hp,hp-68);});
test('nova mana, full-health potions and death actions are bounded',()=>{const s=createGame();assert.equal(action(s,'potion'),false);assert.equal(s.potions,3);action(s,'nova');assert.equal(s.player.mp,65);assert.equal(action(s,'nova'),false);s.player.nova=0;s.player.mp=34;assert.equal(action(s,'nova'),false);s.player.hp=0;update(s,.02);assert.equal(s.phase,'dead');assert.equal(action(s,'potion'),false);});
test('telegraph damages only after windup; dodge prevents the hit',()=>{for(const dodge of[false,true]){const s=accepted(),e=s.enemies[0];Object.assign(s.player,{x:e.x,z:e.z+1});s.enemies=[e];e.cooldown=0;update(s,.01);assert.equal(s.player.hp,100);assert.equal(s.hazards.length,1);const h=s.hazards[0];h.left=.01;Object.assign(s.player,{x:h.x,z:h.z});if(dodge)action(s,'dash');update(s,.02);assert.equal(s.player.hp,dodge?100:88);}});
test('archer releases a projectile and boss enrage adds warnings',()=>{const s=accepted(),e=s.enemies.find(e=>e.kind==='archer');s.enemies=[e];Object.assign(s.player,{x:e.x+5,z:e.z});e.cooldown=0;update(s,.01);s.hazards[0].left=.01;update(s,.02);assert.equal(s.projectiles.length,1);const b=accepted();enterDepths(b);defeatZone(b,'depths-guard');at(b,'ritual');interact(b,'ritual');const boss=b.enemies.find(e=>e.boss);boss.hp=boss.maxHp*.4;Object.assign(b.player,{x:boss.x,z:boss.z+2});boss.cooldown=0;update(b,.01);assert.equal(b.hazards.filter(h=>h.owner===boss.id).length,3);});
test('all points reachable and click path rejects solid obstacles',()=>{for(const p of POINTS){const area=p.area||'overworld';assert.ok(canStand(p.x,p.z,.78,area),p.id);assert.ok(findPath({...MAPS[area].spawn,area},p).length,p.id);}const path=findPath({x:-8,z:-13},{x:-8,z:-4});assert.ok(path.length>9);assert.ok(path.every(p=>canStand(p.x,p.z,.78)));assert.deepEqual(findPath({x:0,z:0},{x:-8,z:-9}),[]);});

test('map caches keep defeated guards, drops and broken objects across reload and backtracking',()=>{const s=accepted();enterCrypt(s);defeatZone(s,'crypt-west');at(s,'crypt-exit');interact(s,'crypt-exit');const r=restore(snapshot(s));assert.ok(r);assert.equal(r.regions.crypt.enemies.length,7);at(r,'altar');interact(r,'altar');assert.equal(r.enemies.length,7);assert.ok(!r.enemies.some(e=>e.zone==='crypt-west'));assert.ok(restore(snapshot(r)));});
test('equipment changes combat stats, cannot sell worn items or sell away from forge',()=>{const s=createGame();s.inventory.push(makeItem('fang',1),makeItem('hide',2));assert.equal(inventoryAction(s,'equip',1),true);assert.equal(combatStats(s).attack,41);assert.equal(inventoryAction(s,'sell',2),false);at(s,'forge');assert.equal(inventoryAction(s,'sell',1),false);assert.equal(inventoryAction(s,'sell',2),true);assert.equal(s.gold,14);assert.equal(s.inventory.length,1);assert.ok(restore(snapshot(s)));});
test('talent points, rank caps and max health persist',()=>{const s=createGame();assert.equal(inventoryAction(s,'learn','blade'),false);s.skillPoints=5;for(let i=0;i<3;i++)assert.equal(inventoryAction(s,'learn','vigor'),true);assert.equal(inventoryAction(s,'learn','vigor'),false);assert.equal(s.player.maxHp,154);assert.equal(s.skillPoints,2);assert.ok(restore(snapshot(s)));});
test('full bag leaves loot on ground and resumes pickup after sale',()=>{const s=createGame();at(s,'forge');for(let i=0;i<16;i++)s.inventory.push(makeItem('iron',++s.serial));dropItem(s,s.player.x,s.player.z,'ember');update(s,.01);assert.equal(s.inventory.length,16);assert.equal(s.drops.length,1);inventoryAction(s,'sell',1);update(s,.01);assert.equal(s.drops.length,0);assert.equal(s.inventory.at(-1).key,'ember');});
test('legacy v2 saves migrate to dungeon entry without losing seals or upgrades',()=>{const s=accepted();s.seals=['west','east'];s.stage='boss';s.weapon=2;const save=JSON.parse(snapshot(s));save.version=2;const r=restore(JSON.stringify(save));assert.ok(r);assert.equal(r.stage,'crypt');assert.equal(r.weapon,2);assert.equal(r.area,'overworld');});
test('dungeon walls block walking and trap damage follows an active pulse',()=>{const s=accepted();enterDepths(s);s.enemies=[];Object.assign(s.player,{x:-3,z:5,invuln:0});s.time=1;update(s,.01);assert.equal(s.player.hp,s.player.maxHp);s.time=4;s.player.invuln=0;const before=s.player.hp;update(s,.01);assert.ok(s.player.hp<before);assert.equal(canStand(12,18,.4,'depths'),false);});

test('breakable rewards happen once and reject corrupted cached loot',()=>{const s=accepted();enterCrypt(s);Object.assign(s.player,{x:-3,z:16});action(s,'nova');assert.equal(s.breakables.length,2);const gold=s.gold;s.player.nova=0;s.player.mp=100;action(s,'nova');assert.equal(s.gold,gold);update(s,.01);assert.ok(s.inventory.some(i=>i.key==='ash'));at(s,'crypt-exit');interact(s,'crypt-exit');const bad=JSON.parse(snapshot(s));bad.data.regions.crypt.drops.push({id:999,x:0,z:18,item:{key:'iron',name:'forged name',slot:'weapon'}});assert.equal(restore(JSON.stringify(bad)),null);});
test('completed expedition can revisit lower floor without resetting completion',()=>{const s=accepted();enterDepths(s);s.bossDead=true;s.stage='done';at(s,'depths-exit');interact(s,'depths-exit');at(s,'descent');interact(s,'descent');assert.equal(s.stage,'done');assert.equal(objective(s).target,'rift-home');});
