import {modules,upstream,defaults,trainTarget,trainStep,lighting,budget,terrain,arcSamples,camera,stages,promptFor,smooth,clamp,validateConfiguration} from './model.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let active='terrain',view='anatomy',parameters=defaults(active),step=0,animation=0,run=null;
const getModule=()=>modules.find(m=>m.id===active);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,n=2)=>Number(v).toFixed(n).replace(/\.?0+$/,'')||'0';
function stopRun(){cancelAnimationFrame(animation);animation=0;run=null}
function changeView(next){view=next;$$('.view').forEach(e=>e.hidden=e.id!==next);$$('[data-view]').forEach(e=>e.setAttribute('aria-current',e.dataset.view===next?'page':'false'));if(next!=='lab')stopRun();else if(!run){renderControls();renderResult()}}
function choose(id){stopRun();active=id;parameters=defaults(id);renderModule();renderControls();renderResult();if(view==='recipe')changeView('anatomy')}
function renderModule(){const m=getModule();$('#chapter').textContent=m.n+' / 08';$('#modules').innerHTML=modules.map(m=>`<button class="module" data-module="${m.id}" aria-current="${m.id===active}"><span>${m.n}</span>${m.name}</button>`).join('');$('#hotspots').innerHTML=modules.map(m=>`<button class="hotspot" data-module="${m.id}" style="left:${m.spot[0]}%;top:${m.spot[1]}%" aria-label="分析${m.name}" title="${m.name}" aria-pressed="${m.id===active}">${m.n}</button>`).join('');$('#module-title').textContent=m.title;$('#module-summary').textContent=m.summary;$('#driver-chain').innerHTML=[['输入 INPUT',m.input],['计算 PROCESS',m.process],['结果 OUTPUT',m.output]].map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join('');$('#implementation').innerHTML=m.steps.map(s=>`<li>${s}</li>`).join('');$('#failure').textContent=m.failure;$('#source-row').innerHTML=m.sources.map(s=>`<a href="${upstream+s}" target="_blank" rel="noopener">${s} ↗</a>`).join('');$('#dependency-map').innerHTML=m.dependencies.map((d,i)=>i===1?`<strong>${d}</strong>`:`<span>${d}</span>`).join('<span aria-hidden="true">→</span>');}
function renderControls(){const m=getModule();$('#lab-title').textContent=m.lab;$('#lab-intro').textContent=m.intro;$('#formula').textContent=m.formula;$('#lab-controls').innerHTML=m.controls.map(c=>c[2]==='select'?`<label class="control"><span class="control-head">${c[1]}</span><select data-param="${c[0]}">${c[3].map(([v,l])=>`<option value="${v}" ${parameters[c[0]]===v?'selected':''}>${l}</option>`).join('')}</select></label>`:`<label class="control"><span class="control-head">${c[1]}<output id="out-${c[0]}">${fmt(parameters[c[0]])}${c[6]}</output></span><input type="range" data-param="${c[0]}" min="${c[2]}" max="${c[3]}" step="${c[4]}" value="${parameters[c[0]]}" aria-label="${c[1]}"><small>${c[2]} — ${c[3]} ${c[6]}</small></label>`).join('')+(active==='train'?'<button id="run-train" class="primary">演示一次进站 →</button><button id="stop-train" class="quiet" style="margin-top:12px;width:100%" hidden>停止演示</button>':'')}
const line=(points,cls='graph-line')=>`<path class="${cls}" d="${points.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`).join(' ')}"/>`;
const label=(x,y,s,extra='')=>`<text x="${x}" y="${y}" class="svg-label ${extra}">${s}</text>`;
function svg(body,title){return `<svg viewBox="0 0 660 310" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title>${body}</svg>`}
function axes(xLabel,yLabel){return `<path d="M55 28V260H620" class="graph-axis"/>${label(60,22,yLabel)}${label(470,300,xLabel)}`}
function metrics(items){return items.map(([v,l])=>`<div class="readout"><b>${v}</b><span>${l}</span></div>`).join('')}
function renderResult(){const p=parameters;let body='',text='',values=[];
if(active==='terrain'){const pts=Array.from({length:151},(_,i)=>{const x=-45+i*.6;return[55+(x+45)*6.1,244-terrain(x,p)*4.7]});body=axes('横向位置 x','地形高度')+`<path d="${line(pts).match(/d="([^"]+)/)[1]}L604,260L55,260Z" fill="#6ddad014"/>`+line(pts)+`<line x1="403" y1="38" x2="403" y2="260" stroke="#efb568" stroke-dasharray="5 5"/>`+label(420,60,'河谷中心');values=[[fmt(terrain(0,p)),'山峰附近高度'],[fmt(terrain(12,p)),'河谷中心高度'],[fmt(p.width),'河谷宽度参数']];text='先改变地形函数，再重新生成网格。河流、建筑和植被查询同一个高度接口，避免各自猜测地面位置。';}
if(active==='track'){const a=arcSamples(p.samples,p.tension),map=([x,z])=>[330+x*5.4,140-z*3.4];body=line(a.points.map(map))+a.samples.map(q=>{const[x,y]=map(q);return`<circle cx="${x}" cy="${y}" r="3.5" fill="#efb568"/>`}).join('')+label(35,300,'青色：路径  /  琥珀色：近似等弧长采样');values=[[fmt(a.length,1),'平面线路长度'],[p.samples,'采样点数'],[fmt(a.length/p.samples),'相邻采样路程']];text='张力改变曲线形状，采样数只改变细分密度。这里忽略上游线路高程；增加采样精度能减少折线感，但不应改变列车的世界速度。';}
if(active==='train'){const t=trainTarget(p.ahead,p.speed,p.angle),v=run?.v??t.target;body=axes('到站距离 →','目标速度')+line(Array.from({length:151},(_,i)=>[55+i*3.65,250-trainTarget(i*.4,p.speed,p.angle).target*23]))+`<line x1="55" y1="${250-t.cruise*23}" x2="603" y2="${250-t.cruise*23}" stroke="#efb568" stroke-dasharray="6 5"/><circle cx="${55+p.ahead/60*547.5}" cy="${250-t.target*23}" r="7" fill="#6ddad0" stroke="#fff"/>`+label(70,292,'车站 0')+label(480,40,'虚线：巡航上限');values=[[fmt(t.target),'目标速度'],[fmt(v),run?'当前速度':'目标稳定速度'],[run?.dwell>0?fmt(run.dwell,1)+'s':run?.done?'已完成':t.brake<t.cruise?'制动约束':'巡航约束','运行状态']];text=run?.done?'到站后速度为零，驻留计时 6.2 秒。本实验在驻留结束后停止；上游随后继续下一圈。':'靠近车站时制动上限降低，弯道则限制巡航速度。青点表示当前距离对应的目标值；演示时实际速度受加减速限制，不能瞬间跳到目标。';}
if(active==='water'){const fade=smooth(.025,.22,p.depth),wave=x=>(Math.sin(x*2.2-p.time*1.5)*.018+Math.sin(-x*.7-p.time*2.2)*.009)*fade*p.amplitude;const water=Array.from({length:201},(_,i)=>[55+i*2.75,100-wave(i/18)*600]);body=axes('沿水面位置','位移（纵向放大）')+`<rect x="55" y="100" width="550" height="${Math.max(4,p.depth*96)}" fill="#246b712e"/>`+line(water)+`<line x1="55" y1="${100+p.depth*96}" x2="605" y2="${100+p.depth*96}" stroke="#efb568" stroke-width="3"/>`+label(80,277,'琥珀色：河床')+label(420,45,'水面微小位移');const alpha=smooth(.012,.17,p.depth)*(.24+(.91-.24)*smooth(0,.62,p.depth));values=[[fmt(fade),'岸边波纹系数'],[fmt(alpha),'基础透明度 α'],[fmt(.027*fade*p.amplitude,3),'位移幅度上界']];text='越靠近岸边，波纹与透明度逐渐减弱。微小几何位移配合更强的法线变化，制造丰富反光；本图放大位移以便观察。';}
if(active==='weather'){const rain=smooth(0,1,p.rain),visible=Math.max(0,p.rain-.03);body=label(40,26,'雨丝方向示意 · 风向 →');for(let i=0;i<70;i++){const seed=((i*37)%71)/71,opacity=smooth(seed,seed+.06,p.rain),x=40+((i*83)%560),y=45+((i*47+p.time*(50+seed*30))%200),dx=28*.08*p.wind*8;body+=`<line x1="${x}" y1="${y}" x2="${x+dx}" y2="${y+28}" stroke="#8cc6dc" stroke-width="2" opacity="${opacity*.85}"/>`;}body+=label(40,295,'共享时间 + 每条雨丝的种子');values=[[Math.round(8400*visible),'约可见雨丝数'],[fmt(p.wind*.08,3),'横向倾斜系数'],[Math.round(p.wind*100)+'%','共享风力输入']];text='上游预先创建 8400 条雨丝，再通过透明度控制雨量，因此低雨量不等于同比减少顶点处理。植被、落叶和雨丝读取同一风力，但各自使用不同位移公式。';}
if(active==='light'){const s=lighting(p.mode,p.time),names=[['sun','太阳强度',3.6],['ambient','环境光',1.04],['night','夜间系数',1],['wet','湿润程度',1]];body=names.map(([key,name,max],i)=>{const y=30+i*66;return label(20,y+17,name)+`<rect x="150" y="${y}" width="390" height="25" rx="3" fill="#233443"/><rect x="150" y="${y}" width="${clamp(s[key]/max,0,1)*390}" height="25" rx="3" fill="${key==='wet'?'#efb568':'#6ddad0'}"/>`+label(552,y+19,fmt(s[key]))}).join('');values=[[fmt(s.rain),'当前雨量'],[s.fog.toFixed(4),'预设雾密度过渡值'],[fmt(p.time,1)+'s','从黄昏开始过渡']];text='各条形分别按各自范围缩放，不能横向比较物理能量。湿润使用更慢的插值；源码的最终雾密度还会叠加 currentRain × 0.0005，本项显示叠加前的预设部分。';}
if(active==='camera'){const c=camera(p),xy=(f,h)=>[55+550*f,255-h*7.5],ground=Array.from({length:151},(_,i)=>xy(i/150,c.ground(i/150))),path=Array.from({length:151},(_,i)=>xy(i/150,c.y(i/150)));body=axes('镜头移动进度','高度')+line(ground,'graph-secondary')+line(path)+`<circle cx="${55+c.e*550}" cy="${255-c.y(c.e)*7.5}" r="8" fill="#eaf0f6"/>`+label(70,55,'青色：镜头轨迹')+label(390,55,'虚线：地形');values=[[fmt(c.e*100,1)+'%','缓动后路程比例'],[fmt(c.lift),'需要的抬升量'],[fmt(c.y(c.e)-c.ground(c.e)),'当前离地高度']];text='镜头位置与注视点都需要插值。时间过半不一定代表运动匀速；起止减速形成平稳感。这里用单个山峰展示源码的抬升方法，真实场景还需检查建筑遮挡。';}
if(active==='budget'){const b=budget(p);body=label(40,27,'LOD 滞回区间')+`<line x1="65" y1="108" x2="605" y2="108" stroke="#355063" stroke-width="22"/><line x1="245" y1="108" x2="353" y2="108" stroke="#efb568" stroke-width="22" opacity=".8"/><circle cx="${65+(p.distance-40)*9}" cy="108" r="11" fill="#6ddad0" stroke="#fff"/>`+label(215,150,'60')+label(338,150,'72')+label(65,188,'近景 ←')+label(475,188,'→ 远景')+label(65,240,'60—72 之间保留进入前的细节状态');values=[[b.near?'近景':'远景','当前几何模型'],[fmt(b.dpr)+'×','调整后 DPR'],[Math.round(b.saved*100)+'%','像素数量减少']];text=`当前每帧像素量约为 DPR=1 时的 ${fmt(b.pixels)} 倍。只有持续压力超过 2.5 秒且冷却结束才调节；本实验只判断一次决策，没有测量真实 FPS。`;}
$('#lab-diagram').innerHTML=svg(body,getModule().lab);$('#lab-readouts').innerHTML=metrics(values);$('#lab-explanation').textContent=text;}
function renderRecipe(){const s=stages[step];$('#roadmap').innerHTML=stages.map((s,i)=>`<button data-step="${i}" aria-pressed="${i===step}"><span>STEP 0${i+1}</span>${s.name}</button>`).join('');$('#step-title').textContent=`0${step+1} / ${s.name}`;$('#step-detail').innerHTML=`<p>${s.goal}</p><h3>这一阶段交付什么</h3><p>${s.deliver}</p><h3>如何验收</h3><p>${s.accept}</p><h3>控制范围</h3><p>${s.avoid}</p>`;$('#prompt').value=promptFor(step,$('#theme').value);$('#copy-status').textContent='';}
function configure(input){const next=validateConfiguration(input,{module:active,view,parameters});stopRun();active=next.module;parameters=next.parameters;renderModule();renderControls();renderResult();changeView(next.view);return{module:active,view,parameters:{...parameters}}}
$('#modules').addEventListener('click',e=>{const b=e.target.closest('[data-module]');if(b)choose(b.dataset.module)});
$('#hotspots').addEventListener('click',e=>{const b=e.target.closest('[data-module]');if(b)choose(b.dataset.module)});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.view)));
$('#try-lab').addEventListener('click',()=>changeView('lab'));
$$('[data-image]').forEach(b=>b.addEventListener('click',()=>{const night=b.dataset.image==='night';$('#reference-image').src=night?'../assets/02-night-hero.jpg':'../assets/01-evening-hero.jpg';$('#reference-image').alt=night?'固定版本实测夜景：深色山体、沿线暖色灯光和瀑布':'固定版本实测黄昏：秋色山林、钢桥和瀑布';$$('[data-image]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
$('#lab-controls').addEventListener('input',e=>{const el=e.target;if(!el.dataset.param)return;stopRun();parameters[el.dataset.param]=el.tagName==='SELECT'?el.value:Number(el.value);if(el.tagName!=='SELECT'){const c=getModule().controls.find(c=>c[0]===el.dataset.param);$('#out-'+c[0]).textContent=fmt(parameters[c[0]])+c[6]}$('#run-train')?.removeAttribute('disabled');if($('#stop-train'))$('#stop-train').hidden=true;renderResult()});
$('#reset-lab').addEventListener('click',()=>choose(active));
$('#lab-controls').addEventListener('click',e=>{if(e.target.id==='stop-train'){stopRun();renderControls();renderResult();return}if(e.target.id!=='run-train')return;stopRun();if(parameters.ahead<.2)parameters.ahead=30;run={ahead:parameters.ahead,v:Math.min(3.1,trainTarget(parameters.ahead,parameters.speed,parameters.angle).target),dwell:0,done:false};$('#run-train').disabled=true;$('#stop-train').hidden=false;let last=performance.now();function tick(now){if(!run)return;run=trainStep(run,Math.min((now-last)/1000,.1),parameters.speed,parameters.angle);last=now;parameters.ahead=run.ahead;const input=$('[data-param="ahead"]');input.value=run.ahead;$('#out-ahead').textContent=fmt(run.ahead)+'单位';renderResult();if(run.done&&run.dwell<=0){$('#run-train').disabled=false;$('#stop-train').hidden=true;return}animation=requestAnimationFrame(tick)}animation=requestAnimationFrame(tick)});
$('#roadmap').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b){step=Number(b.dataset.step);renderRecipe()}});$('#theme').addEventListener('input',renderRecipe);
$('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#prompt').value);$('#copy-status').textContent='任务已复制，可直接交给开发者或 AI。'}catch{$('#prompt').focus();$('#prompt').select();$('#copy-status').textContent='请按 Ctrl+C（Mac 使用 ⌘C）复制已选中的任务。'}});
renderModule();renderControls();renderResult();renderRecipe();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'configure_railway_analysis',title:'调整铁路驱动分析',description:'选择一个能力模块和分析方式，并调整该模块的教学参数。仅改变当前页面，不修改上游场景或文件。',inputSchema:{type:'object',properties:{module:{type:'string',enum:modules.map(m=>m.id)},view:{type:'string',enum:['anatomy','lab','recipe']},parameters:{type:'object',additionalProperties:{type:['number','string']}}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:configure},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
