export const upstream='https://github.com/iamtechartist/mountain-railway-diorama/blob/6e8b0fbb806e486d7819b6d297b92f4ecf3d258b/';
export const modules=[
{id:'terrain',name:'地形与空间',n:'01',spot:[42,20],title:'先建立共同的空间规则',summary:'山体不是孤立的背景。高度场、河道和线路一起决定每个物体可以出现在哪里。',input:'山峰高度、河道中心线、轨道控制点、场景边界',process:'高度函数 → 铁路整平 / 河谷下切 → 网格与顶点颜色',output:'有起伏、河谷、站台平台和隧道开口的微缩地形',dependencies:['山峰与河道参数','height(x, z)','轨道 / 建筑 / 植被 / 镜头'],steps:['提供统一的 height(x, z)，先生成规则采样网格和法线。','接入线路距离查询；沿轨道整平、沿河道下切，站台单独做平台。','加入边界剖面与隧道口裁剪，最后根据高度、坡度和湿度着色。'],failure:'只有高度场不能表达贯通隧道。入口需裁剪网格，内部需生成拱形通道；否则列车会穿山或洞口被“地形帘”封住。',sources:['world.js','geology.js'],lab:'地形剖面',intro:'拖动山峰高度、河谷深度和宽度，观察它们怎样共同改变截面。这里是可解释的简化高度函数，未重建上游完整地形。',formula:'height(x) = base + peak · exp(−x² / 500) − depth · exp(−(x − 12)² / width²)',controls:[['peak','山峰高度',10,40,1,28,'单位'],['depth','河谷下切',0,24,1,15,'单位'],['width','河谷宽度',2,15,.5,6,'单位']]},
{id:'track',name:'轨道与结构',n:'02',spot:[62,57],title:'一条曲线，驱动整个线路',summary:'钢轨、枕木、桥梁与列车都读取同一条路径；几何与运动因此拥有共同坐标。',input:'闭合控制点、曲线张力、轨距、构件间距',process:'Catmull–Rom 曲线 → 弧长采样 → 截面扫掠与重复布置',output:'连续钢轨、均匀枕木、对齐路线的桥梁构件',dependencies:['控制点','曲线与切线','钢轨 / 枕木 / 列车'],steps:['把线路定义成闭合曲线，并缓存累计弧长表。','沿弧长采样中心点和切线，通过横向偏移生成两侧钢轨。','沿路径扫掠钢轨截面，按固定间距放枕木，给桥隧分段明确标识。'],failure:'直接按曲线参数均分不等于按距离均分，会让枕木疏密变化、列车忽快忽慢。桥隧跨度还要与地形和净空一起验证。',sources:['world.js','geometry.js'],lab:'曲线与采样',intro:'俯视线路取自上游的 12 个控制点，仅投影到平面。试着改变张力和采样数量：青色路径改变，琥珀色采样点按近似弧长重排。',formula:'p = curve.getPointAt(u); tangent = curve.getTangentAt(u); rail = p ± normal · gauge / 2',controls:[['tension','曲线张力',.1,.8,.01,.34,''],['samples','等距采样数',12,100,2,36,'个']]},
{id:'train',name:'列车运行',n:'03',spot:[19,58],title:'距离驱动位置，状态驱动速度',summary:'列车沿路径移动；弯道、站点与驻留状态共同决定它每一帧能前进多远。',input:'帧间隔 dt、速度倍率、弯道夹角、到站距离、暂停状态',process:'目标速度 = min(弯道巡航, 进站制动) → 限制加减速 → 更新路程',output:'弯道减速、平稳进站、停车 6.2 秒再出发',dependencies:['路径与站点','路程 / 速度 / 驻留状态','车体 / 转向架 / 车灯 / 镜头'],steps:['以累计路程 s 为唯一位置状态，按弧长采样每节车厢。','用前后采样点确定车身方向，转向架分别读取局部切线。','加入制动目标、加减速度限制和驻站状态机，再连到状态栏。'],failure:'只给整列车一个朝向会让后车厢在弯道错位。用屏幕帧数代替 dt 会导致不同设备车速不同。',sources:['train.js','main.js'],lab:'进站制动实验',intro:'拖动到站距离或运行一次进站。公式和加减速度限制取自上游；该实验固定弯道角度，只演示一次到站，不模拟整圈线路。',formula:'cruise = 4.6 × speed × clamp(1 − angle × 0.95, 0.53, 1)\nbrake = √max(0, 2 × 0.57 × (ahead − 0.06)); target = min(cruise, brake)',controls:[['ahead','到站距离',0,60,.1,30,'单位'],['speed','速度倍率',.25,1.8,.05,1,'×'],['angle','前后切线夹角',0,1,.02,.2,'rad']]},
{id:'water',name:'河流与瀑布',n:'04',spot:[67,78],title:'让水看起来流动，不必求解整条河',summary:'河岸决定形状，深度决定颜色与透明度，时间扰动表面法线，反射与泡沫提供流动线索。',input:'河床高度、水位、时间、波纹、岩石位置、光照',process:'贴合河岸的网格 → 深度着色 → 动态法线 / 泡沫 / 平面反射',output:'浅滩渐隐、深潭吸光、移动高光和连续瀑布',dependencies:['河床与水位','深度 / 时间 / 扰动法线','岸边透明度 / 波纹 / 反射'],steps:['用地形与水位的交界查找左右河岸，并把水深写入顶点属性。','先实现深浅颜色与岸边透明度，再叠加随时间变化的法线和泡沫。','独立实现瀑布落差与雾气，最后添加按需更新的反射。'],failure:'只滚动一张蓝色贴图会缺少真实河岸、深浅变化与光照联系。此项目采用视觉近似，不能用来计算水量或洪水。',sources:['river.js','cascade.js'],lab:'水深与波纹',intro:'上方线条表示水面位移，底部标出河床。深度渐变和双正弦位移借鉴源码，幅度倍率是教学控制；没有执行流体求解或真实反射。',formula:'shoreFade = smoothstep(0.025, 0.22, depth)\nΔy = [sin(2.2x − 1.5t) × 0.018 + sin(−0.7x − 2.2t) × 0.009] × shoreFade',controls:[['depth','水深',0,1.4,.02,.5,'单位'],['amplitude','波纹幅度倍率',0,3,.1,1,'×'],['time','时间切片',0,12,.1,3,'s']]},
{id:'weather',name:'风雨与植被',n:'05',spot:[28,43],title:'把大量细节交给批量几何和时间',summary:'树木不逐棵独立绘制，雨滴不逐滴运行物理。实例化、随机种子与 Shader 共同降低重复计算。',input:'风力、雨量、时间、随机种子、可种植区域',process:'实例化植被 + 雨丝线段 / 落叶网格 → Shader 更新位置与透明度',output:'随风摆动的植被、倾斜雨丝、薄雾和间歇落叶',dependencies:['风 / 雨 / 时间','顶点位移与可见性','植被 / 雨丝 / 落叶 / 水面涟漪'],steps:['先做一棵树的几何变体，再按空间规则批量放置并实例化。','将风的位移写入顶点 Shader，并给阴影使用相同的位移逻辑。','雨滴批量用线段绘制，通过固定种子、时间与雨量控制位置和显隐。'],failure:'只移动可见树叶、不移动阴影会穿帮。树木随机摆放必须避开线路、建筑与镜头视线，实例化也不代表零成本。',sources:['vegetation.js','weather.js'],lab:'风雨驱动关系',intro:'线段图只解释雨丝方向和数量，非原版场景。雨丝倾斜关系取自源码；可见数量是透明度规则的近似估计。',formula:'rain.x += rain.y × 0.08 × wind; visible = smoothstep(seed, seed + 0.06, rain)\n大量物体共享材质与时间，只保留种子和位置差异',controls:[['wind','风力',0,1,.05,.45,''],['rain','雨量',0,1,.05,.68,''],['time','时间切片',0,6,.1,2,'s']]},
{id:'light',name:'环境与灯光',n:'06',spot:[86,56],title:'一次模式切换，联动多个系统',summary:'夜景来自天空、环境光、局部灯光、湿润材质和曝光的协调变化，而非简单把画面变暗。',input:'环境预设、过渡时间、雨量与湿润程度',process:'共享状态 → 指数插值 → 天空 / 光照 / 材质 / Bloom',output:'平滑的昼夜雨景变化，受控的冷暖对比与灯光高光',dependencies:['环境模式','shared.night / wetness / sun','天空 / 材质 / 车灯 / 水体 / 光晕'],steps:['先定义包含光色、太阳强度、雾与湿度的环境预设。','将共享状态传入各材质与系统；按 dt 插值，不直接跳变。','添加有限照射范围的局部灯光，最后用高光过滤和低分辨率 Bloom。'],failure:'把所有东西一起压暗会丢失夜景层次；过度 Bloom 会冲淡黑位。天空、灯光与水面若使用不同时间状态，会显得互不相关。',sources:['main.js','luminous.js','geometry.js'],lab:'环境参数联动',intro:'以黄昏为起点，选择目标环境并移动过渡时间。预设数值来自源码；本页以条形图展示响应，湿润过渡用 60 Hz 离散更新计算。',formula:'k = 1 − exp(−dt × 1.5); value = lerp(value, target, k)\nwetness 使用 k × 0.45，晚于灯光变化稳定',controls:[['mode','目标环境','select',[['day','白天'],['evening','黄昏'],['rain','雨天'],['night','夜间']],'night'],['time','过渡时间',0,6,.1,2,'s']]},
{id:'camera',name:'镜头编排',n:'07',spot:[78,27],title:'事件决定看哪里，地形决定怎样过去',summary:'列车进度触发镜头，平滑曲线控制运动节奏，路径采样决定镜头抬升幅度。',input:'列车进度、当前镜头、目标镜头、地形高度、画幅',process:'按区间选镜 → 缓动插值 → 地形采样与抬升 → 更新相机和目标点',output:'提前等待出隧道、在站台捕捉到站、平稳转换构图',dependencies:['列车进度','镜头规则与过渡','相机位置 + 注视目标'],steps:['先人工设计少量有用的构图，分别存储 position 和 target。','用轨道事件选择下一镜头，设置最短驻留时间，避免频繁切换。','插值位置和注视点，采样途中地形并抬升；手动拖动时退出自动模式。'],failure:'只让相机永远追着列车跑，会缺少构图变化；直接穿越两镜头连线可能穿山。源码抬升只处理地形，不能当成通用建筑碰撞系统。',sources:['cinematography.js','main.js'],lab:'镜头过渡与避地形',intro:'这是镜头移动的侧面剖面。缓动与抬升公式取自源码，障碍山体为教学构造；青色线表示相机轨迹，不是完整的三维碰撞模拟。',formula:'e = t³ × (t × (6t − 15) + 10)\ny = lerp(y₀, y₁, e) + sin(πe)^0.35 × lift',controls:[['height','途中地形高度',0,22,.5,12,'单位'],['time','过渡时间',0,5.4,.1,2.7,'s'],['distance','两镜头距离',20,100,5,60,'单位']]},
{id:'budget',name:'渲染预算',n:'08',spot:[48,86],title:'分开控制几何成本与像素成本',summary:'远处减少几何细节，持续 GPU 压力下降低分辨率，反射和阴影按较低频率刷新。',input:'镜头距离、当前 LOD、像素密度、GPU 耗时与持续时间',process:'LOD 滞回 → 实例化 / 合并 → 自适应像素密度 → 阴影与反射节流',output:'保留近处细节，限制重复绘制与高分辨率后处理开销',dependencies:['距离 + 持续 GPU 压力','LOD / 分辨率 / 更新频率','几何工作量 + 像素工作量'],steps:['先测 draw calls、三角形与 GPU 耗时，定位瓶颈。','对重复构件合并或实例化，对远景配置低细节模型并加滞回。','分开控制阴影、反射与 Bloom；持续压力后再调整像素密度。'],failure:'一次慢帧就降画质会造成反复跳变。GPU 计时扩展不可用时不能假定自动调节生效；DPR 已为 1 时源码也不会继续降。',sources:['render-budget.js','world.js','main.js'],lab:'LOD 与像素成本',intro:'LOD 使用上游道砟的 60 / 72 阈值。像素成本只按 DPR² 估算；假定 GPU 计时可用、持续耗时 >25ms 且调节冷却已结束，不是本机帧率测试。',formula:'near ? distance > 72 : distance < 60\n持续慢于 25ms 超过 2.5s → DPR 减 0.25（最低 1）',controls:[['distance','距细节分区',40,100,1,65,'单位'],['near','进入前 LOD','select',[['yes','近景模型'],['no','远景模型']],'yes'],['dpr','当前像素密度',1,1.5,.25,1.5,'×'],['duration','持续 GPU 压力',0,5,.1,3,'s']]}
];
export const modes={day:{sun:3.35,ambient:1.04,night:0,wet:0,rain:0,fog:.0019},evening:{sun:3.6,ambient:.55,night:.14,wet:0,rain:0,fog:.0024},rain:{sun:.5,ambient:.4,night:.79,wet:1,rain:.68,fog:.0042},night:{sun:.52,ambient:.15,night:1,wet:.46,rain:0,fog:.0027}};
export const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
export function validateConfiguration(input,current){
 if(!input||typeof input!=='object'||Array.isArray(input))throw Error('配置必须为对象');
 if(Object.keys(input).some(k=>!['module','view','parameters'].includes(k)))throw Error('包含未知配置项');
 const id=input.module??current.module,m=modules.find(m=>m.id===id),view=input.view??current.view;
 if(!m||!['anatomy','lab','recipe'].includes(view))throw Error('模块或分析方式无效');
 const parameters=id===current.module?{...current.parameters}:defaults(id);
 if(input.parameters!==undefined){if(!input.parameters||typeof input.parameters!=='object'||Array.isArray(input.parameters))throw Error('参数必须为对象');
 for(const[k,v]of Object.entries(input.parameters)){const c=m.controls.find(c=>c[0]===k);if(!c)throw Error('该模块没有参数 '+k);
 if(c[2]==='select'){if(!c[3].some(([key])=>key===v))throw Error('选项无效：'+k)}else if(typeof v!=='number'||!Number.isFinite(v)||v<c[2]||v>c[3])throw Error('参数超出范围：'+k);
 parameters[k]=v;}}
 return{module:id,view,parameters};
}
export const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)};
export function defaults(id){return Object.fromEntries(modules.find(m=>m.id===id).controls.map(c=>[c[0],c[2]==='select'?c[4]:c[5]]))}
export function trainTarget(ahead,speed,angle){const cruise=4.6*speed*clamp(1-angle*.95,.53,1),brake=Math.sqrt(Math.max(0,2*.57*(ahead-.06)));return{cruise,brake,target:Math.min(cruise,brake)}}
export function trainStep(state,dt,speed,angle){dt=clamp(dt,0,.1);if(state.dwell>0)return{...state,v:0,dwell:Math.max(0,state.dwell-dt)};if(state.done)return state;const {target}=trainTarget(state.ahead,speed,angle),v=state.v+clamp(target-state.v,-.68*dt,.34*dt);if(state.ahead<.12&&v<.32)return{ahead:0,v:0,dwell:6.2,done:true};return{...state,v:Math.max(0,v),ahead:Math.max(0,state.ahead-Math.max(0,v)*dt)}}
export function lighting(mode,time){const target=modes[mode];let s={...modes.evening};for(let t=0;t<time;){const dt=Math.min(1/60,time-t),k=1-Math.exp(-dt*1.5);for(const key of Object.keys(s))s[key]+=(target[key]-s[key])*k*(key==='wet'?.45:1);t+=dt;}return s}
export function budget(p){const near=p.near==='yes'?!(p.distance>72):p.distance<60;const dpr=p.duration>2.5?Math.max(1,p.dpr-.25):p.dpr;return{near,dpr,pixels:dpr*dpr,saved:1-dpr*dpr/(p.dpr*p.dpr)}}
export function terrain(x,p){return 4.5+p.peak*Math.exp(-x*x/500)-p.depth*Math.exp(-((x-12)**2)/(p.width*p.width))}
export const trackPoints=[[-33,22],[-17,25],[-1,24],[15,22],[31,18],[40,5],[36,-12],[23,-26],[1,-31],[-20,-26],[-34,-12],[-38,6]];
export function trackPoint(u,tension=.34){const n=trackPoints.length,f=((u%1)+1)%1*n,i=Math.floor(f),t=f-i;return [0,1].map(k=>{const p0=trackPoints[(i-1+n)%n][k],p1=trackPoints[i][k],p2=trackPoints[(i+1)%n][k],p3=trackPoints[(i+2)%n][k],v0=tension*(p2-p0),v1=tension*(p3-p1);return(2*t*t*t-3*t*t+1)*p1+(t*t*t-2*t*t+t)*v0+(-2*t*t*t+3*t*t)*p2+(t*t*t-t*t)*v1})}
export function arcSamples(count,tension){const pts=Array.from({length:1001},(_,i)=>trackPoint(i/1000,tension)),lengths=[0];for(let i=1;i<pts.length;i++)lengths.push(lengths[i-1]+Math.hypot(pts[i][0]-pts[i-1][0],pts[i][1]-pts[i-1][1]));const total=lengths.at(-1);let j=1;const samples=Array.from({length:count},(_,i)=>{const d=i/count*total;while(lengths[j]<d)j++;const f=(d-lengths[j-1])/(lengths[j]-lengths[j-1]);return pts[j].map((v,k)=>pts[j-1][k]+(v-pts[j-1][k])*f)});return{points:pts,samples,length:total}}
export function camera(p){const ground=f=>p.height*Math.exp(-(((f-.52)/.17)**2));let lift=0;for(let i=1;i<32;i++){const f=i/32;lift=Math.max(lift,(ground(f)+2.3-6)/Math.sin(f*Math.PI)**.35)}lift=Math.max(lift,Math.min(10,p.distance*.1));const t=clamp(p.time/5.4,0,1),e=t*t*t*(t*(t*6-15)+10);return{ground,lift,e,y:f=>6+Math.max(0,Math.sin(f*Math.PI))**.35*lift}}
export const stages=[
{name:'空间骨架',goal:'用最少几何建立地形、路线和桥隧关系。',deliver:'可旋转的灰模场景；height(x,z)、闭合 route 与站点区间。',tasks:['建立 Three.js 场景、相机、控制器与按 dt 更新的主循环。','先做高度网格和闭合曲线，沿轨道整平；为桥、隧道、站台留出空间。','使用简单体块占位，并提供净空和落地检查。'],accept:'线路连续闭合；车站平台落地；桥跨峡谷；隧道口无遮挡；画面能旋转缩放。',avoid:'不做复杂树叶、水面反射、Bloom 或高精度车体。',sources:['world.js','geometry.js']},
{name:'运行逻辑',goal:'让列车以可靠的距离与状态系统运行。',deliver:'两节列车、转向架朝向、进站 / 驻站 / 出站状态和暂停。',tasks:['沿同一曲线按弧长采样，以累计路程定位车体与转向架。','接入弯道速度上限、进站制动、加减速限制和驻站计时。','把状态机与视觉分离，避免帧率影响路程。'],accept:'同样模拟时长下不同 dt 的路程接近；连续绕行能到站；暂停不改变路程；转弯时车厢保持在轨。',avoid:'不增加道岔、多车调度或真实牵引模型。',sources:['train.js']},
{name:'自然细节',goal:'让地形拥有层次，让水流和植被拥有可解释的运动。',deliver:'受约束的实例化树木、贴岸水面、瀑布与风动。',tasks:['按坡度和位置分布树木，排除轨道、建筑与关键视线区域。','将水深写入网格属性，先做岸边渐变，再做法线波纹与泡沫。','用共享时间和风驱动植被与落叶，保持阴影位移一致。'],accept:'树木不侵入净空；浅滩无硬切边；暂停时间后自然动画停止；高低细节切换不出现显著跳动。',avoid:'不引入完整流体求解或每个叶片的 CPU 物理。',sources:['vegetation.js','river.js','cascade.js']},
{name:'环境气氛',goal:'让昼夜雨景成为一组协调变化的状态。',deliver:'四种环境预设、共享湿度与风雨、车灯与有限 Bloom。',tasks:['定义统一的环境数据，区分目标值和当前插值状态。','连接天空、雾、太阳、环境光、湿润材质与车灯。','加入雨丝和低分辨率高光后处理，保留暗部层次。'],accept:'切换模式不出现全屏闪白；夜间仍能辨认主要结构；湿润变化连续；雨量与水面涟漪一致。',avoid:'不把换背景色当作完整昼夜效果，也不承诺物理准确天气。',sources:['main.js','weather.js','luminous.js']},
{name:'叙事镜头',goal:'让镜头提前等待事件，并保持用户随时可接管。',deliver:'主视角、桥梁、出隧道、站台等构图与事件切换。',tasks:['人工保存 position 与 target，围绕关键事件设计镜头。','用线路进度触发镜头并限制最短驻留时间。','加入位置与目标点缓动、地形避让及用户拖动退出机制。'],accept:'能看到列车出洞和到站；镜头不过度抬升或穿地；拖动立即退出自动模式；竖屏保持主体可见。',avoid:'不使用始终追车代替构图，也不宣称通用碰撞系统已完成。',sources:['cinematography.js']},
{name:'性能收敛',goal:'在明确设备与视角上验证预算，再做有针对性的降本。',deliver:'统计读数、LOD、阴影与反射节流、可解释的画质降级。',tasks:['记录测试设备、视角、分辨率和 GPU timer 可用性。','分别定位几何、像素和多次渲染开销，采用实例化 / LOD / 低分辨率 Bloom。','加入带持续时间与冷却的 DPR 调节，并复查夜雨模式和移动镜头。'],accept:'测试结果有设备和场景条件；画质调节不会振荡；低档位仍可理解场景；核心运行检查仍通过。',avoid:'不把作者单机 60 fps 当作所有设备保证，不为一次慢帧立即降低画质。',sources:['render-budget.js','main.js']}
];
export function promptFor(index,theme){const s=stages[index];return`为「${theme.trim()||'山间铁路'}」实现第 ${index+1} 阶段：${s.name}。\n\n目标\n${s.goal}\n\n交付物\n${s.deliver}\n\n实施要求\n${s.tasks.map((t,i)=>`${i+1}. ${t}`).join('\n')}\n\n本阶段边界\n${s.avoid}\n\n验收\n${s.accept}\n请记录实际执行的方法、结果和未验证项；不把视觉近似写成物理仿真。若前置阶段缺失，先补齐最小可运行前提。\n\n参考\n上游 commit：6e8b0fbb806e486d7819b6d297b92f4ecf3d258b\n${s.sources.map(f=>upstream+f).join('\n')}\n如适配源码，保留原作者与 MIT 许可；沿用已有工程结构，先保持默认布局可运行。`}
