import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,trainTarget,trainStep,lighting,budget,arcSamples,trackPoint,camera,validateConfiguration,modules,stages,promptFor} from './model.mjs';
test('列车能从不同距离进站并完整驻留，步长变化不产生明显到站时间偏差',()=>{
 for(const distance of [5,30,60]){const times=[];for(const dt of [1/30,1/60]){let s={ahead:distance,v:Math.min(3.1,trainTarget(distance,1,.2).target),dwell:0,done:false},elapsed=0;while(!(s.done&&s.dwell===0)&&elapsed<150){s=trainStep(s,dt,1,.2);assert.ok(s.v>=0&&s.ahead>=0);elapsed+=dt;}assert.equal(s.done,true);assert.equal(s.v,0);assert.equal(s.ahead,0);times.push(elapsed);}assert.ok(Math.abs(times[0]-times[1])<.25);}
 assert.equal(trainTarget(0,1,0).target,0);assert.ok(trainTarget(60,1,.8).target<trainTarget(60,1,0).target);
});
test('环境过渡有界，灯光快于湿润，零时间保留黄昏',()=>{const initial=lighting('night',0);assert.equal(initial.sun,3.6);const s=lighting('night',1);assert.ok(s.sun>.52&&s.sun<3.6);assert.ok((s.night-.14)/.86>s.wet/.46);const end=lighting('night',20);assert.ok(Math.abs(end.sun-.52)<1e-8);assert.ok(Math.abs(end.wet-.46)<1e-5);});
test('LOD 滞回保留中间区间状态，DPR 不会降至 1 以下',()=>{const p=defaults('budget');assert.equal(budget({...p,distance:65,near:'yes'}).near,true);assert.equal(budget({...p,distance:65,near:'no'}).near,false);assert.equal(budget({...p,distance:59,near:'no'}).near,true);assert.equal(budget({...p,distance:73,near:'yes'}).near,false);assert.equal(budget({...p,dpr:1,duration:4}).dpr,1);assert.equal(budget({...p,duration:2.5}).dpr,1.5);assert.ok(budget(p).saved>0);});
test('轨道闭合，近似弧长采样可用且密度增加不改变路径长度',()=>{assert.deepEqual(trackPoint(0),trackPoint(1));const a=arcSamples(30,.34),b=arcSamples(90,.34);assert.equal(a.length,b.length);assert.equal(b.samples.length,90);const ds=b.samples.map((p,i)=>{const q=b.samples[(i+1)%90];return Math.hypot(p[0]-q[0],p[1]-q[1])});assert.ok(Math.max(...ds)/Math.min(...ds)<1.03);});
test('镜头起止点稳定，采样地形保有净空',()=>{for(const height of [0,12,22]){const c=camera({height,time:2.7,distance:60});assert.equal(c.e,.5);assert.equal(c.y(0),6);assert.ok(Math.abs(c.y(1)-6)<.001);for(let i=1;i<32;i++)assert.ok(c.y(i/32)-c.ground(i/32)>=2.3-1e-8);}});
test('模块切换参数原子验证，错误输入不会修改当前状态',()=>{const current={module:'terrain',view:'anatomy',parameters:defaults('terrain')},before=structuredClone(current);const next=validateConfiguration({module:'train',view:'lab',parameters:{ahead:12}},current);assert.equal(next.parameters.ahead,12);assert.equal(next.parameters.speed,1);for(const input of [{module:'wrong'},{module:'train',parameters:{speed:9}},{parameters:{peak:NaN}},{parameters:[]},{parameters:{peak:30,missing:1}}])assert.throws(()=>validateConfiguration(input,current));assert.deepEqual(current,before);});
test('八项能力与六阶段任务均有实际内容和固定版本来源',()=>{assert.equal(modules.length,8);assert.equal(new Set(modules.map(m=>m.id)).size,8);for(const m of modules){assert.ok(m.steps.length>=3&&m.sources.length);assert.ok(Object.keys(defaults(m.id)).length>=2)}for(let i=0;i<stages.length;i++){const p=promptFor(i,'雪山铁路');assert.ok(p.includes('雪山铁路')&&p.includes('验收')&&p.includes('6e8b0fbb806e486d7819b6d297b92f4ecf3d258b'));}});
