import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from './vendor/three.module.js';
import {createSpatial} from './scene-world.mjs';import {stationLayout} from './scene-station-layout.mjs';import {createTrain} from './scene-train.mjs';import {createPeople} from './scene-people.mjs';import {createBoarding} from './scene-boarding.mjs';import {soundMix} from './scene-audio.mjs';
test('实际列车与人物完成开门、列车员巡视、上下客与关门，联锁阻止带人移动',()=>{
 for(const composition of['ridge','marsh','classic']){
 const world=createSpatial({composition}),scene=new THREE.Group(),l=stationLayout(world),station=new THREE.Group();station.position.copy(l.origin);station.rotation.y=l.angle;scene.add(station);const train=createTrain(scene,world,0,()=>new THREE.Texture()),shared={time:{value:0},night:{value:0},rain:{value:0},season:{value:new THREE.Vector4(0,1,0,0)}},cast=createPeople({group:station,layout:l},shared),b=createBoarding(train,cast,l);train.service.park();let held=false,states=new Set();
 for(let k=1;k<4000;k++){train.update(.05,k*.05,{speed:1,paused:false,night:0});b.update(.05);cast.update(k*.05,0);states.add(b.stage);if(train.service.held){held=true;assert.equal(train.service.speed,0);}if(train.doorOpen>.001)assert.equal(train.service.speed,0);for(const p of cast.people)assert.ok(p.root.position.toArray().every(Number.isFinite));if(b.completed)break;}
 assert.equal(b.completed,1,composition+' '+b.stage);assert.ok(held&&b.passengerAboard&&b.guardAboard);assert.equal(train.doorOpen,0);assert.equal(train.service.held,false);for(const stage of['开门','上下客','确认发车','列车员回车','关门'])assert.ok(states.has(stage),stage);
 // A subsequent arrival must alight the passenger before boarding again.
 for(let k=1;k<160;k++){train.update(.05,200+k*.05,{speed:1,paused:false,night:0});b.update(.05);}train.service.park();let alighting=false;
 for(let k=1;k<4000;k++){train.update(.05,210+k*.05,{speed:1,paused:false,night:0});b.update(.05);alighting ||=cast.people[1].behavior.state==='下车离开门区';if(b.completed===2)break;}
 assert.equal(b.completed,2);assert.ok(alighting);const p=cast.people[1].behavior.position.clone(),stage=b.stage;b.update(0);assert.ok(p.equals(cast.people[1].behavior.position));assert.equal(b.stage,stage);
 for(let k=0;k<160;k++)train.update(.05,500+k*.05,{speed:1,paused:false,night:0});train.service.park();b.update(.05);assert.ok(train.service.held);b.update(.05,false);assert.equal(train.service.held,false);assert.equal(train.doorOpen,0);
 }
});
test('开门后车身门洞实际贯通，关闭后由门片遮挡',()=>{const train=createTrain(new THREE.Group(),createSpatial(),0,()=>new THREE.Texture()),car=train.cars[0];function hits(){car.updateWorldMatrix(true,true);const from=car.localToWorld(new THREE.Vector3(-3,1.6,1.95)),direction=new THREE.Vector3(1,0,0).transformDirection(car.matrixWorld);return new THREE.Raycaster(from,direction).intersectObjects(car.children,true).map(h=>car.worldToLocal(h.point).x);}train.setDoors(0);assert.ok(hits()[0]<-.9);train.setDoors(1);assert.ok(hits()[0]>.8);});
test('声音随距离、天气与速度变化，暂停和隐藏页面归零',()=>{const a=soundMix({distance:2,waterDistance:2,wind:.8,rain:.7,flow:1,speed:3}),b=soundMix({distance:90,waterDistance:90,wind:.1,rain:0,flow:1,speed:.2});assert.ok(a.train>b.train&&a.water>b.water&&a.wind>b.wind&&a.rain>b.rain);for(const opts of[{paused:true},{hidden:true},{stage:1}])assert.ok(Object.values(soundMix({...opts,wind:1,rain:1,flow:1,speed:4})).every(x=>x===0));});

test('暂停近看停靠时随车人员同步车体，但不推进上下客',()=>{const world=createSpatial(),scene=new THREE.Group(),l=stationLayout(world),station=new THREE.Group();station.position.copy(l.origin);station.rotation.y=l.angle;scene.add(station);const train=createTrain(scene,world,.3,()=>new THREE.Texture()),shared={time:{value:0},night:{value:0},rain:{value:0},season:{value:new THREE.Vector4(0,1,0,0)}},cast=createPeople({group:station,layout:l},shared),b=createBoarding(train,cast,l);train.service.park();train.update(0,0,{paused:true,night:0});const stage=b.stage;b.update(0);assert.equal(b.stage,stage);train.group.updateMatrixWorld(true);const local=l.toLocal(train.cars[0].localToWorld(new THREE.Vector3(-.28,.84,-1.95)));assert.ok(cast.people[2].behavior.position.distanceTo(new THREE.Vector3(local.x,local.y,local.z))<1e-6);});
