// Procedural ambience plus locally generated MiniMax announcements; no runtime credentials or microphone.
export function soundMix({distance=30,waterDistance=30,wind=0,rain=0,flow=0,speed=0,paused=false,hidden=false,stage=5}){
 const active=!paused&&!hidden,near=d=>1/(1+(Math.max(0,d)/18)**2);
 return{wind:active&&stage>=3?.022+wind*.07:0,rain:active&&stage>=4?rain*.075:0,water:active&&stage>=3?near(waterDistance)*Math.min(2,flow)*.10:0,train:active&&stage>=2?near(distance)*(.008+speed*.023):0};
}
export function createSceneAudio(){
 let context,master,analyser,samples,channels={},enabled=false,volume=.35,env=true,rail=true,lastStop=-1,lastBeat=0,voiceEnabled=true,voiceGain,voicePan,voiceSource,voiceBuffers={},voiceLoad=null,voiceStatus="未加载",announcedArrival=-1,announcedDeparture=-1;
 async function loadVoices(){try{const result=await Promise.all(["arrival","departure"].map(async id=>{const r=await fetch(new URL("../assets/audio/"+id+".mp3",import.meta.url));if(!r.ok)throw Error("录音加载失败");return[id,await context.decodeAudioData(await r.arrayBuffer())];}));voiceBuffers=Object.fromEntries(result);voiceStatus="MiniMax 播报已加载";}catch{voiceStatus="播报加载失败，环境音仍可用";}}
 function stopVoice(){if(voiceSource){voiceSource.onended=null;try{voiceSource.stop();}catch{}voiceSource.disconnect();voiceSource=null;}}
 function speak(id){if(!voiceBuffers[id])return false;stopVoice();voiceSource=context.createBufferSource();voiceSource.buffer=voiceBuffers[id];voiceSource.connect(voiceGain);const source=voiceSource;source.onended=()=>{source.disconnect();if(voiceSource===source)voiceSource=null;};source.start();return true;}
 function noise(name,type,frequency){const source=context.createBufferSource(),buffer=context.createBuffer(1,context.sampleRate*3,context.sampleRate),data=buffer.getChannelData(0);let s=193;for(let i=0;i<data.length;i++){s=(s*1664525+1013904223)>>>0;data[i]=(s/4294967296)*2-1;}source.buffer=buffer;source.loop=true;const filter=context.createBiquadFilter();filter.type=type;filter.frequency.value=frequency;const gain=context.createGain();gain.gain.value=0;const pan=context.createStereoPanner();source.connect(filter).connect(gain).connect(pan).connect(master);source.start();channels[name]={source,filter,gain,pan};}
 async function setEnabled(value){if(value&&!context){const AudioContext=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioContext)throw Error('此浏览器不支持场景声音');context=new AudioContext();master=context.createGain();master.gain.value=volume;const limiter=context.createDynamicsCompressor();analyser=context.createAnalyser();analyser.fftSize=256;samples=new Float32Array(256);master.connect(limiter).connect(analyser).connect(context.destination);noise('wind','lowpass',480);noise('rain','highpass',1400);noise('water','bandpass',800);noise('train','lowpass',650);voiceGain=context.createGain();voicePan=context.createStereoPanner();voiceGain.connect(voicePan).connect(master);voiceLoad=loadVoices();}
  if(value){await context.resume();await voiceLoad;}else if(context){stopVoice();await context.suspend();}enabled=!!value;return enabled;
 }
 function tone(f,duration,gain){const o=context.createOscillator(),g=context.createGain(),t=context.currentTime;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
 function update(opts){if(!context||!enabled)return;const levels=soundMix(opts),t=context.currentTime;for(const name of["train","water"])channels[name].pan.pan.setTargetAtTime(Math.max(-1,Math.min(1,opts[name+"Pan"]||0)),t,.1);master.gain.setTargetAtTime(opts.paused||opts.hidden?0:volume,t,.08);for(const[name,value]of Object.entries(levels))channels[name].gain.gain.setTargetAtTime(value*(name==='train'?rail:env),t,.12);channels.wind.filter.frequency.setTargetAtTime(180+opts.wind*700,t,.3);channels.train.filter.frequency.setTargetAtTime(140+opts.speed*230,t,.15);
  voicePan.pan.setTargetAtTime(Math.max(-1,Math.min(1,opts.trainPan||0)),t,.1);voiceGain.gain.setTargetAtTime(voiceEnabled?.75/(1+(opts.distance/24)**2):0,t,.1);if(opts.paused||opts.hidden||opts.stage<3||!voiceEnabled)stopVoice();else if(opts.distance<75){if(opts.stops!==announcedArrival&&["开门","上下客"].includes(opts.boarding)&&speak("arrival"))announcedArrival=opts.stops;if(opts.stops!==announcedDeparture&&opts.boarding==="确认发车"&&speak("departure"))announcedDeparture=opts.stops;}
  if(!opts.paused&&!opts.hidden&&opts.stage>=2&&rail){if(opts.stops!==lastStop){if(lastStop>=0&&opts.dwell>0)tone(660,.6,.055/(1+opts.distance/15));lastStop=opts.stops;}if(opts.speed>.2&&t-lastBeat>Math.max(.12,1.3/(opts.speed+.1))){lastBeat=t;tone(85,.07,levels.train*.7);}}
 }
 return{setEnabled,update,silence(){stopVoice();if(master)master.gain.setTargetAtTime(0,context.currentTime,.03);},setVolume(v){volume=Math.max(0,Math.min(1,v));},setCategory(name,v){if(name==='voice'){voiceEnabled=!!v;if(!v)stopVoice();}else if(name==='environment')env=!!v;else rail=!!v;},get voiceStatus(){return voiceStatus},get voicePlaying(){return !!voiceSource},get level(){if(!enabled||!analyser)return 0;analyser.getFloatTimeDomainData(samples);return Math.sqrt(samples.reduce((s,x)=>s+x*x,0)/samples.length);},get enabled(){return enabled},get status(){return context?.state||'未开启'},async dispose(){stopVoice();enabled=false;if(context)await context.close();}};
}
